### ISSUE TITLE
Preparing the Wiki

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#10]
Our group repository should include a wiki. Following are the subtasks about the wiki:
- A home page with a brief description of what we are doing and links to the personal pages of the team members
- Aranging the sidebar to include the communication plan, links to personal pages, meeting notes and repository research.

**Comment by AlicanM** [comment]
- brief description of what we are doing  on home page ✓
- links to the personal pages of the team members on home page ✓
- links to the personal pages of the team members on sidebar ✓
