### ISSUE TITLE
[Use Case Diagram] Update the "Annotate" use case

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#106]
The annotating functionality in our platform has changed after the [Annotations Research](https://github.com/bounswe/bounswe2022group7/wiki/Annotations-Research). 

The new user functions shall be added under our [Requirements](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)), and the details about this task can be found in #105. The use case diagram should also be edited accordingly.

The newly added requirements shall be shown under this issue, too so that the work can follow the relevant plan.

**Deadline: 12/04/2022 13:00**
**Reviewer: @demet47**

**Comment by canatakan** [comment]
The use cases that we decided to add about annotating were as below:

> * Adding hyperlinked texts to comments, discussion posts and online gallery/physical exhibition descriptions.
> * Labeling of discussion posts, online galleries, physical exhibitions and art items
> * Bookmarking discussion posts, art items, online galleries and physical exhibitions

Then, the User Requirements were updated, in the light of the desired functionalities mentioned above. 

Finally, the main points that we need to add to the Use Case Diagram and the relevant requirement elements, to be focused on can be roughly described as below:

### 1. Users annotating text segments where they are authorized to do so 
> 1.1.13.1.1: Registered users shall be able to annotate text segments in discussion posts.
> 1.1.13.1.2: Registered users shall be able to annotate text segments in comment sections.
> 1.1.13.1.3: Artists shall be able to annotate text segments in their own exhibition descriptions and online gallery descriptions.
> 1.1.13.1.4: Artists shall be able to annotate text segments in their own art item descriptions.

### 2. Users adding labels to discussion posts, exhibitions, galleries and art items if they are authorized
> 1.1.13.2.1: Registered users shall be able to label discussion posts.
> 1.1.13.2.2: Artists shall be able to label their own exhibition and online galleries.
> 1.1.13.2.3: Artists shall be able to label their own art items.

### 3. Users bookmarking content
> 1.1.13.3: Registered users shall be able to bookmark discussion posts, art items, exhibitions and online galleries.

**Comment by canatakan** [comment]
These use cases mentioned above shall be added to the Use Case Diagram. 

Some significant points to be taken into consideration:

* Adding required conditions so that the only authorized users shall be able to add labels/annotate texts
* Making the distinction between Artist and non-Artist users while working on the use cases about the updates on the exhibitions, online galleries and art items

**Comment by canatakan** [comment]
The changes are made in the Use Case Diagram and the updates can be observed below, too. The changes are now pending your review @demet47. 

### RegisteredUser
<img src="https://user-images.githubusercontent.com/56476673/162927953-6a14a8e5-f6c3-4920-bb97-aad3bfa9a68a.jpeg" width="800">

### Artist
<img src="https://user-images.githubusercontent.com/56476673/162927295-30499053-f3ba-479a-a917-03120984bb7f.jpeg" width="800">

**Comment by demet47** [comment]
![image](https://user-images.githubusercontent.com/64031659/162960667-364e9776-80b0-421b-9380-98d9e63f51b7.png)
Changed <<include>> from "Add anotation to the text segment" and "Add annotation with labels" parts to <<extend>> as above.

**Comment by demet47** [comment]
![image](https://user-images.githubusercontent.com/64031659/162962255-866ec886-5b09-47f6-8f6d-de338c4b7480.png)
- Changed *include* from "Add anotation to the text segment" and "Add annotation with labels" parts to *extend* as above.
- Since two events are done seperately by the user:
    - Seperated nodes for adding custom labels to exhibitions and to online galleries.
    - Seperated nodes for annotating text segments on exhibition descriptions and to online gallery descriptions.
