### ISSUE TITLE
[UML Class Diagram] Add "Annotated" interface with necessary functionality

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#107]
The annotating functionality in our platform has changed after the [Annotations Research](https://github.com/bounswe/bounswe2022group7/wiki/Annotations-Research). 

The new use cases shall be added to our Use Case Diagram and the details about this task can be found in #106. After these use cases are added, the UML Class Diagram should be changed in a way such that:

* The new "Annotated" interface is added.
* All the content classes that can be annotated should **implement** the "Annotated" interface.
* All the use cases added to the Use Case Diagram shall be accessible with the methods existing under the "Annotated" interface.

The newly added use cases shall be shown under this issue, too so that the work can follow the relevant plan.

**Deadline: 12/04/2022 15:00**
**Reviewer: @canatakan**

**Comment by demet47** [comment]
We created a new interface named *Annotate*.
We connected this to below classess and added its method to those class:
- ForumThread
- ForumPost
- ArtItemInfo
- Comment
- Event

ForumPost, ArtItemInfo, EventInfo will contain customized **createAnnotation** method for labeling.
ForumThread, ArtItemInfo, ForumPost, EventInfo, Comment will contain customized **createAnnotation** method for hyperlinking.

Waiting for review : @canatakan

**Comment by canatakan** [comment]
Thank you for your work. Here are the updates:

* Changed the arrows according to the UML notation
* Added `updateAnnotation(body:string, target:string):string` and `removeAnnotation(target:string):bool` methods
* Updated the connections

My review is completed and the final structure can be viewed in our class diagram. The task is now done, and the issue can be closed.
