### ISSUE TITLE
[Sequence Diagram] Complete the sequence diagram for "Annotate" use case

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#108]
As discussed in [Meeting #8](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%238), I shall complete the Sequence Diagram for the case that the user annotates some content in the platform.

A more detailed description about this task shall be provided after the different use cases for annotating are completed as mentioned in #106.

**Deadline: 12/04/2022 17:00**
**Reviewer: @demet47**

**Comment by canatakan** [comment]
Upon the completion of the Annotation use cases, we decided to have these 3 fundamental use cases for annotations:

1. Users annotating text segments where they are authorized to do so
2. Users adding labels to discussion posts, exhibitions, galleries and art items if they are authorized
3. Users bookmarking content

Accordingly, I decided to prepare the sequence diagram for this case:

_The artist labels his/her event and annotates the text in the description of it. The resulting annotations are added to the database._

**Comment by canatakan** [comment]
The sequence diagram that I prepared can be found in the collaborative document. Changes can also be seen below:

<img width="789" alt="seq_annotation" src="https://user-images.githubusercontent.com/56476673/163194146-48822d55-5ead-49b2-8e48-b863a1ba368b.png">

The changes are waiting for a review by @demet47 now.

**Comment by demet47** [comment]
Changed fetchError to addError in all two places.

**Comment by demet47** [comment]
I modified the lifetimes and made it expressive as for creation implications
