### ISSUE TITLE
[Sequence Diagram] Add "search and filter" Diagram

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#109]
A sequence diagram will be created for the use case where the user searches and filters content on the website.

Deadline: 12-05-2022, 17.00
Reviewee: @CahidArda

**Comment by azizamankenova** [comment]
The issue is canceled. 
All of the created sequence diagrams can be found [here](https://github.com/bounswe/bounswe2022group7/wiki/Sequence-Diagrams).
