### ISSUE TITLE
[Sequence Diagram] Create sequence diagram for "Physical Exhibition Creation"

### ISSUE THREAD

**Issue by erimerkin** [bounswe/bounswe2022group7#110]
As decided in [Meeting #8](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%238), creation of a sequence diagram about **Creation of Physical Exhibiton** use case is assigned to me. 

Before starting on the sequence diagram, I will also review the requirements, use case diagram and class diagram to make sure there are no conflict and missing features. 

- [x] Review requirements: #111
- [x] Review use case diagram
- [x] Review class diagram
- [x] Create sequence diagram

After completing the reviews, the specifications and class should be refined enough for a sequence diagram.

**Deadline: 2022-04-12, 17:00
Reviewer: @azizamankenova**

**Comment by erimerkin** [comment]
The structure of diagram is complicated so we first need to asses with TA about how to represent user and user class. I have created an alternative diagram:

![Sequence diagram - Create Physical Exhibition](https://user-images.githubusercontent.com/26660856/163044400-c38f2037-63ff-4cd7-a0a1-ef96f12224e3.png)

This issue will now be withdrawn from review so to proceed after having feedback from TA.

**Comment by azizamankenova** [comment]
The diagram looks great!
Just wanted to make a clarification about return "True: boolean" statement, shouldn't "True" be a variable name? 
And also in other return statements maybe the type of the variables can be added, if the boolean type was added.
Also, I thought the first version of having an artist as an actor only without having an additional artist:Artist is correct. Not quite sure about it, but in the first case a new activation line can be added on top of the previous one in the artist.

**Comment by erimerkin** [comment]
Thank @azizamankenova, I have made the suggested changes and made two versions since I don't know if we should show how sendNotification() method works. Can you review again if everything is correct?

- With workings of sendNotification():
![Sequence diagram - Create Physical Exhibiton](https://user-images.githubusercontent.com/26660856/163473620-fef42e1a-5bbb-4738-ba70-641366b02224.png)

- Without detailed work of sendNotification():
![Sequence diagram - Physical Exhibition Without notification detail](https://user-images.githubusercontent.com/26660856/163474518-e746ae92-3fef-4906-90a0-ec29c3887ecf.png)

**Comment by azizamankenova** [comment]
Thanks @erimerkin! As was discussed, I suppose the first one looks better, as it shows in more detail how a notification is created.

**Comment by erimerkin** [comment]
This issue is reviewed and now complete.
