### ISSUE TITLE
[Requirements] Modify and expand the requirements for "Exhibitions"

### ISSUE THREAD

**Issue by erimerkin** [bounswe/bounswe2022group7#111]
While reviewing class and use case diagrams in issue #110, I have noticed some inconsistencies between Requirements and diagrams in which some features present on diagrams doesn't exist for requirements. I will add these features and try to detail the requirements. 

The usecases and changes that will be done to "Exhibitions" requirements:
1. Editing event information
2. Adding and removing collaborators to events
3. Removing event
4. Clarify the distinction between **Online Galleries** and **Physical Exhibitions**
5. Ability for users to cancel particiation to event

Since this changes is connected to the sequence diagram, it should be reviewed by **@azizamankenova**.

**Deadline: 2022-04-12, 17:00
Reviewer: @azizamankenova**

**Comment by erimerkin** [comment]
Since we have differentiated between **Physical Exhibitions** and **Online Galleries**, I think it is better to rename [this section in requirements](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)/c7374cd19dd30a415d01ad558de8e7c20a0a9703#115-exhibitions).

**Comment by erimerkin** [comment]
I have made the listed changes to the requirements. The changes are listed as:

1. Changed the section name from **"Exhibitions"** to **"Events"**. 
2. Added Functional Requirements

> * 1.1.5.2: Artists shall be able to edit events. [1.2.3.5]
>   * 1.1.5.2.1: Artists shall be able to add collaborators to events.
>   * 1.1.5.2.2: Artists shall be able to remove collaborators from events.
>   * 1.1.5.2.3: Artists shall be able to edit event information (title, description, time, etc.).  
>   * 1.1.5.2.4: Artists shall be able to edit event location in Physical Exhibitions.
>   * 1.1.5.2.5: Artists shall be able to edit external platform links in Online Galleries.
> * 1.1.5.3: Artists shall be able to remove events they created. [1.2.3.6]
> * 1.1.5.4: Artists shall be able to arrange **Online Galleries** using the platform.
>    * 1.1.5.4.1: Artists shall be able to add art items to Online Galleries.
>    * 1.1.5.4.2: Artists shall be able to remove art items from Online Galleries.
>    * 1.1.5.4.3: Artists shall be able to indicate and link an outside platform for their Online Galleries if they choose to host it in another platform.
> * 1.1.5.5: Artists shall be able to arrange **Physical Exhibitions** using the platform.
>    * 1.1.5.5.1: Artists shall be able to mark event location in Physical Exhibitions. [1.2.3.2]
> 
> * 1.1.5.7: Users shall be able to indicate that their participation in the event. [1.2.3.7]
> * 1.1.5.8: Users shall be able to cancel their participation to a event. [1.2.3.7]

3.  Divided 1.1.5.2 to two different requirements: 1.1.5.4 and 1.1.5.5

> * 1.1.5.2: Artists shall be able to arrange exhibitions online or physically using the platform.

to 
> * 1.1.5.4: Artists shall be able to arrange **Online Galleries** using the platform.
> * 1.1.5.5: Artists shall be able to arrange **Physical Exhibitions** using the platform.

4. Updated System Requirements with addition of:
> * 1.2.3.5: System shall only allow the users who created the event to edit it. [1.1.5.2]
> * 1.2.3.6: System shall only allow the users who created the event to remove it. [1.1.5.3]
> * 1.2.3.7: System shall keep track of participating users. [1.1.5.7] [1.1.5.8]

5. Updated indexes of the requirements
6. Updated Table Of Contents link to the sections regarding **Events**.

The changes can be seen in [page revision](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)/2b02b47bad2f5269ed42dafd956e19d44ecadb0e) also it can be visualized [in this link](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)/_compare/c7374cd19dd30a415d01ad558de8e7c20a0a9703...2b02b47bad2f5269ed42dafd956e19d44ecadb0e).

**This issue is now waiting for review to be completed. @azizamankenova**

**Comment by azizamankenova** [comment]
Thanks for the great work, just have a few questions:
- I wanted to clarify if we have curator as it is written in 1.2.3.1?
 `1.2.3.1: System shall be able to filter art exhibitions based on different features. These features shall include: whether it is online or physical, location, date and time, artist, curator, proximity to user location. [1.1.5.5]`
- Also, in 1.2.3.4 wouldn't an artist after registration be able to create events without having any artistic points?
`* 1.2.3.4: System shall allow only the users with sufficient artistic value points to create any kind of event. (Online galleries, Physical exhibitions)`

**Comment by erimerkin** [comment]
> Thanks for the great work, just have a few questions:
> 
>     * I wanted to clarify if we have curator as it is written in 1.2.3.1?
>       `1.2.3.1: System shall be able to filter art exhibitions based on different features. These features shall include: whether it is online or physical, location, date and time, artist, curator, proximity to user location. [1.1.5.5]`
> 
>     * Also, in 1.2.3.4 wouldn't an artist after registration be able to create events without having any artistic points?
>       `* 1.2.3.4: System shall allow only the users with sufficient artistic value points to create any kind of event. (Online galleries, Physical exhibitions)`

Thanks @azizamankenova, I think we don't have curator for events so we can delete it from 1.2.3.1. You are also right about 1.2.3.4, we can delete this item.
