### ISSUE TITLE
[Sequence Diagram] Create a sequence diagram for writing comment

### ISSUE THREAD

**Issue by guneyizol** [bounswe/bounswe2022group7#112]
A sequence diagram representing a user writing a comment needs to be created.

Deadline: 12.04.2022 17:00

reviewer: @atillaturkmen

**Comment by guneyizol** [comment]
I created the sequence diagram [here](https://lucid.app/lucidchart/507965f6-766a-4a4d-83a6-1b72cc8cb821/edit?invitationId=inv_692f0cb0-be36-44ee-871d-91d453e2c91a&referringApp=slack&page=l0w-ywYFXfH3#). It can be reviewed.

**Comment by atillaturkmen** [comment]
Sequence diagram is reviewed, looks good.
