### ISSUE TITLE
[Sequence Diagram] Create sequence diagram for adding art item

### ISSUE THREAD

**Issue by atillaturkmen** [bounswe/bounswe2022group7#113]
A sequence diagram for adding art item needs to be created.

reviewer: @HasanBingolbali

**Comment by atillaturkmen** [comment]
The sequence diagram that I prepared for adding art items is ready for review:

![Screenshot 2022-04-14 233842](https://user-images.githubusercontent.com/59166549/163471799-3965cf1c-493c-4917-bd72-cb935ca168da.png)

**Comment by HasanBingolbali** [comment]
Good job
