### ISSUE TITLE
[Sequence Diagram] Create sequence diagram for "Editing a profile"

### ISSUE THREAD

**Issue by azizamankenova** [bounswe/bounswe2022group7#114]
As decided in [Meeting #8](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%238), the creation of a sequence diagram about **Editing a profile** use case is assigned to me. 

Before starting on the sequence diagram, I will also review the requirements, use case diagram and class diagram to make sure there are no conflicts and missing features. 

- [x] Review requirements
- [x] Review use case diagram
- [x] Review class diagram
- [x] Review the structure of sequence diagrams
- [x] Create sequence diagram

After completing the reviews, the specifications and class should be refined enough for a sequence diagram.

**Deadline: 2022-04-13, 17:00
Reviewer: @AlicanM **

**Comment by azizamankenova** [comment]
I have created a sequence diagram with the help of [plantuml.com](plantuml.com). The diagram can be seen below:

![image](https://user-images.githubusercontent.com/60221908/163266672-a6f05a20-5e72-4442-8a8c-f326e8112e4d.png)

Ready for review @AlicanM

**Comment by AlicanM** [comment]
Looks good, thank you.
