### ISSUE TITLE
[UML Class Diagram] Simplify and merge classes about Forum and Comment

### ISSUE THREAD

**Issue by erimerkin** [bounswe/bounswe2022group7#115]
In [Meeting #9](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%239), we saw that reply system for Discussion Forum is unnnecessarily complex, so we decided to simplify in a linear manner which resulted in a structure nearly the same as CommentSection and Comment classes. These result prompted us to simplify and merge these classes with a new name. So the task list for this issue is:

- [x]  Modify the class diagram:

   1. Rename CommentSection and Comment classes to **ReplyThread** and **Reply** in order.
   2. Merge ForumThread with newly named ReplyThread class
   3. Change the ForumPost thread to accomodate changes
   4. Change the layout of class diagram for easier to understand connections on ReplyThread 
   5. Make extra accomodations to these classes if necessary

- [ ] #117
- [ ] Update the use case diagram with updated names

**Deadline: 2022-04-13, 17:00**
**Reviewer: @azizamankenova**

**Comment by erimerkin** [comment]
We have deleted the ForumThread and ReportThread classes and replaced them with ReplyThread and ReportReply classes. So ReplyThread and ReportReply classes took place of Comment and Forum counterparts. 
The changes are done in a separate page since we had to move most of the classes around to accomodate the connections. It can be checked [here](https://lucid.app/lucidchart/9f163e3c-c9f9-4b98-9e3b-20f0360ebe53/edit?page=g2S-Q3lYQXqG#).

We have marked some methods regarding Forums in some classes so we can discuss it at the next meeting.

We will now modify the requirements to accomodate these changes.

**Comment by erimerkin** [comment]
I have added these sections to requirements:

> * 1.1.4.2: Registered users and artists shall be able to create posts in the discussion forum.
>    * 1.1.4.2.1: Registered users and artists shall be able to edit their posts in the discussion forum.
>    * 1.1.4.2.2: Registered users and artists shall be able to remove their posts in the discussion forum.
> * 1.1.4.3: Registered users and artists shall be able to reply to posts in the discussion forum.
>    * 1.1.4.3.1: Registered users and artists shall be able to edit their replies under discussion posts.
>    * 1.1.4.3.2: Registered users and artists shall be able to remove their replies under discussion posts.
>    * 1.1.4.3.3: Discussions shall include an upvoting system where registered users can upvote or downvote replies.

I have also modified the glossary with the changes:

> * **Post**: An entry created by a registered user on the discussion forum.
> * **Reply**: A comment written by a registered user under posts on the discussion forum.

The changes are present in [this revision](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)/14411325e2b38bb0bb6c85b1b8f99be9f52cf1d0).

I am not sure about these changes on requirements. Should we just call all comments as replies, or should we preserve as comments with a distinction between replies on forum and comments under other entries?

I have also updated the use case diagram by changing **"Thread"** to **"Reply"**. But it may need some more changes depending on the answer to upper question.

So, this issue's completion shall be discussed in the next meeting.

**Comment by demet47** [comment]
![image](https://user-images.githubusercontent.com/64031659/163328858-435a655d-2dde-4bb4-9c45-86b789d1792c.png)

I numerated the composition association between ReplyReport to Reply.
