### ISSUE TITLE
[Requirement] Update the requirements to reflect changes in Discussion Forum and Comments

### ISSUE THREAD

**Issue by erimerkin** [bounswe/bounswe2022group7#117]
As the class diagram is updated with new classes and functionalities for Discussion Forums, "Replies" and comments. The requirements needs review and updates in line with class diagram changes.

**Deadline: 2022-04-13, 17:00
Reviewer: @musasimsekdotdll @azizamankenova**

**Comment by CahidArda** [comment]
Requirements are updated to match the changes we have made to Discussion Forum and Comments:
- Discussion Forum sections are renamed to Threads.
- Glossary is updated to include Thread
- Thread related requirements are transfered to the Threads section

Additionalty report related requirements are removed.

Revision can be seen [here](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)/_compare/6e61d36f40494a9f43fada98e717909c50df69af...1eed792a47c7f105c2eb129b62c78421be71cc7b)

**Comment by demet47** [comment]
![image](https://user-images.githubusercontent.com/64031659/163326586-efdbe82a-0d7e-4cf5-a59d-8054ec11c743.png)

I numerated the composition association between ReplyReport to Reply.

**Comment by erimerkin** [comment]
Revisions on requirements are reviewed in a meeting, this issue is now complete.
