### ISSUE TITLE
[Scenario] Review Scenario 2 according to latest news

### ISSUE THREAD

**Issue by musasimsekdotdll** [bounswe/bounswe2022group7#119]
Scenario 2 should be revised in consideration of Customer Meeting, TA suggestions etc.

**Comment by musasimsekdotdll** [comment]
Reviewer: @mehmeteminipekdal

**Comment by musasimsekdotdll** [comment]
Action items on Scenario 2 are numbered now.

**Comment by mehmeteminipekdal** [comment]
[Numbered Action Items](https://github.com/bounswe/bounswe2022group7/wiki/Scenario-2) can be seen in the link.
