### ISSUE TITLE
[RAM]Add the activity items to the RAM sheet

### ISSUE THREAD

**Issue by azizamankenova** [bounswe/bounswe2022group7#120]
According to the [meeting #8 notes](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%238), the action items that shall be added to the RAM sheet. The following items should be considered:
- items covered from the beginning till the end of this week
- items of the next half of the semester and next semester
Assignments of future tasks should be done equally.
Also, the format and design of the google sheet should be completed.

**Deadline: 15.02.2022**

**Comment by CahidArda** [comment]
Items covered till now are added to the RAM. It was reviewed during the meeting. Closing the issue.

**Comment by azizamankenova** [comment]
All the items are now completed, and the future items are also added. The format and design are customized. 
I have equally assigned the future action items. 
It was reviewed and now the issue can be closed.
