### ISSUE TITLE
[Scenario] Review and format Scenario 1 according to given feedbacks

### ISSUE THREAD

**Issue by erimerkin** [bounswe/bounswe2022group7#121]
Scenario 1 needs a review to check if it is inline with last feedbacks. It may also need formatting changes in tune with other scenarios to achieve a visual parity with other scenarios.

**Deadline: 2022-04-16, 22:00
Reviewer: @musasimsekdotdll**

**Comment by erimerkin** [comment]
I have found and fixed some obsolote requirements and index inconsistenciens in Acceptance Criteria. I have also numbered actions and combined some of them into an item rather than multiple items.

**Comment by erimerkin** [comment]
The mockups for Scenario 1 is updated and it is consistent with the feedback as it indicates which action is being done clearly. The changes can now be reviewed for completion. 
@musasimsekdotdll

**Comment by canatakan** [comment]
The changes were reviewed in the meeting and Scenario 1 was finalized. The final version can be found [here](https://github.com/bounswe/bounswe2022group7/wiki/Scenario-1:-Creating-Events).
