### ISSUE TITLE
[Sequence Diagram] Create sequence diagram for Auction

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#128]
Creating the sequence diagram for Auction based on UML Class Diagram, User Diagram and Requirements.
Deadline: 03.00
Reviewer: @guneyizol

**Comment by demet47** [comment]
Class diagram:
- removed putArtItemToAuction(itemOnSale:ArtItem,endingDate:Date) from Auction
other edits for functions and their parameters that are isolated from other usages apart from auction, so I am not mentioning here.

The finalized version of the corresponding sequence diagram can be found [here](https://lucid.app/lucidchart/507965f6-766a-4a4d-83a6-1b72cc8cb821/edit?page=oNh_MI-Bfak3#)

**Comment by guneyizol** [comment]
Everything seems okay with the diagram. 👍
