### ISSUE TITLE
[Project Plan] Complete Project Plan

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#129]
The current project plan only includes the events until the end of Milestone 1. The details of the work done so far could be viewed in #133.

I shall add these elements to the Project Plan:

* Events for the rest of the semester
* Events for CMPE451

It is also possible to include significant meetings in the Project Plan.

**Deadline: 15/04/2022, 12:00**
**Reviewer: @azizamankenova**

**Comment by canatakan** [comment]
Also, the Project Plan does not include resource assignments yet. The resources should be added to the plan. 

The main resource used is our personal efforts. However, for some tasks, we can create sub-teams and handle the resource assignments by using those. An example can be found below:

![image](https://user-images.githubusercontent.com/56476673/163523917-8bcff13d-1627-4961-b510-1afcdf077c2f.png)

**Comment by canatakan** [comment]
Also, using `Predecessor` feature can be useful to plan subsequent tasks as it will clearly show the dependency and will be helpful to determine the dates for the tasks.

**Comment by canatakan** [comment]
The Project Plan is added to [this Wiki page](https://github.com/bounswe/bounswe2022group7/wiki/Project-Plan).

Right now, plan for CMPE352 is not uploaded yet since RAM is not completed by all members. Waiting for each member to complete their part in RAM so that viewing their contribution to the past tasks in an easier way will be helpful while adding resources to the past tasks in the Project Plan.

So, the first part of the Project Plan is waiting for everyone to finish their part in RAM to be uploaded.

**Comment by canatakan** [comment]
First part is also added after the completion of RAM. [Project Plan](https://github.com/bounswe/bounswe2022group7/wiki/Project-Plan) is now ready for review.

**Comment by azizamankenova** [comment]
Thanks for your work @canatakan. The Project Plan looks great and it was reviewed during the meeting. 
The issue can be closed now.
