### ISSUE TITLE
[Sequence Diagram] Create sequence diagram for "Edit Online Gallery"

### ISSUE THREAD

**Issue by erimerkin** [bounswe/bounswe2022group7#134]
Since we didn't cover any use cases about Online Galleries, it was decided to add a sequence diagram about Online Galleries. I am assigned to create a sequence diagram covering "Edit Online Galleries". 

**Deadline: 2022-04-15, 17:00**

**Comment by erimerkin** [comment]
I have created sequence diagram for "Edit Online Exhibition", it could be seen in the screenshot below:
![Sequence diagram - Edit Online Gallery](https://user-images.githubusercontent.com/26660856/163576119-b07a50f5-fbb8-4045-b2a2-79bd3012546e.png)

The issue is now ready for review.

**Comment by canatakan** [comment]
The task was reviewed during the submission meeting, and it is now finalized. The finalized version can be found [here](https://github.com/bounswe/bounswe2022group7/wiki/Sequence-Diagrams).
