### ISSUE TITLE
Research for issue labels

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#14]
Should make research about the issue labels in order to provide more comprehensive but concise issue labels.

In order to have an idea on how issue labels are used in different repositories, I shall:
- [x] Browse popular high-quality repositories
- [x] Check the groups from the previous years

**Comment by canatakan** [comment]
### Examples

Some popular repositories:
https://github.com/facebook/react/labels
https://github.com/PrefectHQ/prefect/labels
https://github.com/microsoft/PowerToys/labels

Another group from previous year:
https://github.com/bounswe/2021SpringGroup6/labels

**Comment by canatakan** [comment]
I now checked various repositories and here are some findings:

- It is a good idea to have different groups for issue labels. The group name can be separated from the type with a semicolon. For instance, a group name may be "Status" and the type can be "In Progress" or "Done". So, the label name could be "Status: In Progress".
- "Status" label should be added.
- "Priority" label should be added.
-  A "Research" type should be added to show an issue is about making some research on a specific topic.
- "Difficulty" label can also be included to have an idea about how hard a certain task is.

**Comment by erimerkin** [comment]
Issue is marked as completed, closing the issue.
