### ISSUE TITLE
Make research about dockerization and document it	

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#140]
We shall conduct a research on how to dockerize our Practice Application, then report the results.

* Since it was decided that we will use Flask for back-end, this research should be focused on dockerization of Flask applications.
* The document for the research can be added to the Wiki page in our repository.
* We can also share some content with the team so that everybody can use those for learning more about Docker.

**Deadline: 02/05/2022, 23:59**

**Comment by canatakan** [comment]
This task was delayed until [Meeting 11](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%2311) since there were still some conversations as to which tools/frameworks we will use for the Practice App.

Now, since it was finally decided that we are going to use Flask, we can start doing the research focusing on dockerization of Flask applications. Changing the deadline of the issue, setting it to the next Monday (02/05/2022), and starting to work.

**Comment by canatakan** [comment]
Here are some articles that I used during the research:
* [What is Docker?](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/container-docker-introduction/docker-defined)
* [Docker Docs - Build your Python image](https://docs.docker.com/language/python/build-images/)
* [How to Dockerize a Flask Application](https://www.freecodecamp.org/news/how-to-dockerize-a-flask-app/)
* [How to Upload Docker Image to Docker Hub](https://programatically.com/how-to-upload-docker-image-to-docker-hub)

**Comment by canatakan** [comment]
Also, some video resources for dockerizing Flask applications can be found below:
* [Docker Tutorial - basic setup a Python Flask Application in a Docker container](https://www.youtube.com/watch?v=GVs26OxzE3o)
* [How to build Docker Images for a Flask App](https://www.youtube.com/watch?v=wrMJoKpK2mk)
* [How to Deploy a Docker App to AWS using Elastic Container Service (ECS)](https://www.youtube.com/watch?v=zs3tyVgiBQQ)

**Comment by canatakan** [comment]
* The documentation for the research is completed. You can see the report [here](https://github.com/bounswe/bounswe2022group7/wiki/Docker-Research). 
* The report is also added to the side bar.
* @musasimsekdotdll,  please review the report prepared and complete any missing point or add any contribution that you consider necessary.

**Comment by musasimsekdotdll** [comment]
Hi @canatakan, I have reviewed the report. It seems perfect; however, there are some points where I think that some changes can be made so that the report will be nicer:

- In the dockerizing guide:
    1. At the first step of dockerizing guide, the hyperlink for signup page of docker was not working somehow. The request was redirected to creation of a new page in the wiki, I corrected that.
    2. I have added a line saying that installation pages show proper installation of Docker Desktop and specified in which platform the login operation should be made(_Sign in to your Docker Hub account in Docker Desktop_).
    3. You noted that 
        > In our project, since we will also use a database, the directory structure should be consistent with where the database is created.
        
        at the step 5. Have we decided which database structure we will use in the practice app? If we select a relation oriented -like MySQL- or document oriented -like MongoDB- database structure, we don't have to consider the location of database records. This item needs further work.
    4. A brief explanation for tag option of the command used at the 6th step is added. 

Please check whether you feel comfortable with these changes and inform me about the database structure. Thanks in advance!

**Comment by canatakan** [comment]
Thank you for all your updates. About the third statement, 

> iii. ...  If we select a relation oriented -like MySQL- or document oriented -like MongoDB- database structure, we don't have to consider the location of database records. This item needs further work.

* I think we are going to use SQLAlchemy but it was not finalized. 
* I was not exactly sure about this statement but what I actually meant was that we need to be consistent with the directory structure while deciding on where to create the database. 
* In conclusion, since this is not definite yet, I am deleting it from the research report.

**Comment by canatakan** [comment]
I have just completed the minor updates on the report according to your feedback. Relevant revision can be found [here](https://github.com/bounswe/bounswe2022group7/wiki/Docker-Research/e3fe7849d4ffd97f07dd46af687abb9d51dcfd55).

- Made a minor change on your tag explanation to make it more clear.
- Deleted the statement about the database directory structure.

**Comment by canatakan** [comment]
The report is finalized according to your feedback and updates. The task is now done, and the issue can be closed.
