### ISSUE TITLE
Make research about testing API/RESTClient using Postman and document it

### ISSUE THREAD

**Issue by azizamankenova** [bounswe/bounswe2022group7#141]
The following items should be completed: 

- [x]  conduct research about testing API/RESTClient using Postman
- [x] add a Wiki page to our repository with the research outcomes
- [x] provide the links for further information

**Deadline: 28/04/2022**

**Comment by azizamankenova** [comment]
All the tasks are completed. The wiki page can be found [here](https://github.com/bounswe/bounswe2022group7/wiki/Research-on-testing-API-using-Postman). 
The link is also added to the sidebar in the wiki.
This issue is ready for review during the next group meeting.

**Comment by CahidArda** [comment]
Report was reviewed during [meeting #11](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%2311). Closing the issue.
