### ISSUE TITLE
Research about Flask framework and document the results

### ISSUE THREAD

**Issue by erimerkin** [bounswe/bounswe2022group7#143]
In [Meeting 10](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%2310), we decided to research available framework options for API creation on Practice-App. We will research about Flask. The research should include:

- How to setup and use Flask
- Link to sample/example projects using Flask
- General usecases of framework
- Advantages over other frameworks

Then, the results should be documented in a wiki page which should be shared in this issue.

**Deadling: 2022-04-28, 21:00**
**Revivewer: The results will be reviewed at the next group meeting.**

**Comment by atillaturkmen** [comment]
We can use this official document to start developing flask applications:
https://flask.palletsprojects.com/en/2.1.x/quickstart/

**Comment by erimerkin** [comment]
I have created a page to follow the simple steps on installing/creating/running and testing a Flask application. It can be checked [here](https://github.com/bounswe/bounswe2022group7/wiki/Research-on-Flask-Framework) and we can add more detail to it. @atillaturkmen

**Comment by atillaturkmen** [comment]
Very helpful research page, I added more advantages and disadvantages. I think the research page is sufficient in this state.
