### ISSUE TITLE
Research on Unit Testing in Python

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#145]
Search for general properties of Unit testing and extract highlights.
Search about existing frameworks for Python and select one of them to document.
Deadline : 1/05/2022 , 17:00
Reviewer: @mehmeteminipekdal

**Comment by demet47** [comment]
Found useful brief explanation of general Unit Testing concept:
https://www.guru99.com/test-automation-framework.html

**Comment by demet47** [comment]
Selected unittest framework. 
I will summarize the official documentation from below link:
https://docs.python.org/3/library/unittest.html

**Comment by demet47** [comment]
Covered most parts. Just left a brief part from [here](https://docs.python.org/3/library/unittest.html#load-tests-protocol) to the end of the documentation to my pair @mehmeteminipekdal to summarize and append to the research document I sent. He later will convey the whole document to github.

**Comment by mehmeteminipekdal** [comment]
Research were finished and converting notes into GitHub site is finished also, it can be found [here](https://github.com/bounswe/bounswe2022group7/wiki/Unittest-Research)
