### ISSUE TITLE
[Database] Implement "ArtItem", "DiscussionPost", and "Comment" models

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#150]
[\_\_init.py\_\_](https://github.com/bounswe/bounswe2022group7/blob/practice-app/database-base/practice-app/website/__init__.py) and [models.py](https://github.com/bounswe/bounswe2022group7/blob/practice-app/database-base/practice-app/website/models.py) files are created with fundamental functions. 

Given those, I shall implement `ArtItem`, `DiscussionPost`, and `Comment` models.

- Implement mentioned models
- Push the updates to the [practice-app/database-base](https://github.com/bounswe/bounswe2022group7/tree/practice-app/database-base) branch

**Deadline: 06/05/2022, 14:00**
**Reviewer: @azizamankenova**

**Comment by canatakan** [comment]
* I decided to implement different models for `PostComment` and `EventDiscussionComment` items. 

* The former refers to the comments made under the discussion posts in the separate forum page whereas the latter represents the question-like comments under the event pages.

**Comment by canatakan** [comment]
The mentioned models are implemented. The relevant commit can be viewed [here](https://github.com/bounswe/bounswe2022group7/commit/fdd037048f3ee852155e89451709405c6b413675). The task is now pending the review of @azizamankenova.

**Comment by azizamankenova** [comment]
The models look good, thanks for your work. The issue can be closed now.
