### ISSUE TITLE
[Database] Implement "Events", "Participants", "Users", "Artist" models

### ISSUE THREAD

**Issue by azizamankenova** [bounswe/bounswe2022group7#151]
As was decided in the internal meeting and stated in the #148, I am responsible for implementing the following models:
- Events
- Participants
- Artist

After implementing these models, the changes should be pushed to the [practice-app/database-base](https://github.com/bounswe/bounswe2022group7/tree/practice-app/database-base) branch

**Deadline: 06/05/2022, 14:00
Reviewer: @canatakan **

**Comment by canatakan** [comment]
I made minor changes in the code. You can check my comments on your commit. Also, my latest updates can be found [here](https://github.com/bounswe/bounswe2022group7/commit/2a596f7db4be9481832adf42fdccbde0aa83a225).

This task is now completed. Closing the issue.

**Comment by canatakan** [comment]
Also, I have just noticed a naming error. Fixed it. You can view it in [this commit](https://github.com/bounswe/bounswe2022group7/commit/f9a246cf7b7f88ebf1a1e9eb6f3691787e28668d).
