### ISSUE TITLE
[Practice App] Event Related Features

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#158]
In [Meeting Notes #12 - 06/05/2022](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%2312), we assigned features to team members. I was assigned handling event related features.

# Requirements

- Users shall be able to view the events on the website
- Users shall be able to view the weather forecast for the location of the event
- Users shall be able to create events

I will create two pages to handle these requirements. Frontend templates of these pages were already prepared in #147.

# Use Case Diagram

![image](https://user-images.githubusercontent.com/57228345/168571757-eb8914d3-72dc-48c6-8c4c-1c20ab98de9a.png)

# Class Diagram

![image](https://user-images.githubusercontent.com/57228345/169153048-5128659e-4554-45ab-8d63-683657f65dda.png)

# Sequence Diagrams

![Sequence diagram(Practice App) - View Event](https://user-images.githubusercontent.com/57228345/169153331-2ac1d9df-595e-44d5-a4d6-635d514eed05.png)

![Sequence diagram(Practice App) - Create Event](https://user-images.githubusercontent.com/57228345/169153315-c0c23827-f795-4316-9b7e-358678ae7347.png)

# Feature Implementations
I want to start with completing the basis of the features I will handle:
- [x] Create a new branch based on the [practice_app](https://github.com/bounswe/bounswe2022group7/tree/practice_app) branch.
- [x] Form in the [create_event.html](https://github.com/bounswe/bounswe2022group7/blob/practice_app/practice-app/website/templates/create_event.html) doesn't send a JSON. It sends form-data. This needs to be changes so that the form sends a POST request with JSON.
- [x] Create an endpoint for creating an event in [event.py](https://github.com/bounswe/bounswe2022group7/blob/practice_app/practice-app/website/api/event.py).
- [x] Create an endpoint for viewing a particular event in [event.py](https://github.com/bounswe/bounswe2022group7/blob/practice_app/practice-app/website/api/event.py)
- [x] Connect the frontend templates ([create_event.html](https://github.com/bounswe/bounswe2022group7/blob/practice_app/practice-app/website/templates/create_event.html) and [view_event.html](https://github.com/bounswe/bounswe2022group7/blob/practice_app/practice-app/website/templates/view_event.html)) to the api endpoints
- [x] Update the sidebar in the [base.html](https://github.com/bounswe/bounswe2022group7/blob/practice_app/practice-app/website/templates/base.html) by adding a link to the creating event feature.
- [x] Create a PR and add @atillaturkmen as reviewer.

**Deadline: 10.5.2022**

# Polishing
There will be some things to polish in the features. These are:
- [x] When a request is made to create an event, we don't do anything on the front-end. User keeps seeing the same page. We should:
    - redirect to the page of the created event if the event is created succesfully
    - Show a warning if the event wasn't created succesfully.
- [x] When we view an event through `/event/<event_id>` URI, we are shown the details about the event. If there is no such event, we show lot's of `undefined`. We should show a warning instead.
- [x] Currently, anyone can create an event using the create_event endpoint. They don't need to be logged in. Since we are not checking whether the user has logged in, we are also not able to save the event creator artist in the database.
- [x] We need to use an external Weather API to display the weather at the location.

# Testing
Once all the work is completed, I need to add:
- [x] Unit testing
- [x] API endpoint testing with Postman

# Documentation
- [x] Write documentation with Swagger 

# Conclusion
Once all the tasks are completed, a PR will be created and @atillaturkmen will be added as reviewer.

**Comment by CahidArda** [comment]
[practice-app/feature/events](https://github.com/bounswe/bounswe2022group7/tree/practice-app/feature/events) branch is created.

**Comment by CahidArda** [comment]
Changes listed in the issue have been completed. There are still a few things to improve:
- [ ] When a request is made to create an event, we don't do anything on the front-end. User keeps seeing the same page. We should:
    - redirect to the page of the created event if the event is created succesfully
    - Show a warning if the event wasn't created succesfully.
- [ ] When we view an event through `/event/<event_id>` URI, we are shown the details about the event. If there is no such event, we show lot's of `undefined`. We should show a warning instead.

I will continue woking on these changes. For now I will create my first PR. I want to merge into practice-app before my group mates start working because I have made a few changes which will be important for my team mates too. These changes include:
- Redesigning the Event class in [model.py](https://github.com/bounswe/bounswe2022group7/blob/practice-app/feature/events/practice-app/website/models.py)
- I added a style section in the [base.html](https://github.com/bounswe/bounswe2022group7/blob/practice-app/feature/events/practice-app/website/templates/base.html) so that the links will be in different lines.

**Comment by CahidArda** [comment]
Thanks for the suggestion @canatakan,

I will update the [views.py](https://github.com/bounswe/bounswe2022group7/blob/practice-app/feature/events/practice-app/website/views.py) according to your suggestion.

@guneyizol also suggested that I update the [API endpoint of the events](https://github.com/bounswe/bounswe2022group7/blob/practice-app/feature/events/practice-app/website/api/event.py). He suggests that I merge the two endpoints `view_event` and `create_event` into a single `event` point. I will change the endpoints accordingly.

**Comment by CahidArda** [comment]
I redesigned the API endpoints. I need to update the unittests accordingly.

**Comment by canatakan** [comment]
Hello @CahidArda, I gave [a feedback](https://github.com/bounswe/bounswe2022group7/commit/4c8bf2b688d9ebea264088c28cd2e070e19328fe#r73849620) to your latest commit about your unit tests. 

I think we should not use the functions that we would like to test under the `setUp` function. It is also even problematic to use `assert` statements in the `setUp` function, probably, as it can cause the entire test to fail.

**Comment by CahidArda** [comment]
Thanks for the feedback @canatakan. It looks like you are correct. @demet47 also warned me about this problem.

Apparently there is a `mock` library which will allow us to bypass the authentication wrappers I had defined in the `jwt.py`. We are currently working on using this library.

**Comment by CahidArda** [comment]
I have tested my API endpoints with Postman.

# View Event

![image](https://user-images.githubusercontent.com/57228345/169150009-e6db895d-5c42-4d29-b78e-3456db626452.png)

# Create Event

For creating an event, I first created an artist token by logging in. Then I added the token to the authorization. Finally, I made a create event request:

![image](https://user-images.githubusercontent.com/57228345/169150613-14c38e19-f04c-44b7-acad-c432131371f3.png)

**Comment by CahidArda** [comment]
My progress and code has been reviewed in all the PRs mentioning this issue. My work related to the event feature has been completed.

I am closing the issue.
Glory To Arstotzka!
