### ISSUE TITLE
[Practice App] Forum Related Features

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#161]
In [Meeting Notes #12 - 06/05/2022](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%2312), I was assigned with the task of creating a Forum API

Users:
- shall be able to post to forum on main page of the forum.
- shall be able to view all the past forums in forum page

The part I am responsible consists of two seperate pages, one for submitting a new forum post and one for viewing all the posts have been sent.

Deadline: 11/05/2022  17.30
Reviewer: @azizamankenova 

**To Be Added If Have Time:**
- [x] An [external API](https://rapidapi.com/community/api/purgomalum-1/details) connection to provide censor
- [x] User authentication for posting to forum
- [x] Edge case checks, try catchs and http error message coverages.

**Test**
- [x] Unit testing
- [x] API endpoint testing

**Comment by demet47** [comment]
The current version has these unique and peculiar properties:
- There are two pages accessible from main page, one for viewing forum page to read all the forums and one for posting new posts to this forum
- When clicking to submit button to post new forum post, there appears no sign indicating the post has been successfully sent, neither does any redirection to a different page occur.

**Comment by demet47** [comment]
Created a new branched and pushed the files successfully.

**Comment by demet47** [comment]
Added an external api call. Changed the API we decided on in meeting. Has less free calls per day (50 calls per day).

**Comment by CahidArda** [comment]
Hi there Demet,

I think we should not commit our API keys to a public space like GitHub. This was asked in the begining of PS today. API keys should be environment variables and then these environment variables should be read when we run the app. You can see something similar [here](https://github.com/bounswe/2021SpringGroup6/blob/master/practice-app/website/settings.py).

**Comment by demet47** [comment]
> Hi there Demet,
> 
> I think we should not commit our API keys to a public space like GitHub. This was asked in the begining of PS today. API keys should be environment variables and then these environment variables should be read when we run the app. You can see something similar [here](https://github.com/bounswe/2021SpringGroup6/blob/master/practice-app/website/settings.py).

Thanks for the feedback! I will edit it accordingly, I had it in my mind to change but I didn't know how; now I do.

**Comment by demet47** [comment]
Notes for handling errors inside APIs:
- When description for a new post is empty, **500 INTERNAL SERVER ERROR** occurs ==> I provided an error message JSON return value as this: {"error": f"You have not provided body of the post"} , with an error code 400
- Written a try catch to cover an erroneous return from the [external api](https://rapidapi.com/community/api/purgomalum-1/details) => test it with giving a false key for BAD_WORDS_KEY from command line
- Covered database addition and extraction with try-catch blocks in case of an error with 500 code error.

**Comment by demet47** [comment]
Cuurently working on unittests, a little challenging since authentication should be mocked.
After writing unit tests, I will merge my branch to the main branch.

**Comment by demet47** [comment]
> Cuurently working on unittests, a little challenging since authentication should be mocked. After writing unit tests, I will merge my branch to the main branch.
Merged successfully

**Comment by demet47** [comment]
> Currently working on unittests, a little challenging since authentication should be mocked. After writing unit tests, I will merge my branch to the main branch.

Merged my branch to practice_app

**Comment by demet47** [comment]
![image](https://user-images.githubusercontent.com/64031659/169422298-8292b7e3-4607-4724-a3ef-b3ff0c99f852.png)
For endpoint /api/forum_post/

![image](https://user-images.githubusercontent.com/64031659/169422445-06ef7dad-03fc-4a99-a5f7-82165b7be70b.png)
For endpoint /api/forum_get/

![image](https://user-images.githubusercontent.com/64031659/169422565-6a271d63-2c60-49f2-81e2-408672cd9da6.png)
Forum posting for nonauthenticated users (nonauthorized as expected).
