### ISSUE TITLE
[Practice App] Comments Feature on the Discussion Forum

### ISSUE THREAD

**Issue by azizamankenova** [bounswe/bounswe2022group7#163]
In [Meeting Notes #12 - 06/05/2022](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%2312), we assigned features to team members. I was assigned to handle the comments feature on the discussion forum.

The requirements are:
- Users shall be able to view the comments under each post on the discussion forum
- Users shall be able to write comments under the posts on the discussion forum

# Feature Implementations
I want to start with completing the basis of the features I will handle:
- [x] Create a new branch based on the [practice_app](https://github.com/bounswe/bounswe2022group7/tree/practice_app) branch
- [x] Create an endpoint for creating a comment
- [x] Create an endpoint for viewing post details and comments of the post on the discussion forum 
- [x] Connect the frontend template to the API endpoints
- [x] add a post request to external translation API to display the translation of the body of the comment
- [x] Create a PR and add @canatakan as a reviewer.

**Deadline: 18.5.2022**

# Testing
Once all the work is completed, I need to add:
- [x] Unit testing
- [x] API endpoint testing with Postman

# Conclusion
Once all the tasks are completed, a PR will be created and @canatakan will be added as a reviewer.

**Comment by azizamankenova** [comment]
- I have created a new branch [practice-app/feature/discussion-comments](https://github.com/bounswe/bounswe2022group7/tree/practice-app/feature/discussion-comments)
- I have created API endpoints for viewing posts with comments and writing new comments, connected API endpoint, can be viewed in this [commit](https://github.com/bounswe/bounswe2022group7/commit/851366f242fe31c36094147935a060afb63dc049)

**Comment by azizamankenova** [comment]
I have modified api responses according to authorization, comments can be posted only by logged-in users, and the name of the logged in user will be written at the comment information. the latest changes can be found in this [commit](https://github.com/bounswe/bounswe2022group7/commit/c554e0462796444a96beb46d83cc733e6507bcad)

**Comment by azizamankenova** [comment]
API testing with Postman is shown below:

![image](https://user-images.githubusercontent.com/60221908/169082972-8eeefabb-59c5-4bac-a2c2-11cb282a02f9.png)

![image](https://user-images.githubusercontent.com/60221908/169083203-071d6adc-e015-41fc-adbe-a47bf01d9ff6.png)
![image](https://user-images.githubusercontent.com/60221908/169083297-904427cb-d804-40c4-848c-7169722d2ba1.png)


![image](https://user-images.githubusercontent.com/60221908/169084332-2e40d84b-c9ff-4e44-86e5-6ec58e71ed99.png)

**Comment by azizamankenova** [comment]
API documentation is added and can be viewed in the following images, was documented using swagger and can be viewed in /apidocs endpoint

![image](https://user-images.githubusercontent.com/60221908/169363597-e429f372-ff4e-4042-b882-da23f28f9519.png)

![image](https://user-images.githubusercontent.com/60221908/169363665-c360bcea-446f-45b2-923d-34692637690b.png)

**Comment by canatakan** [comment]
> All of the tasks are completed, PR #215 is created and this issue is now ready for review of @canatakan

Hello @azizamankenova, I have requested some minor changes. Could you please complete those?

**Comment by canatakan** [comment]
After your updates, the pull request is now merged. You can check [this commit](https://github.com/bounswe/bounswe2022group7/commit/081f0a51e9dc3ccee3ff05337545fb07705ef761).

**Comment by azizamankenova** [comment]
The task is completed and the branch is merged to practice_app successfully.
