### ISSUE TITLE
[Practice App] Prepare the Docker configuration for the project

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#170]
As mentioned in [Meeting #13](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%2313), we shall handle the Docker configuration for the Practice App. Here are some points to consider:

* We may branch out from the [practice_app](https://github.com/bounswe/bounswe2022group7/tree/practice_app) branch. The newly created branch may include the files about **both dockerization and deployment**.

* It is also possible to use Docker Compose for our project purposes.

* Depending on the implementation, we may have a `docker-compose.yaml` and a `Dockerfile` for the Docker configuration. Also, the `dockkerrun.aws.json` file can be added to the same branch, for the deployment.

* **Github Actions** can be used for handling the keys. For this, we can get in touch with the TA later on.

**Deadline: 14/05/2022, 23:59**
**Assignees: @canatakan, @erimerkin**
**Reviewer: @CahidArda**

**Comment by canatakan** [comment]
* The [practice-app/deployment](https://github.com/bounswe/bounswe2022group7/tree/practice-app/deployment) branch is now created and [Dockerfile](https://github.com/bounswe/bounswe2022group7/blob/practice-app/deployment/practice-app/Dockerfile) and [docker-compose.yml](https://github.com/bounswe/bounswe2022group7/blob/practice-app/deployment/practice-app/docker-compose.yml) files are added.

* The application can be run with the command `docker-compose up`.

The task is now ready for review @CahidArda.

**Comment by CahidArda** [comment]
I have tested the docker files:
- I have deployed the app with `docker-compose up`
- I accessed and viewed the app through `http://127.0.0.1:8000/`.

Thanks for the work!
