### ISSUE TITLE
[Practice App] Deploying the Practice App on AWS EC2

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#171]
In #170, docker files for deploying the app on docker are created. Next, we need to deploy the app on an AWS EC2 instance.

@erimerkin had suggested that we use [this repository](https://github.com/aws-samples/build-and-deploy-docker-images-to-aws-using-ec2-image-builder/blob/main/templates/docker-image-builder.yml) as reference which includes a [blog post](https://aws.amazon.com/blogs/devops/build-and-deploy-docker-images-to-aws-using-ec2-image-builder/) explaining the design and deployment.

Deadline: 16.5.2022
Reviewer: @erimerkin

**Comment by CahidArda** [comment]
I opened a free-tier account on AWS and made a spot-instance request.

## Spot Instance Parameters:
- AMI: Amazon Linux 2 AMI (HVM) - Kernel 4.14, SSD Volume Type (ami-0fe23c115c3ba9bac)
- Instance type requirements: 
![image](https://user-images.githubusercontent.com/57228345/168416165-2d282281-70ad-453e-8204-729bdb24c631.png)
- I then created the instance.

## Connection Problems

When I tried to connect to the instance with `ssh`, I couldn't connect. I tried to ping the Public DNS, no response.

I solved the issue by adding a Security Group. I added two inbound rules which allowed all traffic with IPv4 and IPv6.

I was finally able to connect to the instance with `ssh`.

## EC2 Setup

After connecting, I used [this guide](https://gist.github.com/npearce/6f3c7826c7499587f00957fee62f8ee9) as reference and install docker:
```bash
sudo yum update -y
sudo amazon-linux-extras install docker
sudo service docker start
sudo usermod -a -G docker ec2-user

sudo chkconfig docker on
sudo reboot
```

At this point, machine will restart, so the connection will be lost. I waited for a few seconds and then connected with `ssh`. Then I installed `docker-compose`:
```bash
https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
```

Then I manually downloaded the branch with the dockerfiles (see #170):
```bash
wget https://github.com/bounswe/bounswe2022group7/archive/refs/heads/practice-app/deployment.zip
unzip deployment.zip
cd bounswe2022group7-practice-app-deployment/
```

## Errors in Deployment
I believe the version in [the docker-compose.yml](https://github.com/bounswe/bounswe2022group7/blob/2acf29ad30ff70cc92265bb0907ce03333301106/practice-app/docker-compose.yml) was not supported in the latest `docker-compose` I was able to download. Changing the `version` from "3.9" to "3.3" fixed the issue.

## Conclusion
After all the steps above, I was able to run `docker-compose up` and deploy the app. It was accesible through `<public-dns-of-EC2>:8000`

**Comment by CahidArda** [comment]
App is currently deployed at [this link](http://ec2-3-135-64-147.us-east-2.compute.amazonaws.com:8000/), @erimerkin can you review the changes?

If you approve, I will update [docker-compose.yml](https://github.com/bounswe/bounswe2022group7/blob/2acf29ad30ff70cc92265bb0907ce03333301106/practice-app/docker-compose.yml) as I described in the comment above and commit my changes.

**Comment by erimerkin** [comment]
It looks good, server runs successfully. We can make the change you suggest since the server runs successfully without a problem. We may also need to setup a WSGI server for production since it is recommended.

**Comment by CahidArda** [comment]
I just redeployed the app and I didn't have to change the version this time. I guess I didn't download `docker-compose` correctly last time I deployed.

I agree that we need to setup a WSGI server.

Since the task of deploying the app on AWS EC2 is completed and reviewed, I am closing this issue.
