### ISSUE TITLE
[Practice App] Creating a wiki page to document API endpoints

### ISSUE THREAD

**Issue by erimerkin** [bounswe/bounswe2022group7#174]
As decided in [Meeting #13](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%2313) we need a API documentation in our wiki. I was tasked to handle the creation and style of this page. So I shall:

- [x] Create a wiki page for API endpoint documentation
- [x] Create a template for filling API endpoint information
- [x] Make sure that every endpoint is correctly documented till the submission date

**Deadline: 2022-05-17, 00:00**

**Comment by erimerkin** [comment]
I have created the [API Documentation Page](https://github.com/bounswe/bounswe2022group7/wiki/Practice-App-API-Documentation) at wiki and added it to sidebar. I have also added a few examples and a template to streamline the documentation page.

**Comment by erimerkin** [comment]
We have decided to use Swagger for API documentation creation. I will transfer the created documentation to wiki page after everyone implements their documentations.

**Comment by erimerkin** [comment]
Created a wiki page with the help of a tool to convert swagger specification to markdown. Documentation for all api endpoints can be seen in [this page](https://github.com/bounswe/bounswe2022group7/wiki/Practice-App---API-Documentation)

**Comment by azizamankenova** [comment]
Thanks for your efforts! [Practice App API Documentation](https://github.com/bounswe/bounswe2022group7/wiki/Practice-App-API-Documentation) looks great. I have looked through the documentation, and all the endpoints seem to be documented correctly. 
The issue can be closed now.
