### ISSUE TITLE
[Practice App] Wikipedia Definition

### ISSUE THREAD

**Issue by atillaturkmen** [bounswe/bounswe2022group7#175]
In [Meeting Notes #12 - 06/05/2022](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%2312), we assigned features to team members. I was assigned handling wikipedia definition.

I will create an API endpoint for users to search a word in wikipedia.

# Feature Implementations
I want to start with completing the basis of the features I will handle:
- [x] Create a new branch based on the [practice_app](https://github.com/bounswe/bounswe2022group7/tree/practice_app) branch.
- [x] Create an endpoint for posting wikipedia search word.
- [x] Create template for searching word.
- [x] Connect the frontend template to API.
- [x] Update the sidebar in the [base.html](https://github.com/bounswe/bounswe2022group7/blob/practice_app/practice-app/website/templates/base.html) by adding a link to the view profile feature.
- [x] Create a PR and add @demet47 as reviewer.

# Testing
Once all the work is completed, I need to add:
- [x] Unit testing
- [x] API endpoint testing with Postman

# Conclusion
Once all the tasks are completed, a PR will be created and @demet47 will be added as reviewer.

**Comment by atillaturkmen** [comment]
![postman_wikipedia](https://user-images.githubusercontent.com/59166549/168970140-675e6072-4619-4c22-9afb-395507f0a37a.png)

API endpoint testing with Postman

**Comment by CahidArda** [comment]
Reviewed in meeting. Closing the issue.
