### ISSUE TITLE
[Milestone 2] Creating an executive summary to the Milestone Report 2

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#184]
According to Cmpe352_M2_Group_Submission_Instructions document, our Milestone Report 2 should include an executive summary.
I will be gathering the information and writing the part

#### Executive Summary:
– Summary of project and overall status
– URL of your deployed application (including any information we may need to test your
application)
– API URL (documented) – this part was described in detail in your assignment description.
– Basic functionality of your project
– Challenges you met as a group
– List the status of deliverables.

Due to: 18/05/2022
Reviewer: @musasimsekdotdll

**Comment by CahidArda** [comment]
@demet47 had written the introduction to the executive summary, basic functionality of your project, challenges you met as a group and the list the status of deliverables sections for the deliverable.

I added introduction to executive summary, stages of development, app components sections. Then I reorganised the report in the following structure:
![image](https://user-images.githubusercontent.com/57228345/169274568-2715d023-438f-4490-8555-04e19f5c36b0.png)

**Comment by canatakan** [comment]
Summary is completed, and the final report is compiled. It will be ready for submission after the combination with the other deliverables.

This task is completed, and the issue can be closed.
