### ISSUE TITLE
[Milestone 2] Filling personal contributions in the created table in Milestone Report 2

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#186]
As in Milestone Report 1, we are expected to document what we have done so far. I am to document mine to an already created table for it.

**Comment by demet47** [comment]
Created a table in Milestone Report 2 for individual "Personal Contributions".

**Comment by demet47** [comment]
Have filled contributions till finalization meeting which will be held on 19/05/2022. Will update it according to the procedings in that meeting if necessary.

**Comment by canatakan** [comment]
The final report is completed now. Thank you for filling your contributions. 

Closing the issue since the task is done.
