### ISSUE TITLE
[Practice App] Bootstrap Integration

### ISSUE THREAD

**Issue by musasimsekdotdll** [bounswe/bounswe2022group7#207]
In [Meeting 13](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%2313), I was assigned to style some html files so that every team member can do the same for other ones. 

I edited following files and committed the changes to [my branch](https://github.com/bounswe/bounswe2022group7/tree/practice-app/feature/verification1.1):
- practice-app/website/templates/base.html
- practice-app/website/templates/home.html
- practice-app/website/templates/signup.html
- practice-app/website/templates/view_verification_request.html

I also added a [draft html file](https://github.com/bounswe/bounswe2022group7/blob/practice-app/feature/verification1.1/practice-app/website/templates/bootstrap.html) so that additional changes can be done more easily.

Here are some screenshots from the website:

1. Home page without a logged-in user:
![Screenshot (1)](https://user-images.githubusercontent.com/74203551/169174109-7beb90ca-d403-4408-af1f-a404f4fe4153.png)

2. Home page when a user logged in:
![Screenshot (2)](https://user-images.githubusercontent.com/74203551/169174355-49a0b3fd-96a7-4893-8241-cc1b1dacb0b2.png)

3.  Viewing an event:
![Screenshot (3)](https://user-images.githubusercontent.com/74203551/169174387-2fa8f4e6-d88d-4dac-9878-9ac2b229699a.png)

4.  Viewing a verification request:
![Screenshot (5)](https://user-images.githubusercontent.com/74203551/169174495-7dc719b6-b2e8-4178-9b6e-e46499be79a7.png)

5.  Reviewing a verification request:
![Screenshot (6)](https://user-images.githubusercontent.com/74203551/169174551-ac96d52c-89f7-409c-abd5-1689139ea542.png)

6. Bonus(Draft html file):
![Screenshot (7)](https://user-images.githubusercontent.com/74203551/169176031-961c7d55-a61d-4a0e-871e-a4b8a407ddcd.png)

Sharing some links I made use of may be helpful for further works:

- [Introduction to Bootstrap](https://www.geeksforgeeks.org/bootstrap-5-introduction/?ref=lbp)
- [Buttons](https://www.geeksforgeeks.org/bootstrap-5-buttons/)
- [Grouping buttons](https://www.geeksforgeeks.org/bootstrap-5-button-group/)
- [Listing elements](https://www.geeksforgeeks.org/bootstrap-5-list-group/?ref=lbp)
- [Forms](https://getbootstrap.com/docs/4.0/components/forms/)
- [How to link a button to a method with Bootstrap](https://stackoverflow.com/questions/16668906/onclick-on-bootstrap-button)
- [Forms Documentation](https://getbootstrap.com/docs/5.0/forms/overview/)
- [List Documentation](https://getbootstrap.com/docs/5.0/components/list-group/)

Reviewer: @demet47

**Comment by musasimsekdotdll** [comment]
Shall I assign every member so that they can update their templates? Also, converting this issue to a basic wiki file about the Bootstrap may work well. What you say?

**Comment by musasimsekdotdll** [comment]
Since ArtItems are displayed differently in home.html file, I could not have managed to apply List format to the corresponding header. Please do not forget to take this into consideration @canatakan.

**Comment by canatakan** [comment]
> Since ArtItems are displayed differently in home.html file, I could not have managed to apply List format to the corresponding header. Please do not forget to take this into consideration @canatakan.

Thank you for your attention @musasimsekdotdll. I had already updated the structure in `home.html` and created a pull request on #206, it is currently waiting for the review from @AlicanM.

**Comment by canatakan** [comment]
> Shall I assign every member so that they can update their templates? Also, converting this issue to a basic wiki file about the Bootstrap may work well. What you say?

In my opinion, the best way to proceed right now would be preparing a pull request for these updates so that we can:

* Review the work so far
* Integrate the new `base.html` file to our parts

Please make sure that your own branch is ready to be merged, if not, I think you can use a different branch named `practice-app/feature/bootstrap`.

**Comment by musasimsekdotdll** [comment]
All bootstrap implementation is merged to the practice_app branch. I am closing this issue.
