### ISSUE TITLE
Adding Git Research to the Wiki Sidebar

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#22]
A list of links will be compiled and a page will be added to the wiki to show resources for learning more about git.

**Comment by guneyizol** [comment]
I can help with writing the git research page.

**Comment by CahidArda** [comment]
[Using Git and GitHub](https://github.com/bounswe/bounswe2022group7/wiki/Using-Git-and-Github) page is added to the wiki.
