### ISSUE TITLE
[Software Design] Finalize software design documents

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#228]
In a meeting, we shall finalize the software design diagrams for Practice Application.

Tasks are:

- [x] Finalize the Use Case Diagram
- [x] Finalize the Class Diagram
- [x] Export all diagrams and Requirements to PNG files
- [x] Add the exported files to Wiki

**Deadline: 20/05/2022, 13:00**

**Comment by demet47** [comment]
The wiki links to these design documents are as follows:
- [Requirements](https://github.com/bounswe/bounswe2022group7/wiki/Practice-App-Requirements)
- [Use Case Diagram](https://github.com/bounswe/bounswe2022group7/wiki/Practice-App-Use-Case-Diagram)
- [UML Class Diagram](https://github.com/bounswe/bounswe2022group7/wiki/Practice-App-UML-Class-Diagram)
- [Sequence Diagram](https://github.com/bounswe/bounswe2022group7/wiki/Practice-App-Sequence-Diagrams)

All tasks are complete, thus I am closing the issue.
