### ISSUE TITLE
Update team members

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#237]
Since our team members have changed after CMPE352, we need to update the team members section in the sidebar of our Wiki page.

- Old members should be written in strikethrough
- New members should be added
- The communicator should be specified

**Reviewer: @canatakan**
**Deadline: 05/10/2022 23:59**

**Comment by CahidArda** [comment]
I have updated the wiki page. I think we should wait for the new members to join our repository before closing the issue. Then they can create their pages and add hyperlinks to their timesheets.

**Comment by askabderon** [comment]
I created my page and linked it to the team members section. Assigning Sabri to add his profile page and close the issue.

**Comment by CahidArda** [comment]
Names in the home page are updated now. People who left the team are written with strikethrough and new people are added. New teammates should do the following:
- Create a personal page (example)
- Create a time tracking page (example)
- Update your name in the wiki home page to have a hyperlink to your personal page
- Update "team members" and "effort trackers" section of the wiki sidebar by adding your name to the list as a hyperlink.

**Comment by erimerkin** [comment]
After everyone creates their wiki page, we should update the [ReadMe file](https://github.com/bounswe/bounswe2022group7#readme).

Also can we move the previous team members in wiki homepage to bottom of the list for easier readability?

**Comment by canatakan** [comment]
- Since the issue has been open for a long time and waiting for multiple people to finish a task in a single issue may cause delays sometimes, I created the Wiki page for @ENESAYDOGDUOGLU. Please feel free to fill it whenever you have time.
- I have updated our [README](https://github.com/bounswe/bounswe2022group7#readme) file. You can see the relevant commit [here](https://github.com/bounswe/bounswe2022group7/commit/91bf9189b72cecf585fb77281768bd5bac8dbc47).
- Also, I have updated team members in our Sidebar.

The task is now completed. Closing the issue.
