### ISSUE TITLE
Review and update the Sequence Diagram for Annotations

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#240]
As discussed in [Meeting 1](https://github.com/bounswe/bounswe2022group7/wiki/CMPE451-Meeting-Notes-%231), after the software design documents are updated, I should update the Sequence Diagram accordingly.

I worked on the Sequence Diagram for Adding Annotations to an Event. The Sequence Dagram prepared by me can be viewed here: [Sequence Diagrams - 6. Annotation](https://github.com/bounswe/bounswe2022group7/wiki/Sequence-Diagrams#6---annotation)

My task is to update this diagram according to the revised versions of our previously prepared software design documents. After the update, the new diagram should be consistent with the rest of the documents.

**Reviewer: @demet47**
**Deadline: 09/10/2022, 23:59**

**Comment by demet47** [comment]
I have two feedbacks:
1. After the first call of createAnnotation there is a string returned as UML class diagram says which here in this case isn't shown and I think what you pass as annotatedJSONString here with add method just after this method call is that string that is returned from it. If so, you may need to first draw a discontinuous arrow returning that string then call the method with that string. 
2. The second occurance of createAnnotation is just right after the first one. But it seems to me that you wanted to call it on the label you added below that function call. If so, the sequence diagrams use a syntax as such: you can track the sequential flow of all the methods when you read the diagram from top to bottom level by level.

**Comment by canatakan** [comment]
Hi @demet47, thank you for your technical feedback. 

- As I mentioned in [this issue comment](https://github.com/bounswe/bounswe2022group7/issues/242#issuecomment-1273758425), Güney came up with a new way to implement annotations. I believe we should consider it and clarify this point in our customer meeting.
- It is possible that we change the entire implementation process after we get answers from our customer.
- Therefore, I believe it is a better idea to suspend this task until we get the answers.

**Comment by canatakan** [comment]
* I checked the #297 conducted by @CahidArda. As far as I can see now, all these transactions will be handled by the libraries at the end, so I do not think that we should make significant changes in our interface design. Current design is an abstraction of how the annotations should work like at the end.
* Revisions according to your feedback will be sufficient. I will update the new version considering your feedback.

**Comment by canatakan** [comment]
Updates are completed according to your feedback. You can find the details below:

* [Revised Sequence Diagram for Annotations](https://github.com/bounswe/bounswe2022group7/wiki/Sequence-Diagrams#6---annotation)
* [Relevant revision](https://github.com/bounswe/bounswe2022group7/wiki/Sequence-Diagrams/2344643f2abdfa2eee7fe913c178b1565187a77c)

Please review these changes and update this issue accordingly @demet47.

**Comment by demet47** [comment]
For copyrigt infringement, the grey column should be longer. It represents the lifetime of an instance of an object. The lifetime for it here should start from when you get a list of infringements. The object is formed at that moment with data from database. And the success at the bottom is divided to two layers but it could have been united, skipping the transit from the mid-level. Other than that, everything seems fine.

**Comment by demet47** [comment]
The diagram seems fine. I am closing the issue.
