### ISSUE TITLE
Update Communication Plan

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#244]
In our first meeting, we discussed on how to communicate effectively with the modified worflow (this year less design more implementation with teams). I am to implement changes to the [communication plan](https://github.com/bounswe/bounswe2022group7/wiki/Communication-Plan). 

**Reviewer:** @erimerkin 
**Deadline:** 05/10/2022, 23:59

**Comment by erimerkin** [comment]
The changes seems good, thank you @demet47. I am now closing the issue.
