### ISSUE TITLE
Revisions on UML Class Diagram

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#250]
According to [meeting notes](https://github.com/bounswe/bounswe2022group7/wiki/BACKEND-Meeting-Notes-%231---12-10-2022), we decided on some fixations for [UML Class Diagram](https://github.com/bounswe/bounswe2022group7/wiki/Class-Diagram). The fixations are as below:
- Rename ForumPost as Post.
- Remove DiscussionForumPage.
- Remove ReplyThread and rearrange the connections, replacing ReplyThread with the Reply class.
- Rename Thread in requirements with Reply to allign with class diagram terminologically.

**Reviewer:** @askabderon 
**Deadline:** 15/10/2022

**Comment by canatakan** [comment]
Hi @demet47,

I remember we discussed this topic in [Team Meeting 2](https://github.com/bounswe/bounswe2022group7/wiki/CMPE451-Meeting-Notes-%232), and:

- I proposed that we only have: `DiscussionPage`, `DiscussionPost` and `Comment` classes.
    * **Discussion Page:** The page where all Discussion Posts are stored.
    * **Discussion Post:** The post that may include a title, description, labels and image. These posts also have Comments under them.
    * **Comment:** These are written under Discussion Posts, Events and Art Items by other users to discuss about the main content.

- The discussion was not concluded properly but I remember there were many people agreeing with this proposal.

- I know that our Requirements may include ambiguous or even conflicting terminology, but if we agree to proceed with these names, I am willing to update our Requirements, too.

- I don't think that assuming that the terminology in the Requirements is necessarily correct is not the right approach. If they are confusing, we may change them.

As you were actively participating in this discussion @guneyizol @CahidArda, what do you think about this?

**Comment by demet47** [comment]
- After discussing in [backend meeting](https://github.com/bounswe/bounswe2022group7/wiki/BACKEND-Meeting-Notes-%231---12-10-2022) we decided that DiscussionPage class was unnecessary. Storing is done by the database. And showcasing the data is done by frontend, backend should only be an intermediary for providing a getAll (or similar) endpoint to make a database call and transfer the data which will be done by other classes, not a static class like DiscussionPage.
- The naming of others I will switch to the ones you mentioned. I forgot and didn't see them in [meeting notes](https://github.com/bounswe/bounswe2022group7/wiki/CMPE451-Meeting-Notes-%232) so we had decided upon these. 
- We were already going to change requirements and comment under this issue but since it wasn't written yet here thanks for the kind pointing out and double checking.

**Comment by demet47** [comment]
- For Event and ArtItem classes instead of ReplyThread I put CommentLits:List<Comment>
- Since we converted DiscussionPost to be a subclass of Comment, I removed the method it already inherits from its parent
- Renamed Thread with Comment and removed Reply and ReplyThread classes.
- For Admin class I converted removeReply method to removeComment method.
 If everyone agrees with this class structure, I can modify Requirements accordingly @CahidArda @AlicanM @musasimsekdotdll @erimerkin @guneyizol @atillaturkmen @canatakan @askabderon @sabrimete @ekremgezgen

**Comment by sabrimete** [comment]
I agree with the changes. You can modify the requirements accordingly. @demet47

**Comment by demet47** [comment]
Changes in requirements:
- I changed every occurence of "thread" with "comment"
- ı changed the definition of "Reply" in **Glossary** section as follows:  
    - **Reply**: A comment written by a registered user under a comment referencing the parent comment.

**Comment by askabderon** [comment]
Looks good to me, thanks for working on this. If @demet47's comment answers @canatakan's questions we can close this issue.

**Comment by demet47** [comment]
Thanks for the review @askabderon !
