### ISSUE TITLE
Backend Dockerization and Deployment to AWS

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#252]
After [creating an initial project for backend](https://github.com/bounswe/bounswe2022group7/issues/251), we are to deploy it to AWS using dockerization. 

**Reviewer:** @demet47 
**Deadline**: 18/10/2022

**Comment by askabderon** [comment]
I implemented a docker-compose file which can be used for deploy the sql locally. However, I have no access to the AWS part and I think we should wait for this before pushing the docker file.

**Comment by erimerkin** [comment]
I can take from here and try deploying to AWS @demet47, @askabderon

**Comment by askabderon** [comment]
Okay then that's great! I am going to add the docker compose file by end of today @erimerkin.

**Comment by sabrimete** [comment]
If you dockerize the backend with the database, it would be great. 
It may solve the problem I had and mentioned here but I'm not sure: https://github.com/bounswe/bounswe2022group7/issues/251#issuecomment-1280059202

I will try to connect your dockerized AWS server after you completed it.

**Comment by askabderon** [comment]
Implementation is waiting review on dev/docker branch fyi @demet47. After the check is done we can close this issue and create new one for AWS deployment.

**Comment by erimerkin** [comment]
@askabderon, can you create a PR for that branch merging it to backend branch so it can be reviewed?

**Comment by demet47** [comment]
Since a [PR](https://github.com/bounswe/bounswe2022group7/pull/276) is opened on this issue, I am closing the issue; the follow-up will continue there.
