### ISSUE TITLE
Revising System Requirements

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#254]
Our system requirements were not written correctly. We need to update them according to the explanations from the last lecture.

Our system requirements were written as a reflection of every action taken by the back-end. We learned that this is not the correct way.

Deadline: 17.10.2022, 23:59
Reviewer: @erimerkin

**Comment by CahidArda** [comment]
During our meeting as the front-end team, we decided to do the following for each system requirement item:
| Subsection | Action |
| - | - |
| 1 | Delete duplicates of user requiremets. Rest should stay |
| 2 | Will be deleted |
| 3 | 1.2.3.2 and subitems below it will be removed. We will specify in 1.1.5.2 that only artist can perform these actions |
| 4 | Will be deleted. User reports and admin removes: No role of the system |
| 5 | Will stay. We will wait for answers to customer questions |
| 6 | Remove items and add the following: System shall end the auction after some time, say 1 day |
| 7 | Should stay |
| 8 | Should stay. Will ask the team |
| 9 | Delete duplicates of user requiremets. Rest should stay |
| 10 | Will be deleted |

**Comment by guneyizol** [comment]
System requirements are updated according to the decisions made in the frontend meeting.
