### ISSUE TITLE
Implementation of Event, ArtItem and PhysicalExhibition classes

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#256]
According to [backend meeting notes](https://github.com/bounswe/bounswe2022group7/wiki/BACKEND-Meeting-Notes-%231---12-10-2022), I was assigned to write classes below in relation to [UML Class Diagram](https://github.com/bounswe/bounswe2022group7/wiki/Class-Diagram)

- [x] Event Class
- [x] ArtItem Class
- [x] PhysicalExhibition Class

**Deadline:** 17/10/2022 23.59
**Reviewer:** @ekremgezgen

**Comment by ArshErgon** [comment]
What exactly we want to do?

**Comment by demet47** [comment]
I implemented the classes mentioned above. There are some dependent classes non-implemented which gives compile error for now.

**Comment by demet47** [comment]
Since @erimerkin didn't review and the branch PR is already reviewed and merged, I am closing the issue
