### ISSUE TITLE
Implementation of OnlineGallery and ArtItemInfo Classes

### ISSUE THREAD

**Issue by askabderon** [bounswe/bounswe2022group7#257]
According to [backend meeting notes](https://github.com/bounswe/bounswe2022group7/wiki/BACKEND-Meeting-Notes-%231---12-10-2022), I was assigned to write classes below in relation to [UML Class Diagram](https://github.com/bounswe/bounswe2022group7/wiki/Class-Diagram)

Because of the inheritance relation between the classes, I am going to start to work on this after the issue #256 is done.
- [x] Online Gallery Class
- [x] ArtItemInfo Class

**Deadline:** 18/10/2022 23.59
**Reviewer:** @sabrimete

**Comment by demet47** [comment]
I finished the classes sunday night. Sorry that I didn’t arrange the issue status accordingly. The branch name is dev/homepage-demet. I also have some dependant non-implemented classes. I used  them anyway.

**Comment by demet47** [comment]
Hi @askabderon,
The corresponding [issue #256](https://github.com/bounswe/bounswe2022group7/issues/256) is done. You can find it in dev/homepage-demet branch.

**Comment by sabrimete** [comment]
The PR related with this issue is already merged the code seems fine at the moment.
