### ISSUE TITLE
Uploading Target File to the Backend Directory

### ISSUE THREAD

**Issue by askabderon** [bounswe/bounswe2022group7#259]
For the issue #252, I need the default target file in order to implement Dockerfile. @sabrimete is going to upload this file. Then I will be able to finish the docker setup.

**Deadline:** 17/10/2022 23.59
**Reviewer:** @askabderon

**Comment by sabrimete** [comment]
I think you ask for it for the jar file. 
Please try this one to create jar file and let me know if you need anything
https://stackoverflow.com/questions/36105004/intellij-maven-mvn-command-not-found

**Comment by askabderon** [comment]
Yes I meant .jar file, sorry about misnaming it. I tried to run mvn package from command tool and also from IntelliJ and got errors during the build. I saw some discussions about changing the main file, however if it works for you it should not be related to the project code itself. Hence, could you describe the setups you have done for me, because there are many recommendations in the corresponding link.

**Comment by sabrimete** [comment]
I created the jar file by following the comment with a highest score. This link should take you directly to the comment:
https://stackoverflow.com/a/36112620

**Comment by askabderon** [comment]
Figured out that it is relevant with application properties file. I am closing this comment because we do not have anything to upload related to this issue, you can reach me for help in case of any similar error.
