### ISSUE TITLE
Research on Testing Flutter Apps

### ISSUE THREAD

**Issue by musasimsekdotdll** [bounswe/bounswe2022group7#261]
According to the [first meeting of mobile team](https://github.com/bounswe/bounswe2022group7/wiki/MOBILE--Meeting-Notes-%231), I was assigned to make a research on how to test our mobile application.

I have createad a [file](https://github.com/bounswe/bounswe2022group7/wiki/Testing-Flutter-Apps) making introduction to testing concepts.

Deadline: 17.10.2022 23:59
Reviewer: @atillaturkmen

**Comment by musasimsekdotdll** [comment]
If you think anything is missing etc, you can also remark @canatakan and @AlicanM

**Comment by atillaturkmen** [comment]
It looks good, thank you.
