### ISSUE TITLE
Implementation of Profile Page

### ISSUE THREAD

**Issue by musasimsekdotdll** [bounswe/bounswe2022group7#262]
According to the [first meeting of the mobile team](https://github.com/bounswe/bounswe2022group7/wiki/MOBILE--Meeting-Notes-%231), I was assigned to implement the profile page of the mobile application.

There are a few things to do to complete this task:

- [x] cloning the android branch to the local machine
- [x] creating a new branch named _dev/profilepage-musa_ so that changes can be tracked
- [x] actual implementation of the page and connecting to the relevant pages

Deadline: 17.10.2022 23:59
Reviewer: @canatakan

**Comment by musasimsekdotdll** [comment]
I have cloned the android branch to my local machine.

**Comment by musasimsekdotdll** [comment]
I have created a [new branch named _dev/profilepage-musa_](https://github.com/bounswe/bounswe2022group7/tree/dev/profilepage-musa).

**Comment by musasimsekdotdll** [comment]
I have created an initial profile page with no interactivity. The page displays mock profile picture, name, surname, username, a settings icon, an icon indicating verification and various buttons that will classify the activities of that user and shows the asked.

**Comment by musasimsekdotdll** [comment]
Since I cannot add functionality and interactivity, I might not be able to write unit tests. What say you, @canatakan?

**Comment by canatakan** [comment]
* I think testing can be postponed for now as we should decide on a standard way to do it in a meeting.

* If you create a PR and add me as a reviewer, I can review your code and we can start to merge everything into the `android` branch.

**Comment by musasimsekdotdll** [comment]
I will revise my codes according to your implementation since your page seems much more aesthetical. Shall I close this issue and open again when it is finished or keep this issue open until that time @canatakan?

**Comment by canatakan** [comment]
It depends on your preferences indeed.

* You may simply continue tracking your work on this task under this issue by appending your new commits, new PR, etc.
* You may close this issue after marking it as "Cancelled" and open a new one that refers to this issue and explains the situation. Then, you can add your new commits, new PR, etc. there.

Whichever you choose, please let me know when you are done with your implementation so that I can review your code.

**Comment by musasimsekdotdll** [comment]
I have finished reimplementing the profile page.

- When a user is redirected to the profile page, s/he will see this page:

![Ekran Görüntüsü (11)](https://user-images.githubusercontent.com/74203551/197342649-78c2843f-6652-4091-9c66-97246300cc61.png)

    1.  This page will show the profile picture, name and surname, a settings button; followers, followings and invite buttons; a dropdown to select the type of posts to be seen in the remaining of the screen and posts in a list view.
    2. Every element of the list view is just a preview of the actual post. User must touch any point of the list item in order to see the post in details.
    3. Notice that I didn't add the images to the screen in order to gain from space. However, a preview or the full version of the images might be added according to the team decisions.


- In order to change the type of the post listed, the dropdown button must be pressed and one of the options must be selected:

![Ekran Görüntüsü (12)](https://user-images.githubusercontent.com/74203551/197343025-5ee47c61-587e-45d7-b34c-635bf24f2d41.png)

    1. There is a bug that I couldn't solve: When one of the options selected in the dropdown menu, the value of the dropdown button doesn't change. In other words, the value does not become "art items" even if the "art items" option selected in the menu.


- The list view is scrollable, meaning that the elements that could not fit in the screen can be accessed by scrolling down/up:

![Ekran Görüntüsü (13)](https://user-images.githubusercontent.com/74203551/197343323-190ebe63-61a7-4be6-9ecc-ce5e7e125eb6.png)

**Comment by musasimsekdotdll** [comment]
I have removed the _unit test task_ since we do not have any functionality yet, as we discussed.

**Comment by musasimsekdotdll** [comment]
I have created a [pull request](https://github.com/bounswe/bounswe2022group7/pull/279), you can track changes from there.

**Comment by canatakan** [comment]
- Thank you, please check [my review](https://github.com/bounswe/bounswe2022group7/pull/279#pullrequestreview-1152315023) and make necessary updates.

- We can merge after the requested changes are completed.

**Comment by canatakan** [comment]
- `dev/profilepage-musa` is now merged into `android` after the updates (#279).
- Further developments shall be made under the `android` branch.

Since the task is now completed, I am closing the issue.
