### ISSUE TITLE
[Mobile] Implementation of Register Page

### ISSUE THREAD

**Issue by atillaturkmen** [bounswe/bounswe2022group7#263]
According to the [first meeting of the mobile team](https://github.com/bounswe/bounswe2022group7/wiki/MOBILE--Meeting-Notes-%231), I was assigned to implement the register page of the mobile application.

These are the tasks to complete this issue:

- [x] A register page will be created for the mobile app without implementing the network calls.
- [x] There will be email validation via regex.
- [x] User will be navigated to homepage after pushing the register button.
- [x] There will be unit tests for validators.

Deadline: 17.10.2022 23:59
Reviewer: @AlicanM

**Comment by AlicanM** [comment]
UI looks good, fields work as intended.
Thanks for the good work, sorry for the late review.
