### ISSUE TITLE
Implementation of Authentication Part

### ISSUE THREAD

**Issue by askabderon** [bounswe/bounswe2022group7#271]
According to [backend meeting notes](https://github.com/bounswe/bounswe2022group7/wiki/BACKEND-Meeting-Notes-%232-20-10-2022), @sabrimete is assigned to research about built-in functions of Spring Boot for authentication and implemented this part by using them.

**Deadline:** 25/10/2022 23.59
**Reviewer:** @askabderon

**Comment by CahidArda** [comment]
Are there any updates on the status of authentication in back-end?

**Comment by sabrimete** [comment]
There is no progress right now. I am still in the research part of the task.

**Comment by askabderon** [comment]
merged the corresponding branch of this issue with [pull request] (https://github.com/bounswe/bounswe2022group7/pull/317), closing the issue now.
