### ISSUE TITLE
[BACKEND] Implementation of authentication

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#274]
Based on research done for [issue #273](https://github.com/bounswe/bounswe2022group7/issues/273), backend code will be implemented for sign-in, sign-up functionalities. Endpoints for sign-in and sign-up are to be written.

**Reviewer:** @demet47 
**Due:** 21/10/2022 23.59

**Comment by CahidArda** [comment]
Is this a duplicate of #271? Your meeting notes say that authentication was assigned to @sabrimete

**Comment by demet47** [comment]
Ah you are right, I confused the issues I was supposed to open. Thanks!
