### ISSUE TITLE
Implementation of Visitor and Guest Classes

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#278]
According to [backend meeting notes](https://github.com/bounswe/bounswe2022group7/wiki/BACKEND-Meeting-Notes-%232-20-10-2022), I was assigned to write classes below in relation to [UML Class Diagram](https://github.com/bounswe/bounswe2022group7/wiki/Class-Diagram)

- [ ] Visitor Class
- [ ] Guest Class

**Deadline:** 08/11/2022 23.59
**Reviewer:** @demet47

**Comment by askabderon** [comment]
We decided to implement RegisteredUser class at first due to Milestone 1 Login requirements and postpone implementation of these classes. Hence, I am updating the deadline and priority of this issue

**Comment by askabderon** [comment]
During the latest [backend meeting](https://github.com/bounswe/bounswe2022group7/wiki/BACKEND-Meeting-Notes-%234), we talked about the necessity of these classes. It seems like having RegisteredUser and Artist classes is enough to implement the endpoints. Hence, I suspend this issue for a while to be sure about their redundancy.
