### ISSUE TITLE
[Mobile] Implementation of Login Page

### ISSUE THREAD

**Issue by AlicanM** [bounswe/bounswe2022group7#280]
In the first [mobile team meeting](https://github.com/bounswe/bounswe2022group7/wiki/MOBILE--Meeting-Notes-%231), I was assigned to implement the login page.

These are the tasks to complete this issue:

- [x] A UI for the login page will be created without implementing the network calls.
- [x] User will be navigated to homepage after filling username and password fields and pushing the log in button.
- [x] Create a PR after the functionality is implemented.

Reviewer: @atillaturkmen

**Comment by AlicanM** [comment]
UI of the Mobile Login Page
![image](https://user-images.githubusercontent.com/47609112/197414310-0245caf8-c45b-4871-ad29-82b8f447ac74.png)

**Comment by AlicanM** [comment]
Navigators and controllers are added to the login page widgets with [related commit](https://github.com/bounswe/bounswe2022group7/commit/c523ebe0e51d5d7e4c61053701d57ff47a9f535d).
Log In buttons redirects the user to Home Page, without checking authentication since we dont have the backend database ready.
Sign Up Now button redirects to the Register Page

**Comment by AlicanM** [comment]
[PR#281](https://github.com/bounswe/bounswe2022group7/pull/281) is created. Ready to a review.

**Comment by atillaturkmen** [comment]
It looks good and works as intended, thanks for the good work.
