### ISSUE TITLE
Extending Comments component to Cover any User Related Component

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#289]
Currently, we have a Comment component without any functionailty. We need to add the following functionalities:
- Access profile page
- Show level of the user
- Like the comment

We will also add another component in the future to do something very similar: to show the artist name, level and accessing the artist page. The difference will be that we will follow an artist instead of liking. I believe that we can cover these two functionalities under one component. Maybe we can switch to a multiclass structure in the future but one component should do the job.

I will take the following steps:
- I will write a new component UserCard to extend the features of the existing Comment component.
- I will replace the Comment components with UserCard in the CommentsSection
- I will use mock data on the art item page to showcase the usage of UserCard in two different configurations

Deadline: 25.10.2022
Reviewer: @guneyizol

**Comment by CahidArda** [comment]
I have written the UserCard component to replace the Comment component. Here is how it looks with two different configurations:

### UserCard as a comment

![image](https://user-images.githubusercontent.com/57228345/197632026-16923e3e-da12-4b9a-bcf3-0c3e9386bc65.png)

### UserCard as a user

![image](https://user-images.githubusercontent.com/57228345/197632484-97d5ce8e-8a89-48ce-9e5e-82e93a26ae7d.png)

## Common Features

- Observe that the purple circle has a number. This number shows the user level. 
- The menu to the right is a functional menu:
    - can be opened and closed
    - menu item can be clicked to take you to the user profile
- The star is functional:
    - It will be hidden from guest users
    - Changes colors when clicked
    - Calls a function to follow/unfollow a user or like/dislike a comment based on the user card type (comment/user)

**Comment by CahidArda** [comment]
I have used the UserData component I wrote to fill the art item page. I used the mock data I suggested in #287. I took the mock data, processed it and displayed the art item information.

![image](https://user-images.githubusercontent.com/57228345/197633208-1758f65b-ad6f-4177-a151-15b57cbd1c94.png)

**Comment by CahidArda** [comment]
Ready for your review @guneyizol

**Comment by guneyizol** [comment]
It looks cool. I will also inspect in more detail our routing configuration relating to these components.

**Comment by guneyizol** [comment]
Our router is functional and allows token-based authorization of resources.
