### ISSUE TITLE
Token Handling in the Frontend

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#290]
We need to manage the JWT token returned from the backend in the frontend. There are two basic functionalities:
- Block access to some pages: Visitors won't be able to access some pages such as the create art item page. 
- Show different components: Liking a comment can only be done when the user is logged in.

We need to research methods of handling tokens and implement them.

Deadline: 25.10.2022, 23:59
Reviewer: @erimerkin

**Comment by CahidArda** [comment]
I have found this guide on [handling authentication with React Router v6](https://blog.logrocket.com/complete-guide-authentication-with-react-router-v6/#using-nested-routes-and-outlet). It provides a simple code for authentication we can customize for our case.

I had trouble understanding how it functioned because the guide is missing one crucial thing: It never shows how to use the `AuthProvider` it defines. I went down deeper into the rabbit hole and found this [Redirects (Auth) from React Router docs](https://v5.reactrouter.com/web/example/auth-workflow). The guide has a similar structure for authentication to the other guide I had found. With this guide I was able to understand how we will use `AuthProvider` looking at `ProvideAuth` component.

I will now add the code from the first guide. I will have to change the way we create routing browser because we need to encapsulate the whole app inside `AuthProvider`. There is no way of doing this with our current setup.

**Comment by CahidArda** [comment]
I have finished implementing the authenticaiton. We can now protect pages from unauthorised access and render pages differently for visitors and logged-in users.

**Comment by erimerkin** [comment]
@CahidArda, can you also implement a general error/404 page while updating the other parts? [This guide](https://reactrouter.com/en/main/start/tutorial#handling-not-found-errors) is pretty explaining.

**Comment by CahidArda** [comment]
I won't be able to use the guide you sent because I had to change the router structure for the authentication like I wrote in the second paragraph of [my comment above. ](https://github.com/bounswe/bounswe2022group7/issues/290#issuecomment-1290089820). I will try to do what you requested with the new structure though.

**Comment by CahidArda** [comment]
I have added the error page. I didn't bother with styling it for now.

![image](https://user-images.githubusercontent.com/57228345/197715009-01c0e787-343f-4bc9-9b63-caf64c2eb587.png)


Ready for your review @erimerkin.

**Comment by erimerkin** [comment]
Thanks for the changes @CahidArda, I will review it on #291.

**Comment by erimerkin** [comment]
#291 is now merged. Closing this issue.
