### ISSUE TITLE
Save User Information in Local Storage

### ISSUE THREAD

**Issue by atillaturkmen** [bounswe/bounswe2022group7#292]
According to the [second meeting of the mobile team](https://github.com/bounswe/bounswe2022group7/wiki/MOBILE-Meeting-Notes-%232), I was assigned to save user information and make a user provider class. These are the tasks to complete this issue:

- [x] A shared preferences class will be created for storing user information in local storage.
- [x] A user provider class will be created that provides user information to other pages.
- [x] User information entered in login and register pages will be saved in local storage.

Deadline: 25.10.2022 14:00
Reviewer: @canatakan

**Comment by atillaturkmen** [comment]
I have completed the implementation. I have also opened a pull request and added @canatakan as the reviewer.

**Comment by canatakan** [comment]
I gave my feedback in #293 and the branch is now merged. Thank you for your work.
