### ISSUE TITLE
Fix: Unable to Save to Database

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#295]
While trying to save to Database, during [backend meeting](https://github.com/bounswe/bounswe2022group7/wiki/BACKEND-Meeting-Notes-%233) we realaized database save couldn't be made. We are to fix that situation. 

**Reviewer:** @sabrimete 
**Deadline:** 26/10/2022 13.00

**Comment by demet47** [comment]
I fixed the issue by adding the following line to application.properties:
**spring.jpa.hibernate.ddl-auto = update**

Also, another error was showing up which indicated something was not working with database dialect as a follow-up problem. I solved that issue by adding the below line to application.properties:
**spring.jpa.database-platform = org.hibernate.dialect.MySQL5InnoDBDialect**

**Comment by sabrimete** [comment]
When I try to run the branch, it doesn't give an error. Problem seems to be fixed.
