### ISSUE TITLE
Fix Comment and Discussion Post structures

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#296]
* In the current version of our [UML Class Diagram](https://github.com/bounswe/bounswe2022group7/wiki/Class-Diagram), the relationship between Comment and DiscussionPost classes are as follows:

  <img width="700" alt="Screen Shot 2022-10-26 at 16 26 59" src="https://user-images.githubusercontent.com/56476673/198038294-426adeee-bbde-4c49-828e-8835776df900.png">

* This was the way it was designed as the Discussion Post itself was considered a special Comment. Although this may be technically true, making a design like that was confusing. 

* In addition, it was also decided that the recursive structure of the `Comment` class is also complicated. Replies can go infinitely deep in this current design. That is why it was decided that we remove the notion of _"Reply"_ and have an different implementation.

As the result of these discussions, the task of fixing this structure was assigned to me in [Meeting 3](https://github.com/bounswe/bounswe2022group7/wiki/CMPE451-Meeting-Notes-%233).

Here are some subtasks to fix the structure:
- [x] Update the [Class Diagram](https://github.com/bounswe/bounswe2022group7/wiki/Class-Diagram) by fixing the relationship between `Comment` and `DiscussionPost` classes.
- [x] Update [Requirements](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)) by revising the parts including _"Reply"_.
- [x] Update the [Class Diagram](https://github.com/bounswe/bounswe2022group7/wiki/Class-Diagram) by revising the parts including _"Reply"_.

**Deadline: 29/10/2022, 23:59**
**Reviewer: @askabderon**

**Comment by canatakan** [comment]
The updates on the Class Diagram is completed. The updated part is as follows:

![cropped](https://user-images.githubusercontent.com/56476673/198050630-fe622142-2f60-4a10-8fa0-08eb8bb46e4e.png)

* `CommentReport` class is now more general and can be used by `ArtItem`, `DiscussionPost` and `Comment` objects. Hence, renamed as `Report`.
* The inheritance relationship between `DiscussionPost` and `Comment` classes are removed and replaced with the correct relationship.
* The incorrect one-to-one relationship between `Comment` and `ArtItem` and `Event` classes are corrected.
* You can check the minor changes inside the classes as well.

**Comment by canatakan** [comment]
- [The updated UML Class Diagram](https://github.com/bounswe/bounswe2022group7/wiki/Class-Diagram)
- [Relevant revision](https://github.com/bounswe/bounswe2022group7/wiki/Class-Diagram/066ce6adc43eeba8f141941ee6e71c6d20d069a4)

**Comment by canatakan** [comment]
Requirements are now updated according to the changes in the definition of _"Reply"_. The issue with the recursive definition of comment is now solved.

* [The updated Requirements document](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft))
* [Relevant revision](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)/0f6f32479f06af44c6ad095eb749a96b8f2c1b67)

**Comment by canatakan** [comment]
* As the task is now completed, it can be marked as _ready for review_ now.
* You can mark the issue as _completed_ and close it after giving your feedback if everything is okay @askabderon. Thanks in advance!

**Comment by askabderon** [comment]
I think we can rename "comments" field of DiscussionPost class to "commentsList" in order to be consistent with Event and ArtItem classes. Other than this, I agree with the changes of diagram and requirements.

**Comment by canatakan** [comment]
Renamed the relevant field and its getter method. You can find the updates in [this revision](https://github.com/bounswe/bounswe2022group7/wiki/Class-Diagram/6986be79a493bbf684f44f7a06224d437fdd65ca). Since this task is now completed, I am closing the issue.
