### ISSUE TITLE
Frontend Annotation Research

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#297]
Our project will need to include text and image annotation. We still don't have a clear idea of how these features will be. We need to do some research to find out what these concepts are. We should also find libraries we can use in our app. I will focus on frontend since I am in the frontend team.

Deadline 30.10.2022, 23.59
Reviewer: @erimerkin

**Comment by CahidArda** [comment]
I have found a tool for text annotation called [Annotator](http://annotatorjs.org/). 

![image](https://user-images.githubusercontent.com/57228345/198092291-6c2cc45d-f963-4943-81a9-f2bd9d8358a2.png)


## How can you try?

Their website is meant to showcase the annotation tool but the tool is not maintained since 2015 and the website is broken. One can go to [their github repository](https://github.com/openannotation/annotator/), download [the latest release zip](https://github.com/openannotation/annotator/releases/tag/v1.2.10) and click `index.html` file and use the annotation tool.

**Comment by CahidArda** [comment]
I have tried a few things and now I have a plan for configuring Annotator in our app to solve the problems I described above (authentication and integration with React).

I removed the `<script>` I had added to `index.html` to define and start Annotator app. Instead, I moved the code to [ArtItemPage.js](https://github.com/bounswe/bounswe2022group7/files/9876537/ArtItemPage.txt). Here is how I import and start the app:
```js
// ...
import annotator from "../../js/annotator"

function ArtItemPage() {
    
  var app = new annotator.App();
  app.include(annotator.ui.main, {element: document.body});
  app.start();
  // ...
```
The annotations work when they are imported this way. In order to save and load annotations, we will have to use [Annotator modules](http://docs.annotatorjs.org/en/latest/modules/index.html).

## Storage Module

We need to use the `annotator.storage.http` module for receiving annotations. We will provide the api address implementing the [Storage API of Annotator](http://docs.annotatorjs.org/en/latest/modules/storage.html#storage-api) and the token by adding the storage module like the following:
```js
app.include(annotator.storage.http, {
    prefix: 'http://example.com/api',
    headers: 'add token here'
});
```
See http module usage and module creation options in [Module Usage section](http://docs.annotatorjs.org/en/latest/modules/storage.html).

Storage API has endpoints for creating and deleting annotations. So annotations will probably work once we have all the endpoints up. Backend team has to handle these endpoints.

**Comment by CahidArda** [comment]
I have found tools for adding text and image annotation. I have also planned the steps we will take to add annotations to the frontend.

Ready for your review @erimerkin.

**Comment by CahidArda** [comment]
We will need several endpoints [as described in the Annotator](http://docs.annotatorjs.org/en/latest/modules/storage.html#storage-api) documentation for annotations.

fyi @demet47

**Comment by erimerkin** [comment]
Thanks for your research @CahidArda. According to your findings, I think we should revise our project plan as annotations are the focal point of our application. I suggest that we move the implementation of annotations to an earlier stage for ensuring the feature works properly without a problem. This task is now completed, we can close the issue.
