### ISSUE TITLE
Implementation of RegisteredUser Class

### ISSUE THREAD

**Issue by sabrimete** [bounswe/bounswe2022group7#299]
In order to move on with the Authentication task, Basak assigned to write classes below in relation to [UML Class Diagram](https://github.com/bounswe/bounswe2022group7/wiki/Class-Diagram)

- [x] RegisteredUser Class

**Deadline:** 27/10/2022 23.59
**Reviewer:** @sabrimete

**Comment by askabderon** [comment]
Because of the urgency of this class, I leave the unimplemented DiscussionPost relation classes as TODO and implemented the rest of it. Also, necessary fields are added to Event related classes.

**Comment by sabrimete** [comment]
I already merged the PR related with this issue.
