### ISSUE TITLE
Creating Personal Wiki Pages

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#3]
Every member of the group should create a personal wiki page. Each wiki page should include:
- Name
- A brief description
- Contacts (Must include a link to Github profile)

**Comment by guneyizol** [comment]
I think we should create seperate issues for wiki pages for each member so that they can close their issues when they created their pages.

**Comment by demet47** [comment]
Also I recommend the pages to be generic, at least as a starter.

**Comment by AlicanM** [comment]
All personal pages are created and ready to be filled.

**Comment by AlicanM** [comment]
- [ ] [Cahid Arda Öz](https://github.com/bounswe/bounswe2022group7/wiki/Cahid-Arda-%C3%96z)
- [ ] [Demet Yayla](https://github.com/bounswe/bounswe2022group7/wiki/Demet-Yayla--%F0%9F%90%AC-%F0%9F%90%9A-%E2%AD%90)
- [ ] [Ali Can Milani](https://github.com/bounswe/bounswe2022group7/wiki/Ali-Can-Milani)
- [ ] [Musa Şimşek](https://github.com/bounswe/bounswe2022group7/wiki/Musa-%C5%9Eim%C5%9Fek)
- [ ] [Erim Erkin Doğan](https://github.com/bounswe/bounswe2022group7/wiki/Erim-Erkin-Do%C4%9Fan)
- [ ] [Mehmet Emin İpekdal](https://github.com/bounswe/bounswe2022group7/wiki/Mehmet-Emin-%C4%B0pekdal)
- [ ] [Güney İzol](https://github.com/bounswe/bounswe2022group7/wiki/G%C3%BCney-%C4%B0zol)
- [ ] [Aziza Mankenova](https://github.com/bounswe/bounswe2022group7/wiki/Aziza-Mankenova)
- [ ] [Rafet Oğuz Pançuk](https://github.com/bounswe/bounswe2022group7/wiki/Rafet-O%C4%9Fuz-Pan%C3%A7uk)
- [ ] [Atilla Tüekmen](https://github.com/bounswe/bounswe2022group7/wiki/Atilla-T%C3%BCrkmen)
- [ ] [Can Atakan Uğur](https://github.com/bounswe/bounswe2022group7/wiki/Can-Atakan-U%C4%9Fur)

**Comment by CahidArda** [comment]
It was decided that every member will open their own issue when creating their own wiki page. Therefore closing this issue.
