### ISSUE TITLE
Implement Single Event Endpoint

### ISSUE THREAD

**Issue by askabderon** [bounswe/bounswe2022group7#301]
We need to implement an endpoint that returns a single event for the event detail page. @demet47 is assigned for this task.

**Deadline:** 28/10/2022 23.59
**Reviewer:** @askabderon

**Comment by demet47** [comment]
I finished the implementation. The endpoint to be used is as follows:

{domainURL}/event/{id}

I injected an instance of event with id 1 to the database, if yo want to test you can try that.
Also, if there is no event with the given id, it returns nothing but doesn't give HTTP error either.

**Comment by sabrimete** [comment]
Already merged the PR.

**Comment by askabderon** [comment]
LGTM
