### ISSUE TITLE
Fix: Remove wrong usage of cascade

### ISSUE THREAD

**Issue by askabderon** [bounswe/bounswe2022group7#309]
There is an error about ManyToMany associations of database, we need to deprecate all (cascade = [cascade.ALL]) usage in these associations and replace them with suitable cascade using. @demet47 is assigned to check this using and replace all occurrences.

**Reviewer:** @sabrimete 
**Deadline:** 29/10/2022 13.00

**Comment by demet47** [comment]
I solved this issue with another approach:
I maintained CascadeType.ALL because this in fact is the behaviour we really want to see. Instead, I used below combination of annotations:

**@ ManyToMany**(cascade = [CascadeType.ALL])
**@ JoinTable**(
    name = <name of the table to be formed to represent connection>,
    joinColumns = [JoinColumn(name = <name of the column we will see for each element of other side of the relation>)],
    inverseJoinColumns = [JoinColumn(<name of the column we will see for each element of this side of the relation>)]
)
