### ISSUE TITLE
Research on Inheritance and Hibernate Entegration

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#310]
We coincided with inheritence related problems while trying to do things below:
- Creating abstract classes
- Creating a list field of entity classes inside entities

We will learn about spring annotations and hibernate annotations related to this and brainstorm on how to represent classes in database tables that use inheritence.

**Comment by demet47** [comment]
Issue [here](https://github.com/bounswe/bounswe2022group7/issues/309) is strongly related to this issue. I want to reference it here.

**Comment by CahidArda** [comment]
Associated PRs are merged. Can we close this issue?

**Comment by demet47** [comment]
Hi @CahidArda !
The system seems to work but I am still not sure if the annotations from hibernate are correct. I am to research more on them since this research will mostly clear out our production of entity classes and we will automize writing them mostly without any erroneous behaviour.

**Comment by demet47** [comment]
For One-To-One mapping, research results:
- From [link](https://www.baeldung.com/jpa-joincolumn-vs-mappedby) I fixed one-to-one mapping to behave as such:
If the foreign key holder is deleted, the referenced entity is deleted. If the referenced entity is trying to get deleted, it is prevented from happening. This can be observed in the OneToOne relation between ArtItem - ArtItemInfo. Also here when the parent object is saved, its child object is saved automatically without needing explicit save before.

**Comment by demet47** [comment]
**Many-To-One & One-To-Many mapping:**
For the one formed between a commentable object - comment:
- a comment can be deleted without any problem. 
- when a commentable object is deleted, all comments pointing to it deleted.
- Implementaiton related details:
    - For a comment, we use **ManyToOne** annotation. Comment is the foreign key holder and this is implemented by using **JoinColumn** annotation for the field. It uses CascadeType.PERSIST because of transient object issues.
    - For a commentable object, we use **OneToMany** annotation. It uses CascadeType.ALL along with orphanRemoval = True because we want all comments to get removed when a commentable object is removed. To imply the owner side of relation, we use mappedBy also.

**Comment by demet47** [comment]
We already had a working version of ManyToMany relationship. So I am thus closing this issue by transferring the knowledge and implementation to [issue #382](https://github.com/bounswe/bounswe2022group7/issues/382). The review can be traced in bulk through entegration of the related branch for this issue and the branch corresponding to the issue I referred above.
