### ISSUE TITLE
Customize the Home Page for Guest Users

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#313]
- Current home page is made from the Registered User's point of view; however, now we would like it to be visible to Guest Users and provide some functionality according to our Requirements.

- For this task, some minor changes are required along with the task of updating the drawer. To update the drawer, I shall delete all the current sections in it and add Register and Login options only.

Since these changes will not affect any other file than `home_page.dart`, and all changes are expected to be minor updates, I will not create another branch and rather I will push my commit(s) to `android`.

**Deadline: 29/10/2022, 13:00**
**Reviewer: @atillaturkmen**

**Comment by canatakan** [comment]
* The drawer is updated and some minor changes are added. [The referencing commit](https://github.com/bounswe/bounswe2022group7/commit/47f0350c32db3e8c56a8e38009cb5e2e2e639b6c) has all the necessary implementations and therefore, this issue is now ready for review.

* You can simply close this issue after providing your feedback if everything is okay. If not, please request some changes.

**Comment by atillaturkmen** [comment]
Thank you for the work, it looks good. Therefore I am closing this issue.
