### ISSUE TITLE
Connecting the Register Form to the Backend

### ISSUE THREAD

**Issue by atillaturkmen** [bounswe/bounswe2022group7#318]
As discussed in the [Mobile Team Meeting 3](https://github.com/bounswe/bounswe2022group7/wiki/MOBILE-Meeting-Notes-%233), I was assigned to complete the register functionality by connecting to the back end register end point.

* Here are the tasks that will be done to complete this issue:
  - [x] Create input and output data transfer objects.
  - [x] Take all inputs in the register form and put it into the input object.
  - [x] Send input object to "/register" endpoint.
  - [x] Register or show an error message according to response.

**Deadline: 29/10/2022, 23:59**
**Reviewer: @canatakan**

**Comment by atillaturkmen** [comment]
I have implemented the back end connection of register functionality. Detailed information can be found in PR https://github.com/bounswe/bounswe2022group7/pull/320. Therefore, this issue can now be closed after being reviewed by @canatakan.

**Comment by CahidArda** [comment]
Can you provide the latest format of the sign-up form in the mobile? @atillaturkmen

**Comment by atillaturkmen** [comment]
> Can you provide the latest format of the sign-up form in the mobile? @atillaturkmen

Of course, you can find screenshots from the latest version of the register form below:

![image](https://user-images.githubusercontent.com/59166549/198845321-e0119536-8aec-4636-8f0e-218a21ee172d.png)

![image](https://user-images.githubusercontent.com/59166549/198845323-48228aaa-55b2-4a0b-b432-b9d7e1c34206.png)

![image](https://user-images.githubusercontent.com/59166549/198845326-730060f1-2fc2-4894-b67a-d87f133f4195.png)

**Comment by atillaturkmen** [comment]
The PR https://github.com/bounswe/bounswe2022group7/pull/320 is merged. I am closing the issue.
