### ISSUE TITLE
Implement Event page with endpoint integrations

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#330]
As discussed in the [Mobile Team Meeting 3](https://github.com/bounswe/bounswe2022group7/wiki/MOBILE-Meeting-Notes-%233), I was assigned to prepare the Event page and complete the integration of those with the relevant endpoints. 

* Since our documentation is not ready yet, the Back-end Team has created a Wiki page containing the endpoints that are ready to be integrated. See: [Endpoint Table for Backend Requests](https://github.com/bounswe/bounswe2022group7/wiki/Endpoints).

* Some sub-tasks of this issue are as follows:
  - [x] Branch out from the `develop` branch
  - [x] Connect the route from the homepage to the Event page
  - [x] Design the Event page UI
  - [x] Integrate the Event related endpoint: `event/{id}`
  - [x] Create a pull request to merge the new branch `dev/android/event-page` into `develop`

**Deadline: 29/10/2022, 23:59**
**Reviewer: @musasimsekdotdll**

**Comment by canatakan** [comment]
* The newly created branch named `dev/android/event-page` is created from the `develop` branch.
* The commit https://github.com/bounswe/bounswe2022group7/commit/e15a6d1c73685f8d40c28d1edb082d5d28f821b1 includes the creation of this branch and the fundamental route updates.

**Comment by canatakan** [comment]
After commit https://github.com/bounswe/bounswe2022group7/commit/740d615c65846b00f4fef52b68abeabfa3fe3896, every event in the homepage now points to its relevant page.

**Comment by canatakan** [comment]
With the commit https://github.com/bounswe/bounswe2022group7/commit/a48c24e6d8bd1d516196797ab94b929260ff4f01, basic UI for the event page is completed. You can see an example screenshot from the page:

<img width="263" alt="Screen Shot 2022-10-30 at 01 33 35" src="https://user-images.githubusercontent.com/56476673/198854909-d927f748-81a0-448e-9c52-69352b24970f.png">

**Comment by canatakan** [comment]
After the commit https://github.com/bounswe/bounswe2022group7/commit/b8d5f707c946a41cc4c2edc30c2aef7fe253a8c0, the Event Page UI is completed for now. The design looks as below:

<img width="259" alt="Screen Shot 2022-10-30 at 02 45 18" src="https://user-images.githubusercontent.com/56476673/198856524-529f1d58-80ca-47d3-889a-6a0ae015ae6f.png">

**Comment by canatakan** [comment]
I made many commits in order to be consistent with the back-end team with our models. These pieces of implementations were actual implementations of the relevant comprehensive classes. You can see some of these commits below:

- 8aba013540f1b2aaa09bba16bc6d15064c376ae8
- e3c25f8bba9c445f30a6ee67a71090bf30cbe531
- 700aff447be4b5fffbcf002de51618ca9bb4e1f8
- 172765b25e42fbbf303d90c3abf2e27a7f9d00cb 
- 19153a33050317532e706545807788d5cec499ee
- 546461c241ae01ce8d301d44ab1b96051296e505
- f2621d12bf16f839ee9569f546b3adc7db509ad4
- fcb8b2ee79500aa342626f850c02d76e861268a2

These class designs were made according to the feedback we got from the back-end team. Although this task is almost completed, there are many points to discuss between both teams. Therefore, I will create a separate issue to discuss about the consistency between us and address all of the points that are not clear.

**Comment by canatakan** [comment]
* The endpoint integration has just been completed. 
* The events are fetched with their `id` by sending a `GET` request to `event/{id}`.
* Thus, the `EventPage()` constructor now does not get an `Event` object as parameter. It only takes its `id` to show the event's page.

**Comment by canatakan** [comment]
Before sending a pull request, here are a couple of points that can be improved in the UI:
- [ ] Show collaborators list next to the _"Collaborators"_ section
- [ ] Take care of the image size so that RenderFlex overflow will not happen

After these updates, the pull request will be created.

**Comment by canatakan** [comment]
- The pull request is now opened and marked as ready for review. This issue is also linked to it.
- Please check #348 and provide your feedback @musasimsekdotdll.
- After your review in the pull request, the issue might be closed, thank you.

**Comment by musasimsekdotdll** [comment]
UI seems as fine as the implementation, thank you for your great work! I am closing this issue.
