### ISSUE TITLE
Fetch home page data and show them in the browser

### ISSUE THREAD

**Issue by guneyizol** [bounswe/bounswe2022group7#332]
The endpoints required by the home page are done. We need to fetch those data and show them to the users in the browser. In order to do that, we need to make api calls to the backend server from the frontend. But first, a jwt needs to be acquired by singing up / logging in. After a jwt is acquired, it can be used to fetch further data.

**Comment by guneyizol** [comment]
While in development, we discovered that parcel doesn't solve our problems in a clean way. Specifically, running a proxy in development environment is not as straightforward as it is with webpack. We switched to Create-React-App which uses webpack.

**Comment by CahidArda** [comment]
This task was handled with #337. Closing the issue.
