### ISSUE TITLE
[Mobile] Test Mobile Application Functionality

### ISSUE THREAD

**Issue by atillaturkmen** [bounswe/bounswe2022group7#334]
I will test to see if the mobile application can connect to back end sucessfully. 
Here are the tasks that I will do to complete this issue:

- [x] Download Docker Desktop and Postman
- [x] Build the docker containers from develop branch.
- [x] Connect the flutter app running in emulator to localhost by changing the API endpoint URL in config file.
- [x] Test network functions of the mobile application.

I will put the results of the tests in this issue after they are complete.

Reviewer: @musasimsekdotdll 
Deadline: 31/10/2022 23:59

**Comment by atillaturkmen** [comment]
I have run the docker containers and connected the emulator to the localhost. Then I have tested the signup functionality. Signup works as intended. Here is a screenshot after a successful signup. (User is redirected to the login page after a successful signup operation): 

![Screenshot (105)](https://user-images.githubusercontent.com/59166549/198873012-4c9af261-7f7b-4d63-8438-f281f4e2ccdd.png)

**Comment by atillaturkmen** [comment]
I will close this issue after all functionality for milestone 1 are implemented and tested.

**Comment by canatakan** [comment]
> I will close this issue after all functionality for milestone 1 are implemented and tested.

Checking the functionality of the Event Page might be one of the next objectives here. The implementation of this task has just been completed and it is pending review in #348. 

Maybe we can check it at our team's earliest convenience.

**Comment by atillaturkmen** [comment]
I have tested the scenerio and it seems that everything works as intended. I did not encounter any errors. Therefore I am closing this issue.
