### ISSUE TITLE
[Frontend] Revise and connect signup and login to backend

### ISSUE THREAD

**Issue by erimerkin** [bounswe/bounswe2022group7#338]
As we have previously implemented the login and signup pages without a backend connection, we need to set up the backend connection. Also we need to achieve feature parity with mobile application, as we don't have some fields they have on their signup page. So I will implement these changes.

**Deadline: 31.10.2021**
**Reviewer: @CahidArda**

**Comment by erimerkin** [comment]
I will make the necessary changes in `fetch-homepage` branch since auth changes are needed for homepage to work. The login page connection and a few visual updates on the page is done. Now I will work on Sign Up page.

## Login Page changes:

- Page now displays an error message if there was a problem logging in:

<img width="862" alt="resim" src="https://user-images.githubusercontent.com/26660856/198881047-1cf9c306-7f14-49c3-aba2-9c6090ad3d28.png">

- Loading button is added to show response for the user:

<img width="862" alt="resim" src="https://user-images.githubusercontent.com/26660856/198881490-ad6da657-5ffa-472a-a6cb-c0484941ed8c.png">

**Comment by erimerkin** [comment]
For sign-up page, I will create a new branch and work from here. The necessary changes are:

- Adding following fields: Age, Country, Username
- Connecting to backend
- Implement form validation

**Comment by erimerkin** [comment]
While researching for popular validation methods in React, I found [this package with necessary example ](https://formik.org/docs/examples/with-material-ui)on Material UI. So I will use this package and modify the example to handle validation.

**Comment by erimerkin** [comment]
I have now finished the signup and login pages. Now after sign up is completed succesfully user is redirected to login page with email field automatically filled.


## Sign Up Form
**Added validation to sign up form:**

- Empty fields for required texts:
<img width="1671" alt="resim" src="https://user-images.githubusercontent.com/26660856/198894447-60191611-1ede-4e4f-9999-1a72a75297bf.png">

- Email validation:
<img width="1671" alt="resim" src="https://user-images.githubusercontent.com/26660856/198894602-e8635dd3-ee35-41d0-b673-0a1660f05c31.png">


- Age validation
<img width="1671" alt="resim" src="https://user-images.githubusercontent.com/26660856/198894563-f5510bfc-e3fd-41cc-8b48-06bcc90c001a.png">

- Username validation (empty spaces etc.)
<img width="1671" alt="resim" src="https://user-images.githubusercontent.com/26660856/198894498-2ca6623c-9e6e-4426-acdd-0c829ac68ba1.png">


## Login Form

- Login page redirection after successful signup:
<img width="1671" alt="resim" src="https://user-images.githubusercontent.com/26660856/198894631-fd4c4f5d-19c0-49f3-8451-12fcc24fbfab.png">

**Login Form Validations:**

- Email:
<img width="1671" alt="resim" src="https://user-images.githubusercontent.com/26660856/198894654-a71f32e8-efbc-4e81-8b6b-1f16f100ccef.png">

- Password:
<img width="1671" alt="resim" src="https://user-images.githubusercontent.com/26660856/198894668-39779242-e3a7-4399-a818-05041e2d0db4.png">
 

----

This issue is now ready for your review @CahidArda.

**Comment by CahidArda** [comment]
Associated PR is merged. Closing the issue.
