### ISSUE TITLE
Integrate the Art Item related endpoint: `art_item/{id}`

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#339]
In the scope of the implementation of the Art Item page, the integration of the related endpoint and the design of the UI are now two distinct tasks. The latter has now been assigned to Atilla.

For the details of the task, please see #331.

**Deadline: 30/10/2022, 23:59**
**Reviewer: @canatakan**

**Comment by atillaturkmen** [comment]
I have implemented the connection of art item endpoint. You can find the relevant work in this commit: be3345b6b6148bd7e4e34d6115d774c7902d5d73

Please review the code. After the review this issue can be closed.

**Comment by canatakan** [comment]
We are working in the same branch, and I reviewed your code. Now I need to keep working on the UI. Thank you for your work, closing the issue.
