### ISSUE TITLE
[Backend] Recursion Problem in Art Items

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#344]
I am having issues when I try to access endpoints with art item information. There is no response to my requests and the cnosole runnign the docker shows the following few lines repeating:
```
artshare-backend   |    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178) ~[jackson-databind-2.13.4.jar:2.13.4]
artshare-backend   |    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728) ~[jackson-databind-2.13.4.jar:
artshare-backend   |    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774) ~[jackson-databind-2.13.4.j
artshare-backend   |    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178) ~[jackson-databind-2.13.4.jar:2.13.4]
artshare-backend   |    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728) ~[jackson-databind-2.13.4.jar:
```

I was also able to catch the following logs:
```
>com.group7.artshare.entity.RegisteredUser["accountInfo"]->com.group7.artshare.entity.AccountInfo["registeredUser"]->com.group7.artshare.entity.RegisteredUser["accountInfo"]->com.group7.artshare.entity.AccountInfo["registeredUser"]->com.group7.artshare.entity.RegisteredUser["accountInfo"]->com.group7.artshare.entity.AccountInfo["registeredUser"]-
```

It looks like there is a recursion in the database. I tried to find where this started occuring and here is how I think it happened:
- This wasn't a problem until [this commit adding creator information to art items](https://github.com/bounswe/bounswe2022group7/commit/a3b3432feee18c9b0c0c4bc262cd35baab4e273e#diff-6a010c15d09e93e1494814fe10c56f3d5ead9fa84a3d285fa316087f3aec79bd). The commit doesn't add creator information to events so this problem doesn't occur in events.
- After this commit, the creator field of the art item changes. Past version can be seen [here](https://github.com/bounswe/bounswe2022group7/issues/287#issuecomment-1294019147). After the change it looks like [this](https://github.com/bounswe/bounswe2022group7/pull/342#issuecomment-1296272023). There are new fields: name and surname. **Notice that they are null in the image in the PR**. 
- Then I created art items through the create art item end point. After this, I couldn't use the art item endpoints anymore.

I don't know much about how things work in the backend but I think it may be related to this:

![image](https://user-images.githubusercontent.com/57228345/198889099-def5d6a0-de25-4e47-9a67-d96a849dc2ee.png)

## How to Replicate

- Run `docker-compose up`
- Create art items with the endpoint
- Try to get art items with: `http://localhost:8080/homepage/getArtItemsForUser`

If it doesn't work with the steps above, you can try to do the following first:
- Delete existing containers
- Delete database volume

Deadline 31.10.2022, 12:00
Reviewer: @sabrimete

**Comment by demet47** [comment]
I think the problem will be solved removing the "CascadeType.ALL" from OneToOne annotation in AccountInfo class registeredUser field. [The official website](https://www.baeldung.com/jpa-one-to-one) has a similar implementation.

**Comment by askabderon** [comment]
This bug is related with the [issue] (https://github.com/bounswe/bounswe2022group7/issues/323). I created the [pull request](https://github.com/bounswe/bounswe2022group7/pull/345) corresponding to these issues. Please review them @CahidArda to ensure it resolves this bug.

**Comment by CahidArda** [comment]
Problem was handled in #345. Closing the issue. Thanks for the work.
