### ISSUE TITLE
Demands from Frontend to Backend

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#347]
There are some requested changes from frontend on the datas we will provide in demo. They are as below:
- [x] Add creation dates to sample events.
- [x] Owner is missing for a sample art item.
- [x] Author is missing for a comment.
- [x] current version for labels field in json is written as follows : "{ "label1", "label2"}". It should be converted to the following: "[ "label1", "label2"]"

**Reviewer:** @canatakan 
**Deadline**: 31/10/2022 12.00

**Comment by demet47** [comment]
An event doesn't have a field like "creationDate" @canatakan ? It has lastEdited date, startingDate and endingDate. And I think this way is logical. Is there a special reason or use case that requires this requested modification?

**Comment by canatakan** [comment]
- Yes, keeping timestamps of the objects created in the platform is fundamental in my opinion.
- Also, there may be some cases such that we will need to sort events according to their creation time. "Most recently posted events" seems like a very reasonable ordering to me.

**Comment by canatakan** [comment]
Also, could you please update the second event, too? Most of its fields are `null` and it does not have an `eventInfo`.

**Comment by guneyizol** [comment]
Could you prepend the endpoint names with the string '/api/'? This will make the configuration of the production and development environments much easier.

**Comment by erimerkin** [comment]
> Could you prepend the endpoint names with the string '/api/'? This will make the configuration of the production and development environments much easier.

I have updated the backend with this change in #355

**Comment by canatakan** [comment]
The back-end changes were sufficient for the Milestone. There are still lots of work to do for the further development and we can discuss those in the next meeting that we decide our next tasks for each sub-group.

Since the task is completed, I am closing the issue.
