### ISSUE TITLE
Updating the App Name

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#350]
We had decided to name the app ideart in [our last meeting](https://github.com/bounswe/bounswe2022group7/wiki/CMPE451-Meeting-Notes-%234).

The mobile and frontend should be updated with the new name.

Deadline: 31.10.2022, 23:59
Reviewer: @atillaturkmen

**Comment by CahidArda** [comment]
I have created a branch and updated the app name. Here is how it currently looks in the front end:

![image](https://user-images.githubusercontent.com/57228345/198936895-8910e624-fc41-437e-854e-872fe088e806.png)

I have also updated the navigation bar to better match the [items in the mobile](https://github.com/bounswe/bounswe2022group7/pull/328).

**Comment by canatakan** [comment]
Hello @CahidArda, 

* Could you please provide some details as to the font used in the name? 
* Are we planning to use this logo? If that is the case, could you please also share that with us?

**Comment by CahidArda** [comment]
The font is monospace font. I don't know if you can use them in mobile but other relevant arguments we used are these:
```
fontFamily: 'monospace',
fontWeight: 700,
letterSpacing: '.2rem',
```

The logo is not a must but if you want to include it, you can find it [here as SVG](https://materialui.co/icon/adb).

**Comment by canatakan** [comment]
The pull request #352 is now open and it is ready for your review @atillaturkmen. Please also update the state of this issue after your review. 

Thank you in advance!

**Comment by atillaturkmen** [comment]
I have reviewed and merged the relevant pull request https://github.com/bounswe/bounswe2022group7/pull/352. Therefore, I am closing this issue.
