### ISSUE TITLE
Adding Event Page to frontend

### ISSUE THREAD

**Issue by ENESAYDOGDUOGLU** [bounswe/bounswe2022group7#356]
The Event Page needs to be added to the front-end. For the first milestone, this page will be visual only, but will be functional in the future. 

Event page should satisfy the [requirements](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)#115-events).

**Comment by erimerkin** [comment]
The necessary additions were done in PR #367, which is now succesfully merged with `develop` branch. So this issue is now completed.
