### ISSUE TITLE
[Mobile] Put Server IP Address in .env file

### ISSUE THREAD

**Issue by atillaturkmen** [bounswe/bounswe2022group7#357]
For now the mobile application requests data from localhost. I will create an ".env" file and put server configuration such as IP and port address into that file.

Here are the tasks to complete this issue:
- [x] Find and add a dependency for adding environment variables to flutter applications.
- [x] Create a .env file and put server configuration inside the file.
- [x] Change the code in main and config files accordingly.

Reviewer: @canatakan 
Deadline: 31/10/2022 23:59

**Comment by atillaturkmen** [comment]
@canatakan 

I have added an env library, integrated it with the app and created a template.env file to show the expected fields in the .env file. If fields in the env file are empty, ip and port number defaults to localhost 8080.

Please review the code. This issue can be closed after the review.

**Comment by canatakan** [comment]
Thank you for your contribution. I have already approved and merged your pull request. Closing the issue.
