### ISSUE TITLE
Research on Integration Testing

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#358]
I am working on how to implement integration test with spring and java. I mostly searched Mvc. I will provide a map of my research journey on this issue.

**Comment by sabrimete** [comment]
Thanks for sharing, I'll look into that.

**Comment by askabderon** [comment]
Thanks for working on this @demet47 I also found a link related to that https://medium.com/backyard-programmers/kotlin-spring-boot-unit-testing-integration-testing-with-junit5-and-mockk-a2977bbe5711 we can look into this also.

**Comment by sabrimete** [comment]
This one can be useful as well: https://www.baeldung.com/spring-boot-testing

**Comment by demet47** [comment]
Bazı kod parçaları yazdım. dev/integration-test branchinde varlar.

- [Video link](https://www.youtube.com/watch?v=mrhhOqx4uzA) for setting up maven and Junit for integration testing.
- [Video link](https://www.youtube.com/watch?v=Geq60OVyBPg) good for intro to methods of junit etc. (!!MY STAR VIDEO YET!!)
- [Video link](https://www.youtube.com/watch?v=pNiRNRgi5Ws) for mocking controllers
- In RestAPIs, exceptions may be thrown. To cover them, [here](https://stackoverflow.com/questions/2496525/is-it-against-best-practice-to-throw-exception-on-most-junit-tests) is a good discussion
- For using our albert-test db instead of an in-memory db, we can look [here](https://www.baeldung.com/spring-boot-testcontainers-integration-test).
    - Specifically, 3.1 is a good implementation option.
    - If we want to create a test-db container and use it throughout the test folder (singleton db container), 4 is useful here.
- [Discusses](https://sendgrid.com/blog/when-writing-unit-tests-dont-use-mocks/) why we should use fakes instead of mocks in tests
    - **highlight 1:** “The major benefit of fakes are that they decrease coupling in code, where mocks increase coupling, and coupling makes refactoring harder.”
- Am looking for a way to mimic some internal method call embedded inside the method I am calling for testing.
I want it not to get executed, but want to set a certain value for its return type instead when needed (In this case, it isn’t needed since the method is void. But there could be a case in which the flow of the method required this call to return some value.) 

- Almost exactly what I was looking for: [https://www.baeldung.com/integration-testing-in-spring](https://www.baeldung.com/integration-testing-in-spring)
- **A link to understand the securityFilterChain for spring security: [https://medium.com/geekculture/spring-security-authentication-process-authentication-flow-behind-the-scenes-d56da63f04fa](https://medium.com/geekculture/spring-security-authentication-process-authentication-flow-behind-the-scenes-d56da63f04fa)**
    - Terminologies in this link:

        - authentication filter in a filter chain catches an attempt and directs it to the auth manager
        - Authentication interface implementation specifies the type of auth.
             e.g. UsernamePasswordAuthenticationToken is an implementation which we will utilize
        - Authentication Manager to call authenticate() to the correct AuthenticationProvider. Decision is made by calling supports() method to see if auth type fits.
        - Authentication Provider interface implementation is for processing certain type of authentication.

**Comment by demet47** [comment]
https://spring.io/guides/tutorials/spring-boot-kotlin/

**Comment by demet47** [comment]
I tried different versions of mocking an API endpoint call. I failed with errors that google lacks answers to.
For one of my trials, I had an error that I opened a stackoverflow question about. You can reach the post from [here](https://stackoverflow.com/questions/74511835/the-specified-key-byte-array-is-192-bits-which-is-not-secure-enough-for-any-jwt)

I tried another approach using different dependencies from the link [here](https://www.baeldung.com/kotlin/spring-boot-testing) again had wrong assertion error.

Now I am investigating what old years' groups followed as an approach. I found one repo worth trying but I frankly couldn't find any example of direct endpoint call with mockmvc and assertions on the call.
