### ISSUE TITLE
[Mobile] Add Widget Test for Register Page

### ISSUE THREAD

**Issue by atillaturkmen** [bounswe/bounswe2022group7#359]
I will add widget tests for register page that tests UI of the page. 

For this task I should research how to build scaffold widgets without material app widgets. Beacuse our pages contain Scaffold widgets and these widgets require Material App widgets as parents.

After I solve this issue and write tests, I will open a PR and add @musasimsekdotdll as the reviewer.

Reviewer: @canatakan 
Deadline: 22:00 31/10/2022

**Comment by atillaturkmen** [comment]
@musasimsekdotdll 

I have implemented widget tests that tests the UI of the register page. To achieve this, I created a helper function that wraps given widgets with Material Apps and necessary providers.

Please review the code. This issue can be closed after the review.

**Comment by canatakan** [comment]
* I reviewed #360 and your tests were clear and correct.
* Since the review is done and your tests are passed, now we can close the issue.
