### ISSUE TITLE
Updating the readme screenShoot

### ISSUE THREAD

**Issue by HasanBingolbali** [bounswe/bounswe2022group7#36]
Hasan Bingolbali is absent in our readme ss

**Comment by canatakan** [comment]
We can take a new picture in our next meeting, and easily update our group photo afterwards.

Happy to have you in our team, welcome @HasanBingolbali! :)

**Comment by canatakan** [comment]
I will add this to the next meeting's agenda and we will take the action accordingly. Closing the issue as it remained open for a long time and there is no need for a comprehensive description or reporting for this task.
