### ISSUE TITLE
Add tests for the Event Page

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#361]
To finalize the implementation of the Event Page, I should add tests.

- [x] Add unit tests
- [x] Add widget tests for the UI

For unit tests, I can test the `string_helpers.dart` file.
For widget tests, I will test the user interface of the Event Page.

**Reviewer: @atillaturkmen** 
**Deadline: 31/10/2022, 23:00**

**Comment by canatakan** [comment]
I added unit tests for the `string_helpers.dart` file in commit 4cfc127248b1056ec7b7799e7c7af686979ec489. The results of these unit tests can be seen below:

<img width="1386" alt="Screen Shot 2022-10-31 at 21 16 06" src="https://user-images.githubusercontent.com/56476673/199080447-d1932dc8-5c24-45b5-9b61-0a549ce32926.png">

**Comment by canatakan** [comment]
Widget tests are now also completed. To test the `EventPage()` widget:
- I mocked the API call to the `event/<event_id>` endpoint;
- I mocked the calls made by the network images in the code.

I used two extra dependencies for this task which are [`nock`](https://pub.dev/packages/nock) and [`network_image_mock`](https://pub.dev/packages/network_image_mock).

**Comment by canatakan** [comment]
Here are the results for the widget test:

<img width="1378" alt="Screen Shot 2022-10-31 at 22 24 25" src="https://user-images.githubusercontent.com/56476673/199092592-dd4845e0-f474-4cee-8ea6-eeadd2532c04.png">

**Comment by canatakan** [comment]
The work is completed and now is ready for review. Please review the relevant pull request that issue is connected to and handle the issue accordingly @atillaturkmen. 

Thanks in advance!

**Comment by atillaturkmen** [comment]
Thank you for the work. I don't see any issue in the code. I will merge the PR and close this issue.
