### ISSUE TITLE
Preparing Part 1 of Customer Milestone-1 Group Review

### ISSUE THREAD

**Issue by askabderon** [bounswe/bounswe2022group7#374]
Part 1 of this Group Review, summary of the project and planned changements of it, is going to done by me.

Deadline: 04/11/2022 19.30
Reviewer: @musasimsekdotdll

**Comment by askabderon** [comment]
I prepared this text:

Ideart. is an art platform where the users can create or visit online galleries and physical exhibitions. It also allows artists to publish their art works, copyright them, and sell them to the art-lovers. Discussion page that users can share their thoughts are also provided.
Our application works on web and mobile both. It is on developing process right now. It supports registration related features such as sign up and log in functions, home page view is partly developed which provides the events and art items information by using the data on our database. Finally, when an event or art item is clicked, the corresponding information page of it is also shown.

Here are the topics that we discussed and decided to change after Customer Milestone 1:

During the sign up process, optional fields would be deprecated from the page in order to make this process be looked more simple. These optional fields are going to be added to the profile page which is available for the user’s usage when they want to provide more information about themselves.
We were taking age as a personal field, we are going to change it with birthday in order to reduce any update about it and be more consistent.
Discussion about the time zones that are shown for events: We decided to check whether local time of the user is different than event location time:
If they are the same, one time zone shall be shown. If they differ from each other, we shall show both of these time.
The location of the events are going to be updated to Geolocation from bare country.

@musasimsekdotdll can you review it and let me know about any required changes?

**Comment by musasimsekdotdll** [comment]
Everything seems fine, thank you for your effort. I am closing this issue.
