### ISSUE TITLE
Write an Evaluation of Tools and Processes Used in Mobile Application

### ISSUE THREAD

**Issue by atillaturkmen** [bounswe/bounswe2022group7#375]
I will write and explain tools we used in the mobile application of our team project. After the review by @musasimsekdotdll, I will add it into section 4 of our our group report.

Deadline: 04/11/2022 19.30
Reviewer: @musasimsekdotdll

**Comment by atillaturkmen** [comment]
@musasimsekdotdll 

I have written the evaluation. You can find it below. Please review it and provide your feedback. Thanks in advance.

## Flutter

We have used Flutter framework for developing our mobile application. Dart language is used for developing Flutter apps and Dart is very similar to Java. Since we all used Java in our school courses, getting used to Dart was fairly easy. The reason we chose Flutter over Kotlin is because Flutter provides easier and faster development with many libraries. Also Flutter has a hot reload feature which allows observing changes in code without rebuilding the app. This feature allowed us to develop faster than native Kotlin development. All in all, we were satisfied with our Flutter experience due to the reasons explained above.

**Comment by musasimsekdotdll** [comment]
Flutter evaluation seems nice and I cannot think of any additional tool/process to add. I am closing this issue, thank you for your effort.
