### ISSUE TITLE
Remaining Classes Implementation

### ISSUE THREAD

**Issue by askabderon** [bounswe/bounswe2022group7#382]
In order to fully structure backend, we should implement the remaining classes from our [class diagram](https://github.com/bounswe/bounswe2022group7/wiki/Class-Diagram). 
I was assigned the write the classes below:

- [x] Auction
- [x] AuctionInfo
- [x] Bid
- [x] Notification
- [x] Recommendation
- [x] Comment
- [x] Report
- [x] DiscussionPost
- [x] Artist
- [ ] InfringementCase
- [ ] CopyrightService

I should also update the existing classes TODO parts because of lack of these classes.
Deadline: 15/11/2022 23.59
Reviewer: @sabrimete

**Comment by askabderon** [comment]
In order to make the review process faster, I am going to split this work into three; 

- First part will include "auction", "AuctionInfo", "Bid", "Notification", "Recommendation"
- Second part will include "Comment", "Report", "DiscussionPost" 
- Final part will include "InfringementCase", "CopyrightService"

**Comment by askabderon** [comment]
We decided to deprecate the latest two classes on the latest team meeting. Our platform has a default copyrighted service which deprecates the copyright service class. And admin can control the flow by looking into the Report class. Hence, I think we can close the issue @sabrimete

**Comment by sabrimete** [comment]
Yes, you are right. Closing the issue since other classes are already merged.
