### ISSUE TITLE
Editing the Json Response

### ISSUE THREAD

**Issue by askabderon** [bounswe/bounswe2022group7#388]
During [the PR](https://github.com/bounswe/bounswe2022group7/pull/386) about Artist class implementation, [one comment](https://github.com/bounswe/bounswe2022group7/pull/386#issuecomment-1306725744) indicates the errors about Json Response.

We were directly returning the art item with corresponding id. However, we should be able to edit the Json object now. In order to achieve this I (@askabderon) am going to research some RestController examples in Kotlin and decide which is the best way to do it. 
At final, I am going to edit the endpoints to work as expected:
1. Endpoints should not contain user credentials.
2. Duplicate fields in the response should be deprecated.

Deadline: 12/11/2022, 23:59
Reviewer: @demet47

**Comment by demet47** [comment]
Yes, PR seems already a lot self-explanatory. Changes work well on my local too. Thus I am closing the issue.
