### ISSUE TITLE
Implementation of Event Creation Page UI

### ISSUE THREAD

**Issue by AlicanM** [bounswe/bounswe2022group7#397]
I was assigned to implement the Event Creation Page UI.

These are the tasks to complete this issue:
- [x] Branch out from the develop branch
- [x] Create the UI of a page for creating an event
- [x] Manage the navigations to that page
- [x] Create a PR 

Reviewer:  @atillaturkmen

**Comment by AlicanM** [comment]
- Implemented the event creation page UI with a form widget
![image](https://user-images.githubusercontent.com/47609112/201666022-151bb2d4-3624-4a3b-afd2-0fe0469921a5.png)

- Used the Date Range Picker for events starting and ending dates
![image](https://user-images.githubusercontent.com/47609112/201667149-e8fea44e-18d5-48ce-9f02-2786d9fb536e.png)

- Implemented validators as below
![image](https://user-images.githubusercontent.com/47609112/201667470-aa6a2faf-133e-4d60-bfb8-9b9accba07e8.png)

- [relevant commit](https://github.com/bounswe/bounswe2022group7/commit/8e5f58046e7e56a851b900036a234725bdb9b0de)

**Comment by AlicanM** [comment]
Now create event ui takes an image instead of a url ([relevant commit](https://github.com/bounswe/bounswe2022group7/commit/ee5b2cedcc0789d1b0ebe545611d6a5dc9d72cf1))
![Ekran görüntüsü 2022-11-19 155038](https://user-images.githubusercontent.com/47609112/202851915-2c5beb66-8c7b-4da6-8983-2424b7f43055.png)
![Ekran görüntüsü 2022-11-19 153148](https://user-images.githubusercontent.com/47609112/202851916-51696881-7d3c-49f1-b6fd-2ec63d97d5a7.png)

Navigation to create event page are also done.

**Comment by AlicanM** [comment]
[PR](https://github.com/bounswe/bounswe2022group7/pull/430) is created. Waiting for a review. @atillaturkmen

**Comment by atillaturkmen** [comment]
I have reviewed and merged the PR.
