### ISSUE TITLE
Implementation of Event Creation Page Network Calls

### ISSUE THREAD

**Issue by AlicanM** [bounswe/bounswe2022group7#398]
I was assigned to implement the Event Creation Page Network Calls.

These are the tasks to complete this issue:
- [x] Branch out from the develop branch
- [x] Send the data of a new event to the backend
- [x] Redirect to the newly created event page
- [x] Create a PR 

Due Date: 21/11/2022, 23:59
Reviewer: @musasimsekdotdll

**Comment by AlicanM** [comment]
[dev/android/create-event-network](https://github.com/bounswe/bounswe2022group7/tree/dev/android/create-event-network) branch is created.

**Comment by AlicanM** [comment]
[commit](https://github.com/bounswe/bounswe2022group7/commit/c148c342ae2c077be45009aa5fffa032830f83cf)
- Input and Output classes are implemented
- Input Fields are connected to those classes
- Post method service is implemented


Since the post method on the backend are not done yet, the input and output classes most likely going to change.

**Comment by AlicanM** [comment]
[commit](https://github.com/bounswe/bounswe2022group7/commit/77cbddedc55191d6d001933ff29efb6ea5d545ed)
Navigation to the newly created event page is handled, with an assumption that backend will return the event id. So this part may change also.

**Comment by AlicanM** [comment]
network connection for posts image are implemented [commit](https://github.com/bounswe/bounswe2022group7/commit/472362e4ee13f52c9a6f0eb0f7d395f89ad8e416)
online and physical event post methods now have correct models and their network connections are completed. [commit](https://github.com/bounswe/bounswe2022group7/commit/f1e825cfe8f4be2b2c0d02ce4c843c3f76fce809)

I created [PR](https://github.com/bounswe/bounswe2022group7/pull/465), waiting for the rewiew. @musasimsekdotdll

**Comment by AlicanM** [comment]
I add the auth token to the post methods headers  as requested in PR. [commit](https://github.com/bounswe/bounswe2022group7/commit/3db70fb409308ff75d89f80dd32d01939e842858)

**Comment by musasimsekdotdll** [comment]
The pull request is merged now, we can close this issue.
