### ISSUE TITLE
Setup Swagger for endpoint documentation

### ISSUE THREAD

**Issue by erimerkin** [bounswe/bounswe2022group7#399]
In our [group meeting in 8.11.2022](https://github.com/bounswe/bounswe2022group7/wiki/CMPE451-Meeting-Notes-%235), frontend and mobile teams complained about not having access to extended documentation for endpoints. I will try to implement a swagger/OpenAPI documentation for the api, so that documentation can be easily obtained by these teams in their development states.

**Deadline: 23.59, 14.11.2022**
**Reviewer: @askabderon**

**Comment by askabderon** [comment]
Closing the issue since the corresponding PR is merged. Thanks for working on this and making our life much easier with the swagger!
