### ISSUE TITLE
Preparing a Communication Plan

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#4]
A communication plan that shows how we will use different platforms needs to be prepared. It should include the following sections for each platform:
- Who will participate
- Where (i.e. department, Doydos, skype, slack, ...)
- Purpose (i.e. progress update)
- When (i.e. Mondays at 5)

**Comment by demet47** [comment]
A plan is created. As the teams are formed and subgroups' communication is necessary, slack channel specialization will be provided for better unbloated communication which will be easier to track.

**Comment by canatakan** [comment]
The communication plan can be found [here](https://github.com/bounswe/bounswe2022group7/wiki/Communication-Plan) and the details can be discussed during our first meeting.
