### ISSUE TITLE
Frontend of profile page

### ISSUE THREAD

**Issue by guneyizol** [bounswe/bounswe2022group7#400]
The profile page of the website needs to be designed and implemented according to the use cases and mockups.

**Comment by guneyizol** [comment]
I implemented the basic structure of the profile page and pushed the changes. @ENESAYDOGDUOGLU will take over the implementation while I research and start to implement the annotation features.

**Comment by ENESAYDOGDUOGLU** [comment]
I have completed the profile page for the frontend, the [pull request](https://github.com/bounswe/bounswe2022group7/pull/516) has been merged into the develop branch.
