### ISSUE TITLE
Frontend: Create Event and Art Item Pages

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#401]
We need to add create event and art item pages to the frontend. 

Prototypes of the JSON responses and bodies were shared in #394 as [a notion note](https://omniscient-stock-09e.notion.site/json-943f816afebf4915a31ee7ee1c079809). [An additional discussion](https://github.com/bounswe/bounswe2022group7/issues/394#issuecomment-1309816809) took place for updating these samples.

These pages should be created in frontend using the samples and the discussion as reference.

Deadline: 14.11.2022, 12:00
Reviewer: @erimerkin

**Comment by CahidArda** [comment]
I have prepared the new event (online & physical) pages. I haven't created a branch yet. It is pointless to create a branch and add these pages yet. This is because the endpoints for these features don't exist yet. I will branch out when the endpoints are ready.

In addition to the create event & art item endpoints, I also need the user endpoint where we will receive user data in response to the token. This will allow me to add a list to the create online exhibition page. User will be able to select from his/her art items.

I have defined a layout for showing these create event forms. I am planning to change the layout to be a little wider and add a padding in these forms. Then I can use the same form in the art item and event pages.

### Physical

![image](https://user-images.githubusercontent.com/57228345/201677540-ce2fdb68-481b-4931-9c31-67b0fe042ab8.png)

### Online

![image](https://user-images.githubusercontent.com/57228345/201677709-7c74c1de-08b1-467f-9c2a-9c2b9097d30d.png)

**Comment by CahidArda** [comment]
I integrated the create event and art item pages with the new endpoints. Ready for review.

**Comment by erimerkin** [comment]
Since the associated PR #459 is reviewed and merged to `develop` branch, this issue is now completed.
