### ISSUE TITLE
Update the Project Plan after Milestone 1

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#402]
As mentioned in [Team Meeting 5](https://github.com/bounswe/bounswe2022group7/wiki/CMPE451-Meeting-Notes-%235), I will update our project plan. There were a lot of changes in the Project Plan during our progress for the first milestone.

Here are a couple of significant points that will be included in my update:
- DevOps related tasks will be added.
- Our sub-teams will be updated. People who did not contribute to a specific task will be excluded.
- We implemented different features for the first Milestone rather than the ones that we mentioned in the previous plan. Those will be fixed.
- We are going to handle more features every week. After the update, we will have these features until the Milestone 2:

    | Week | Tasks |
    |--|--|
    |15/11/2022 - 22/11/2022 |1. Profile Page & Settings <br> 2. Follow functionality <br> 3. Geotagging functionality |
    |23/11/2022 - 30/11/2022 |1. Discussion Page & Comments <br> 2. Annotations|

**Deadline: 15/11/2022, 23:59**
**Reviewer: @demet47**

**Comment by canatakan** [comment]
After [Team Meeting 6](https://github.com/bounswe/bounswe2022group7/wiki/CMPE451-Meeting-Notes-%236), @ENESAYDOGDUOGLU wanted to take responsibility for the update of the Project Plan. I will now assign this task to him and just be a reviewer at the later stages of this task's development.

I can summarize TO-DOs so that Enes can also benefit from them:
- Rearrange the teams, so, reassign the resources in ProjectLibre.
- Add DevOps related tasks which were mostly completed by Erkin (check the repository for the tracking).
- Add the tasks mentioned above to the time range between Milestone 1 and Milestone 2.
- Rearrange the future tasks, put more features every week because we are able to do so (and we have to, in order to be able to complete everything before the deadlines)

I shared the current Project Plan with you via our communication channel.

**Comment by demet47** [comment]
@canatakan is the issue still in progress or did we forget to update the status of the issue.
Also, from the comments above I see that you also switched to a reviewer status. Am I still a reviewer, are there two reviewers at the latest status (me and you)?

**Comment by canatakan** [comment]
Hello @demet47,

* As you can see above, Enes is responsible for the development of this task. So, he is the one who should let us know if the task is in progress or not by providing his progress.

* I thought I could review Enes' submission beforehand since I mostly worked on planning and I am familiar with our schedule. I guess you can still review it for the last time when the finalized version is ready. If you do not want to track this issue anymore, you may simply remove your assignment, so I can handle it as well. It depends on your choice.

**Comment by demet47** [comment]
Thanks for the reply @canatakan!
I think this task doesn't require a second eye for review since the changes are going to be done according to our discussions in weekly team meeting. Thus I am removing myself from assignees.

**Comment by ENESAYDOGDUOGLU** [comment]
[At the meeting on November 15th](https://github.com/bounswe/bounswe2022group7/wiki/CMPE451-Meeting-Notes-%236), I wanted to undertake the project plan update task. I'm working on it, when I'm done, I'll share it with your approval.

**Comment by canatakan** [comment]
Hello @ENESAYDOGDUOGLU, we should complete the updates in the plan before the overwhelming period of non-stop coding and documentation before Milestone 2. So, what stage are you at currently? Do you need any help?

**Comment by ENESAYDOGDUOGLU** [comment]
It required several updates due to changes in planning. If the following topics are appropriate, I can share the final version of the plan with you.

1. Implement: Home Page
2. Implement: Authentication Features
3.Implement Event Page 
4. Implement Art Item Page
5. Implement: Artist Users & Art Items
6. Implement: Events
7. Implement: Discussion Page & Comment Threads
8. Implement: Profile Page & Regular User Features
9. Implement: Geotagging
10. Implement: Following Feature
11. Implement: Annotations
12. Implement: Semantic Search & Filtering

**Comment by canatakan** [comment]
* Thanks for reporting the progress. We discussed the situation of the Project Plan in our latest meeting. Please finalize and upload the Project Plan according to our discussions.

* Do not forget to both include a Detailed Sheet of the tasks and a Gantt Chart. You can check our [previous Project Plan](https://github.com/bounswe/bounswe2022group7/wiki/Project-Plan). Please stick to this format.

**Comment by ENESAYDOGDUOGLU** [comment]
I updated the project plan, you can see the final version [here](https://github.com/bounswe/bounswe2022group7/wiki/Project-Plan).

**Comment by canatakan** [comment]
Hi @ENESAYDOGDUOGLU, thank you for your updates. Here are a couple of significant points:

* **DevOps related tasks should be added as Erkin has spent/is spending a significant time on it.** It should be included in our time & resource estimations.

* There is a typo in the meeting numbers of Week 10. Additionally, we did not have many of those team meetings written in there. However, I don't think that we need to include meetings in the Plan week by week as we followed an irregular schedule for them. Either correct the meeting numbers in the Plan (for example, the Front-end Team only has a single meeting, so delete all the other meetings) or simply remove meetings for the future from the Plan.

* Finally, in the Gantt Chart, not all the resources are visible. I think we should be able to check those team-by-team. If it is very difficult to do because of the software, just skip it. Please try to correct it otherwise.

**Comment by ENESAYDOGDUOGLU** [comment]
Hi @canatakan, thank you for your feedback,

- I talked to Erkin and added DevOps related tasks.
- I edited the meeting numbers and dates

You can see updated version of [project plan](https://github.com/bounswe/bounswe2022group7/wiki/Project-Plan).

**Comment by canatakan** [comment]
Thank you for finalizing the Project Plan. I reviewed your submission.

* This version is much better and it can be used for planning our development towards the Final Milestone.
* The Gantt Chart is still not the best but I think correcting it requires a lot of effort because of the software we are using. 
* Also, I would be glad if you could also share the `.pod` file with me as a back-up.

Since this task is now completed, I am closing this issue.
