### ISSUE TITLE
[Mobile] Art Item Creation Page UI

### ISSUE THREAD

**Issue by atillaturkmen** [bounswe/bounswe2022group7#403]
As discussed in our [weekly meeting](https://github.com/bounswe/bounswe2022group7/wiki/CMPE451-Meeting-Notes-%235), I was assigned to implement UI of art item creation page. In this page, users will be able select pictures and these pictures will be encoded in base64 format before being sent to backend.

Here are the tasks for completing this issue:
- [x] Create a branch for the task
- [x] Find and import a library for selecting pictures from gallery
- [x] Encode images in base 64
- [x] Create the UI of the page.
- [x] Add navigation to this page in the menu
- [x] Create a PR

Reviewer: @AlicanM 
Deadline: 14/11/2022 23:59

**Comment by atillaturkmen** [comment]
I have implemented the UI of art item creation page. Here are the screenshots of the new art item creation page:

![Screenshot (111)](https://user-images.githubusercontent.com/59166549/201704246-b32a1753-d77e-4e21-880a-e2fe43308a33.png)

After selecting a picture:
![Screenshot (112)](https://user-images.githubusercontent.com/59166549/201704274-b40c73e4-08da-40fc-9cda-3b76a34d5dad.png)

**Comment by atillaturkmen** [comment]
I have created a [pull request](https://github.com/bounswe/bounswe2022group7/pull/406) and added @AlicanM as the reviewer. This issue can be closed after the review.

**Comment by AlicanM** [comment]
I have reviewed the PR and created a change request about validators.

**Comment by AlicanM** [comment]
Requested changes are done. Merged the [pull request](https://github.com/bounswe/bounswe2022group7/pull/406). Closing the issue.
