### ISSUE TITLE
Fix .env issue in Mobile Widget Tests 

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#405]
Since the `main` method in `main.dart` file is not run during the widget tests, the `.env` file cannot be loaded and the test fails as the IP address and the port cannot be loaded from it.

- [x] Open a hotfix branch
- [x] Update `event_page_test.dart` to load `.env` configurations for testing
   ~Update the `api_endpoints.dart` so that it will not throw an exception when the `.env` file cannot be loaded~
- [x] Open the pull request and send it for review

**Deadline: 15/11/2022, 15:00**
**Reviewer: @atillaturkmen**

**Comment by canatakan** [comment]
- The branch has just been created with commit 90809903be76f55c320dc6da4d0ab32d915883cd.
- The issue was much easier to solve than I thought as the `dotenv` library provides a function named `testLoad` for testing purposes.
- After the update the test ran successfully.

**Comment by atillaturkmen** [comment]
I have reviewed the pull request, there were no issues and tests passed. I merged the PR so now this issue can be closed.
