### ISSUE TITLE
[Mobile] Configure Continuous Integration Workflow

### ISSUE THREAD

**Issue by erimerkin** [bounswe/bounswe2022group7#408]
Previously, I have created CI/CD for backend and frontend parts of code. Now, we need to create mobile CI workflow to test the PRs to ensure the stability and concurrency of the codebase.

This workflow should also include an option to compile and upload the APK files for releases.

**Deadline: 23.59, 2022-11-14**
**Reviewer: @canatakan**

**Comment by erimerkin** [comment]
Continuous Integration workflow is now created in commit https://github.com/bounswe/bounswe2022group7/commit/862ce2c5990a5bf429bf78d2f3949dd5d1c845da. This workflow will run when a pull request is opened for `develop` and `master` branches. 

I was not able to accomplish automatically uploading the resulting binary file (.apk) to a release so that feature will be on hold. This issue is now complete @canatakan and the subsequent PRs should be reviewed: #411 and #412

**Comment by canatakan** [comment]
The pull requests mentioned above are merged into the respective branches after the reviews. Thank you for your work. This task is now completed.
