### ISSUE TITLE
[Mobile] Removal of Optional Fields in Signup Page

### ISSUE THREAD

**Issue by musasimsekdotdll** [bounswe/bounswe2022group7#410]
As discussed in [this week's mobile team meeting](https://github.com/bounswe/bounswe2022group7/wiki/MOBILE-Meeting-Notes-%234), I am assigned to remove the fields(like fullname, date of birth etc.) that is optional to fill in the signup page.

This task is divided to two sections:

- [x] Removal of optional fields from the signup page
- [x] Adding a progress bar showing the registration process(if user does not fill the optional fields, progress bar will be filled up to the half of the whole bar)

Reviewer: @canatakan
Deadline: 15/11/2022, 23:59

**Comment by musasimsekdotdll** [comment]
I have created a [branch](https://github.com/bounswe/bounswe2022group7/tree/dev/android/signup-additional-fields) named _dev/android/signup-additional-fields_ for the changes I will make.

**Comment by musasimsekdotdll** [comment]
Optional fields are removed from the register page. I tried to register with this new version while backend part is running in my local machine and the register operation was successful.

Here is how the page looks:
![Screenshot_20221116-235511](https://user-images.githubusercontent.com/74203551/202294995-d84c0b2f-3fea-4ecc-bac9-d6682df5c930.png)


Note that I will refer code-wise changes when I open a pull request for this feature.

**Comment by musasimsekdotdll** [comment]
In profile page, I check whether the user has filled optional fields somehow. For now, this check is based on the fullname of the user: if user has a valid fullname, then that user is considered as one completed his/her profile. If the fullname is not valid, like an empty string, then a progress bar displaying that half of the profile completion process is completed will be shown, with a directive to complete the profile.

If user has filled optional fields, then the profile page looks like:
![Screenshot_20221116-235408](https://user-images.githubusercontent.com/74203551/202296424-867b34b8-03cf-4198-b4f1-79e8a50b9a13.png)


Else, it will look like:
![Screenshot_20221116-235435](https://user-images.githubusercontent.com/74203551/202296509-458bf24d-2500-4f37-b8a6-b9a8d10addff.png)


I will refer code-wise changes of this part in pull request, too.

**Comment by musasimsekdotdll** [comment]
I created a [pull request](https://github.com/bounswe/bounswe2022group7/pull/414).

**Comment by canatakan** [comment]
* The review is completed. I did not request any changes, and merged your updates in commit ae071439d13553fe8379c6e6657bece9877a5da4.

* The task is now completed, hence closing the issue.
