### ISSUE TITLE
Author Field Missing For Comments in Comment List

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#420]
When we call BASE_URL/art_item/ART_ITEM_ID, the returned json contains comment list.
On a request from frontend, I am to add author field to each comment located in that list.

**Deadline:** 21/11/2022
**Reviewer:** @sabrimete

**Comment by demet47** [comment]
@CahidArda is it fine if I send you the whole registeredUser object as author? Otherwise I will implement another solution.

**Comment by CahidArda** [comment]
It's fine.

**Comment by demet47** [comment]
@CahidArda the current version doesn't send the whole user. You can find the details in the PR referenced in this issue.

**Comment by demet47** [comment]
@sabrimete the related PR is merged so I think the issue can be closed.

**Comment by sabrimete** [comment]
> @sabrimete the related PR is merged so I think the issue can be closed.

Yes, you are right. Sorry for the delay.
