### ISSUE TITLE
[Backend] Signup as an Artist

### ISSUE THREAD

**Issue by sabrimete** [bounswe/bounswe2022group7#423]
Right now, all signed up users are Regular Users. However, Artists should also sign up as Artist. 
This fix is required to distinguish users with their types.

@sabrimete is assigned to implement this.

Deadline: 23.59, 2022-11-21
Reviewer: @askabderon

**Comment by askabderon** [comment]
Tagging this issue as completed and closing it since the corresponding PR is merged. Thanks for working on this.
