### ISSUE TITLE
[CI/CD] Fix Android CI not running on Pull Requests

### ISSUE THREAD

**Issue by erimerkin** [bounswe/bounswe2022group7#425]
Currently our [Android CI](https://github.com/bounswe/bounswe2022group7/actions/workflows/Android-CI.yml) is not running properly on Pull Requests. So to ensure that each change works without major problems/passing tests, I need research the reasoning and fix the implementation of the workflow.

**Deadline: 23.59 2022-11-21**
**Reviewer: @atillaturkmen**

**Comment by erimerkin** [comment]
I found that in our [Android-CI.yml file](https://github.com/bounswe/bounswe2022group7/blob/master/.github/workflows/Android-CI.yml) the path for mobile source code is wrong as it is specified as `mobile` while the current folder is named as `android`. I will open a branch and merge fix to develop branch.

**Comment by erimerkin** [comment]
I found inconsistencies between run conditions of [Android CI](https://github.com/bounswe/bounswe2022group7/actions/workflows/Android-CI.yml), [Backend CI](https://github.com/bounswe/bounswe2022group7/actions/workflows/Backend-CI.yml), [Fronend CI](https://github.com/bounswe/bounswe2022group7/actions/workflows/Frontend-CI.yml). So after changes all CIs should run in this conditions:

- On PRs and pushes to develop if a filed related to themselves is changed
- On PRs to master without any condition
- Called from another workflows

**Comment by erimerkin** [comment]
The problems with CI setup is fixed in commit 43ba094 and the status can be checked in #426. Since there is a problem with android tests(an exception is throws) this issue and PR will be suspended until the tests are fixed.

**Comment by atillaturkmen** [comment]
I have fixed the android tests and pushed the changes to branch https://github.com/bounswe/bounswe2022group7/pull/426.

CI seems to work with no issues so I am merging the branch and closing the issue.
