### ISSUE TITLE
Non-functional requirements

### ISSUE THREAD

**Issue by azizamankenova** [bounswe/bounswe2022group7#43]
The non -functional requirements should be written to the [Google document](https://docs.google.com/document/d/1NGibMXZMf8aAyCiVXT8a_oKjVlsaaZQ-He6By9bBtlc/edit)
The non-functional requirements should include 
- Annotations
- Accessibility
- Performance and Reliability
- Security
- Legal and Ethical Issues

After the completion, the requirements should be written on the wiki page 
The deadline: 23:59/14.03

**Comment by canatakan** [comment]
You can also add your final work to our [Requirements Draft](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)) page after you are done with it in the Google document, as discussed in Slack.

Thank you for your hard work!

**Comment by CahidArda** [comment]
I transfered the requirements items we had written down on the [Google document](https://docs.google.com/document/d/1NGibMXZMf8aAyCiVXT8a_oKjVlsaaZQ-He6By9bBtlc/edit) to the [requirements draft](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)).

Closing the issue.
