### ISSUE TITLE
Implementing follow functionality

### ISSUE THREAD

**Issue by AlicanM** [bounswe/bounswe2022group7#435]
As mentioned in [this meeting](https://github.com/bounswe/bounswe2022group7/wiki/MOBILE-Meeting-Notes-%235), i will implement follow functionality.

Subtasks:
- [x] Branch out from the develop branch
- [x] Navigation to other profiles
- [x] Add UI to follow other profiles
- [x] Network connections 
- [x] Create a PR 

Due Date: 21/11/2022, 23:59
Reviewer:  @canatakan

**Comment by AlicanM** [comment]
[branch](https://github.com/bounswe/bounswe2022group7/tree/dev/android/follow)

**Comment by AlicanM** [comment]
Pressing the creator username in event and art items view pages redirects to creators profile page [commit](https://github.com/bounswe/bounswe2022group7/commit/c31f32fe74d07ff7b5ff2082c92e65fdbf7d9f72)

**Comment by AlicanM** [comment]
follow button added to profile page [commit](https://github.com/bounswe/bounswe2022group7/commit/64998a663528e7f1aaa0ef9d5a21964a30168d1b)

**Comment by canatakan** [comment]
The pull request #499 was finally merged. Thank you for your contribution, closing the issue.

**Comment by AlicanM** [comment]
I reopened this issue, since the backend for followedBy is implemented.
I will add the  check if a profile page visited is already followed to change the "follow" button to "following"

**Comment by AlicanM** [comment]
[branch](https://github.com/bounswe/bounswe2022group7/tree/dev/android/follow_fix)
update the follow button for already followed users [commit](https://github.com/bounswe/bounswe2022group7/commit/0ac0764b9ad46f07dabb9c84e42198d817bd815c)
Created the [PR](https://github.com/bounswe/bounswe2022group7/pull/604)
Ready to review @canatakan

**Comment by canatakan** [comment]
I approved and merged your pull request. Thank you for your work, closing the issue.
