### ISSUE TITLE
Viewing and Deleting the Settings Page

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#437]
In [backend meeting](https://github.com/bounswe/bounswe2022group7/wiki/CMPE451-Meeting-Notes-%236) I was assigned to write setting related endpoints:
- [x] view settings
- [x] modify settings

**Reviewer:** @askabderon 
**Deadline:** 21/11/2022

**Comment by demet47** [comment]
I implemented the necessary endpoints. Please do have a look at the fields I provided @CahidArda @atillaturkmen . Are they feasible for you? Do you want any additions or subtractions?

**Comment by askabderon** [comment]
Tagging this issue as completed and closing it since the corresponding PR is merged.
