### ISSUE TITLE
[BE] Implementation of Discussion Post and Comment endpoints

### ISSUE THREAD

**Issue by askabderon** [bounswe/bounswe2022group7#438]
Since I completed my weekly tasks and still have time, I am going to write the upcoming week's discussion post and comment related endpoints that are already discussed in the [team meeting](https://github.com/bounswe/bounswe2022group7/wiki/CMPE451-Meeting-Notes-%236)

- [x] GET DiscussionForum
- [x] GET Discussion
- [x] POST Discussion
- [x] POST Comment
- [x] GET Comment (?)

**Reviewer:** @demet47  
**Deadline:** 28/11/2022

**Comment by askabderon** [comment]
Endpoints on this issue is implemented in the mentioned PR. Since it is merged, I think we can close this issue @demet47

**Comment by demet47** [comment]
Since I also am the reviewer of the related PR, I see no fault and thus am closing the issue.
