### ISSUE TITLE
[Mobile] Add Geotagging to Create Event Page

### ISSUE THREAD

**Issue by atillaturkmen** [bounswe/bounswe2022group7#439]
As mentioned in [this meeting](https://github.com/bounswe/bounswe2022group7/wiki/MOBILE-Meeting-Notes-%235), i will add geotagging feature to create event page by adding a map for selecting a location for an event.

Subtasks:
- [x] Research about map libraries for flutter
- [x] Implement selecting a location from the map
- [x] Create a PR 

Due Date: 21/11/2022, 23:59
Reviewer:  @canatakan

**Comment by atillaturkmen** [comment]
After some research, I have found [flutter_map library](https://docs.fleaflet.dev/) for Flutter that is based off of 'leaflet.js'. It looks like we can use this library for selecting a location from map and also getting user's location.

**Comment by atillaturkmen** [comment]
I have decided to use [open street map library](https://pub.dev/packages/flutter_osm_plugin). Here is a screenshot of the location select page:

![Screenshot (120)](https://user-images.githubusercontent.com/59166549/203030142-682e90f9-2725-4486-b646-d83c65a2f595.png)

Now I will open a pull request and add @canatakan as the reviewer.

**Comment by canatakan** [comment]
I have approved your updates in the relevant pull request. I merged your updates into `develop` as can be seen in 814269aab688753496cd621a0fb024d604c1cefd. This task is now completed, I am closing the issue.
