### ISSUE TITLE
[Mobile] Fix post widgets in homepage

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#442]
As discussed in the [Mobile Team Meeting 5](https://github.com/bounswe/bounswe2022group7/wiki/MOBILE-Meeting-Notes-%235), I was assigned to the task of fixing the issue with the Post widgets used in Feed Container. 

* The current version cannot differentiate between an Art Item and Event. Therefore, post-specific data cannot be shown in the homepage.

* Some sub-tasks of this issue are as follows:
  - [x] Branch out from the `develop` branch
  - [x] Show post-specific data in the homepage
  - [x] Delete the `ArtItemCreator` model as it should not be different than the `User` anyway
  - [x] Create a pull request to merge the new branch `dev/android/post-model` into `develop`

**Deadline: 21/11/2022, 23:59**
**Reviewer: @atillaturkmen**

**Comment by canatakan** [comment]
- The branch named `dev/android/post-model` has been published with the initial commit f1b624e39c6b303a61c6b3ce033428323ef2dd58, and it can be found [here](https://github.com/bounswe/bounswe2022group7/tree/dev/android/post-model).
- An inheritance relationship between PostInfo and ArtItemInfo and EventInfo has been formed.

**Comment by canatakan** [comment]
- The inheritance relationship has been improved and `Event` and `ArtItem` extend `Post` with the commit 907b5ea1a704c6a4f8a5f932bc5f76f4bba98959.
- The objects are now sent to the `FeedContainer` in the correct way with the fix in the commit a376a4c59c120ba2d24997c98ee62dc841e84b14.

With these updates, we can use event-or-art-item-specific data in the homepage.

**Comment by canatakan** [comment]
`ArtItemCreator` model has also been deleted as there is no need for it now.

**Comment by canatakan** [comment]
The pull request has been created and linked to this issue. @atillaturkmen has been assigned as the reviewer. After his review is completed and the relevant pull request is merged to the `develop` branch, this issue can safely be closed.

**Comment by atillaturkmen** [comment]
I have reviewed the PR and merged it into develop branch.
