### ISSUE TITLE
[Mobile] Update Home Page endpoints & images

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#445]
As discussed in the [Mobile Team Meeting 5](https://github.com/bounswe/bounswe2022group7/wiki/MOBILE-Meeting-Notes-%235), I was assigned to the task of fixing the homepage's network connections.

- [x] Update the hardcoded endpoints according to the updates of the back-end (and parse the responses differently, if needed)
  
  Apparently, the new endpoints to fetch Events and Art Items are as below:
  - `api/homepage/event`
  - `api/homepage/artItem`

- [ ] Handle images in base64 standard with the new endpoints

**Deadline: 21/11/2022, 23:59**
**Reviewer: @atillaturkmen**

**Comment by sabrimete** [comment]
> * I have created the branch in commit [e6319e4](https://github.com/bounswe/bounswe2022group7/commit/e6319e42f30dc757f1ce562479c3603fd9810e0c). I am now using the new endpoints to fetch the data.
> * After some development, I pushed my commits on the image conversion as well. However, as the `image/{id}` endpoint requires authentication and the back-end team shall update this soon ([[BE] Fix Typo and Remove Auth from Image endpoints #449](https://github.com/bounswe/bounswe2022group7/issues/449)), I stopped working on this.

The issue you mentioned is closed now. authentication requirement is removed from `image/{id}` 
Also please beware of the other change in the issue. "lattitude" field had typo. It is now "latitude".

**Comment by canatakan** [comment]
Now the second step will be the integration of new Art Item models into the homepage. The updates for the Art Item model will be made by @atillaturkmen. I can help with the homepage integrations when Atilla completes his part.

**Comment by canatakan** [comment]
So, although we made use of some of it, the development in #471 will be abandoned as the branch is just behind and the desired functionality is achieved with the developments mentioned above.

Hence, this issue will also be cancelled as the PR.
