### ISSUE TITLE
[Mobile] Final Version of the Profile Page

### ISSUE THREAD

**Issue by musasimsekdotdll** [bounswe/bounswe2022group7#446]
As discussed in the [mobile meeting](https://github.com/bounswe/bounswe2022group7/wiki/MOBILE-Meeting-Notes-%235), I was assigned to update the profile page to the product level. There will be a few steps to finish this task:

- [x] making dropdown button work properly
- [x] making it the profile page of an actual user
- [x] dealing with real objects with dropdown button instead of mock data
- [x] putting the finishing touches to profile customization progress bar

Reviewer: @AlicanM 
Deadline: 21/11/2022, 23:59

**Comment by musasimsekdotdll** [comment]
I have created a new [branch](https://github.com/bounswe/bounswe2022group7/tree/dev/android/profile-page-finalver) to work on.

**Comment by musasimsekdotdll** [comment]
All tasks completed, the final version of the profile page of a user that created a physical event, an online event and an art item will look like:

- if s/he did not complete his/her profile:
    ### Events selected on dropdown
    
    ![events_half](https://user-images.githubusercontent.com/74203551/204916377-e9c1cf63-dfa8-4772-84bb-c149f1c451a6.png)


    ### Art Items selected on dropdown
    
    ![art_items_half](https://user-images.githubusercontent.com/74203551/204916494-6b98a978-aa0d-4710-9aa6-2e682feb36a1.png)


- If s/he completed his/her profile:

    ### Events selected on dropdown

    ![events_completed](https://user-images.githubusercontent.com/74203551/204916674-81ad8671-3bc3-4f33-9331-1f3a5cc186df.png)


    ### Art Items selected on dropdown

    ![art_items_completed](https://user-images.githubusercontent.com/74203551/204916790-35389726-166e-472d-98ad-d901e7c660a5.png)

**Comment by musasimsekdotdll** [comment]
Now, I will open a pull request regarding these changes.

**Comment by AlicanM** [comment]
I reviewed and approved the PR, so i also merged it. Thanks for your work.
