### ISSUE TITLE
Following User Endpoint

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#447]
According to [meeting notes](https://github.com/bounswe/bounswe2022group7/wiki/CMPE451-Meeting-Notes-%236), I was assigned to write an endpoint for following a user.

**Reviewer** : @askabderon 
**Deadline:** 23/11/2022 12.00

**Comment by demet47** [comment]
I linked the issue to a corresponding PR thus qwith merge the issue will autoclose. The reviewer for both are the same.

**Comment by askabderon** [comment]
Closing this issue since the corresponding PR is merged.
