### ISSUE TITLE
Converter from String of List to List

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#450]
We are currently holding a few fields that are originally lists as their string version to reduce redundant database tables. Frontend is translating this string to list. We are to provide a list and remove their conversion code.

**Deadline:** 30/11/2022 23.59
**Reviewer:** @sabrimete

**Comment by demet47** [comment]
@sabrimete the PR is merged so I think we can close the issue.

**Comment by sabrimete** [comment]
> @sabrimete the PR is merged so I think we can close the issue.

Yes, you are right. Closing the issue. Thanks for reminding.
