### ISSUE TITLE
POST Image Response Body Fixation

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#453]
Since the response body becomes too large and the data returned is unnecessary, the image will be reduced from response body and only image id will be returned for post image endpoint.

**Reviewer:** @demet47 
**Deadline:** 28/11/2022 23.59

**Comment by askabderon** [comment]
This issue is included in [PR](https://github.com/bounswe/bounswe2022group7/pull/462) and already merged. @demet47

**Comment by demet47** [comment]
From the discussions on the topic and by examining the successful PR request, I am concluded to close the issue.
