### ISSUE TITLE
Fix Namings for Endpoint About Discussion "Forum" to "Page"

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#454]
We fixed the naming of discussion forum to discussion post in requirements and other design documents along with some reduction in its diagrams.  This terminology is used as its pre-modification version in backend code. It is to be fixed to the current verison.

**Reviewer:** @sabrimete 
**Deadline:** 28/11/2022 23.59

**Comment by askabderon** [comment]
This issue is included to [PR](https://github.com/bounswe/bounswe2022group7/pull/462) and already merged @sabrimete

**Comment by sabrimete** [comment]
Yes, you are right. I'm closing the issue.
