### ISSUE TITLE
Discussion Post DTO Implementation

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#455]
Discussion page contains posts where each individual post is directed to an expanded page containing comments on the post. This main page contains reduced info of discussion posts and getAll returns a bloated list for them with lots of useless data. A DTO class is to be implemented for this and the list is to be returned of this new type. 

**Reviewer:** @demet47 
**Deadline:** 28/11/2022 23.59

**Comment by askabderon** [comment]
I am directing this issue to @sabrimete to achieve more balanced distribution of tasks.

**Comment by demet47** [comment]
The related branch is successfully merged and faultlessly working. Thus i am closing the issue.
