### ISSUE TITLE
Bug: Owner field null in Create Art Item Endpoint

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#457]
When a user creates an art item with the endpoint, no owner is assigned to the art item. I also realised that event endpoint doesn't return the people who created the event. I think we can change this too.

### Owner null in Art Item

![image](https://user-images.githubusercontent.com/57228345/204055171-882e1935-8492-4584-bb64-905610034350.png)

I believe I am using the latest version of the backend and the database. 

I assigned the issue to @demet47 since she is team lead but it's upto them to decide who handles this problem.

**Comment by askabderon** [comment]
@CahidArda 
Owner field is different than the creator field. Both Event and ArtItem has creator who created them by using this endpoint. Owner is going to be used for indicating the purchasing of the artItem. 

By default we cannot return Owner of the ArtItem and ArtItems of a RegularUser, it yields to nested loop in the response JSON. We can update these JSON formats as well but I think you can also use the /profile endpoint to get the details about the user. What do you think about this?

**Comment by CahidArda** [comment]
I think it would make sense to assign the person who created the art item as the owner. Then they can start an auction with the item. We can give whoever 'owns' the art item the privilege of starting the auction.

About using the profile endpoint: Which profile endpoint are you refering to? I want to show the user who owns or created the art item. None of the profile endpoints help me in this case unless I know the username. I don't get the username from the art item endpoint.

**Comment by askabderon** [comment]
We can initialize owner as creator, it makes sense to me.

We are using the POST endpoints with user token who is the creator of these events/artItems. GET /profile with the same token is going to return the user details of the creator. Am I missing the necessary field in this logic?

**Comment by CahidArda** [comment]
Assume artist X creates the event. Then user Y wants to view the event. Y can not get user information of X because Y doesn't have the token of artist X.

**Comment by askabderon** [comment]
Yes you are right. I was thinking about the post endpoint environment but we should reach the user details while getting the artItem/event information.

**Comment by CahidArda** [comment]
I think username field would be enough. Then we can use the `profile/<username>` endpoint to get the user info.

**Comment by askabderon** [comment]
With the latest commit of @demet47 GET endpoint is returning the creatorFields now. I think @demet47  can update POST endpoint of ArtItem and endpoints of events by a similar changes.

**Comment by askabderon** [comment]
This [PR](https://github.com/bounswe/bounswe2022group7/pull/464) was not intended to fix this bug but it also solves the part about returning the creator of the event/artItem. We are going to update the JSON by deprecating the unnecessary fields and making it smaller, however, you can use the creator information by fetching this endpoints now.

**Comment by demet47** [comment]
Thanks for reporting. I will fix the bug before our weekly group meeting on Tuesday.

**Comment by CahidArda** [comment]
Issue was handled. Closing the issue.
