### ISSUE TITLE
Document the scenario of copyright infringement reporting (mobile version)	

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#46]
As discussed in our [Weekly Meeting 3](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%233), we have decided to create a scenario and mock-up for a case where a user reports an artwork for copyright infringement.

About this scenario, we discussed these points below, in our meeting:
* Our persona can be an artist who owns the copyright for a particular artwork.
* We will create the scenario mostly focusing on the mobile application.
* The artist goes to the profile page that the artwork is listed, and recognizes that it's his/her piece of art.
* After clicking on the "Report" button, he/she fills the details.

After studying the topic and making necessary research, we can proceed with creating the relevant Wiki page and start to work on it collaboratively.

**Deadline: 19/03/2022, 23:59**

**Comment by canatakan** [comment]
As we discussed with @atillaturkmen, I have created and filled the necessary parts of the relevant scenario. The Wiki page can be found [here](https://github.com/bounswe/bounswe2022group7/wiki/Scenario-3).

Now, the next step is to arrange the requirements and the acceptance criteria according to our scenario.

**Comment by atillaturkmen** [comment]
Requirements are added to acceptance criteria.
https://github.com/bounswe/bounswe2022group7/wiki/Scenario-3:-Copyright-Infringement-Report

**Comment by canatakan** [comment]
The scenario is completed, and the mock-ups are also added. More details about the mock-ups can be found in [this issue](https://github.com/bounswe/bounswe2022group7/issues/53).

The job is now completed, and the issue can be closed.
