### ISSUE TITLE
[BE] Bug: GET Discussion Post Requires Token

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#469]
I have already [removed the posters from discussion posts](https://github.com/bounswe/bounswe2022group7/issues/460#issuecomment-1329789657) while implemeting the discussion pages but I ran into another problem. The GET discussion page endpoint requires user token.

I have already created [a branch](https://github.com/bounswe/bounswe2022group7/tree/dev/backend/discussion-update) where I removed the poster from discussion page. I believe you can fix the token issue there.

I have assigned this to @demet47 since she is the team lead. Issue can be reassigned.

**Comment by sabrimete** [comment]
I reassigned the issue to myself since I dealt with these kind of issues.

**Comment by CahidArda** [comment]
Task is handled. Thanks!
