### ISSUE TITLE
[BE] Bug: CommentList Problems in Event and DiscussionPost GET Endpoints

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#470]
There are two problems in the comment lists of GET discussion post and GET event.

## DiscussionPost GET: No Author Information in Comment

We simply get the author id, instead of receiving author information like we do in art item. I think it's because you used CommentDTO in art items but not here.

```json
"commentsList": [
  {
    "id": 15,
    "text": "Test comment 2",
    "creationDate": "2022-11-29T05:35:24.000+00:00",
    "lastEditDate": "2022-11-29T05:35:24.000+00:00",
    "upVotedUsers": [],
    "downVotedUsers": [],
    "author": 2
  }
]
```

## Event GET: List of Comment IDs

Additionaly, when I use the discussion post GET endpoint, I receive a list of comment id's, instead of comments themselves:

```json
{
    ...
    "creationDate": "2022-11-28T20:43:15.000+00:00",
    "commentList": [
        15,
        16
    ],
    "eventInfo": 5,
    ...
}
```

**Comment by askabderon** [comment]
@CahidArda existing issues about these classes fix these bugs as well. They have already merged to develop branch and I do not observe these bugs. Please check the corresponding endpoints and let me know in case of any troubles observed.

**Comment by CahidArda** [comment]
I will have a look at the current state of the endoints. Thanks for letting me know.

In the mean time, can you also look into removing the poster image from discussion posts? I had already tried it in the [dev/backend/discussion-update](https://github.com/bounswe/bounswe2022group7/tree/dev/backend/discussion-update) branch. If [the changes I have made](https://github.com/bounswe/bounswe2022group7/commit/d5a0468b9bc02c306425f306d8568e39e0a37b64) are correct, then you can create a PR and merge.

**Comment by CahidArda** [comment]
Problems in the endpoints were handled. Closing the issue.
