### ISSUE TITLE
Update Event View and Create Page endpoints

### ISSUE THREAD

**Issue by AlicanM** [bounswe/bounswe2022group7#479]
I was assigned to the task of checking and fixing the event view and create page's network connections.

**Deadline: 03/12/2022, 04:59**
**Reviewer: @musasimsekdotdll**

**Comment by AlicanM** [comment]
[new branch](https://github.com/bounswe/bounswe2022group7/tree/dev/android/event-network-fix) is created

**Comment by musasimsekdotdll** [comment]
I merged the pull request of this issue, now I am closing this issue.
