### ISSUE TITLE
Review the Project Requirements Draft

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#48]
[Draft](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-%28Draft%29/) we wrote for the project requirements will be reviewed. Following subtasks will be completed:
- [x] Items under the User Requirements will be indexed.
- [x] Coherence of the whole document will be reviewed.
- [ ] Requirements need to comply with the format described in the lecture. Items will be updated to comply with the format whenver possible.

Deadline: 3.4.2022

**Comment by HasanBingolbali** [comment]
@CahidArda 
WHAT TO CHANGE/ADD IN REQURIMENTS:
1) It is not clear what content does the guest user access (comments , discussion )?
2) We must be able to upvote the comments
3) The User wouldn’t have to enter the username and password over and over. If it is an active user, we will automatically log them in.
4) System also should track of number of attendance for both psychical and online events (Interested in going - not going buttons can be added ). So the system notify them when the events approach

**Comment by CahidArda** [comment]
Thanks for the suggestions. I agree that our requirements should clarify these points. Here is what I have done about the suggestions:
1. I added this to the list of questions we can ask the customer. 
2. I am confused about what the project description refers to when it says commenting: "The platform itself is run by the content creators who are the users. In this project, users can share their art items, **comment & discuss** about art items, and make exhibitions solo or collaboratively.". My understanding is that users will be able to comment on items and these comments will be visible on the page of the item. There are also comments on the discussion forum (maybe we should refer to these as a *reply* instead of a *comment*). I believe that this is something we should ask the customer and get clarification. Which of these do you refer to when you say comment?
3. I added this item to the Sign In section.
4. I believe this can be done with the bookmarking system. I believe we should still ask the customer what they refer to when they say bookmarking. I have added this to the questions too.

**Comment by CahidArda** [comment]
A new draft is prepared for the requirements. It will be presented to the team on the next meeting and this issue will be closed depending on the feedback.

**Comment by CahidArda** [comment]
I shared [the document I created while analyzing the project description](https://github.com/bounswe/bounswe2022group7/wiki/Project-Analysis-and-Possible-Customer-Questions) (which was then added to wiki by @canatakan) and [the new requirements draft](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)) with the team.

We asked the majority of the questions we had prepared while reviewing the project and the requirements in [the customer meeting on 23.3.2022](https://github.com/bounswe/bounswe2022group7/wiki/Customer-Meeting-Report).

Next, we need to update the requirements sections of the scenarios we had created. A new issue will be added about updating the scenarios.

**Comment by CahidArda** [comment]
Last item in the original subtasks of this issue will not be worked on. We asked the TA whether we need to make sure that the format complies with the format described in the lecture slides.

An issue (#58) is created for the task of updating the scenarios according to the new requirements draft. Therefore this issue will be closed.
