### ISSUE TITLE
[Mobile] Implement user profile settings

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#481]
During our latest lab session, I was assigned the task of implementing the settings page for the User. 

The desired functionality in this settings page is as follows:

#### Settings UI
*  ~There should be a connection from the User's Profile Page if the they are logged in~  
- [x] There should be a UI providing different tabs for different types of settings:
  - User Information (this part will be connected to the network)
  - Privacy and Account Management Settings (some settings related to the functions like blocking can be put here)
  - Account Settings

#### Network Connections for Settings
Although the design for the different tabs shall be visible, the functionality for filling extra information will be fully integrated with the back-end. So the User Information tab will be connected to the implemented endpoints.
- [x] Integrate `GET /profile/settings` (for viewing the current user information)
- [x] Integrate `POST /profile/settings` (for updating/entering the information)

---

After completing the implementation, I shall finalize my pull request and assign Atilla as the reviewer.

**Deadline: 04/12/2022, 05:00**
**Reviewer: @atillaturkmen**

**Comment by canatakan** [comment]
* The branch has been created with a very basic Settings Page with the commit 6403c9d888edf918312523205f75b71a917e0f41.
* The base for the newly created branch `dev/android/settings-page` is `dev/android/event-network-fix`.

**Comment by canatakan** [comment]
* The Main Settings UI that will redirect to the personal information page is completed with the commits e9844b607b3efd261b0ae98b7b117ca853df69d1, a0823b727aaf976cbe92cca156dc18b68f20a88d, and d5ffbf835e6bd7d4aafccf12c9f3e499e6b6de0a.

* An example screenshot from the Settings Page can be seen below.

  <br>
  
  <img width="415" alt="Screen Shot 2022-12-03 at 00 06 03" src="https://user-images.githubusercontent.com/56476673/205391251-031d24af-9df9-48d0-9634-1479121f1cb1.png">

**Comment by canatakan** [comment]
* With commit 61a8b851a37ed13f4ad41a545dd4c5f7cad2677d, the UI for viewing the personal information that is returned by the `GET /profile/settings` endpoint is completed.

* An example screenshot:

  <img width="417" alt="Screen Shot 2022-12-03 at 10 30 02" src="https://user-images.githubusercontent.com/56476673/205430193-6eeacb9c-242b-4a2f-b4a9-428fcb61eb4f.png">

**Comment by canatakan** [comment]
* As there are still some developments ongoing for the Profile Page, the connection between those pages will be made later on. For now, the first task is postponed.
* The relevant pull request has been opened and pending the review of @atillaturkmen.

**Comment by atillaturkmen** [comment]
I have reviewed and merged the pull request. Therefore this issue can be closed.
