### ISSUE TITLE
Test for Event Create Page

### ISSUE THREAD

**Issue by AlicanM** [bounswe/bounswe2022group7#482]
I will write test for the event create page.

Due: 3.12.2022 04.59
Reviewer: @canatakan

**Comment by AlicanM** [comment]
- I created new [branch](https://github.com/bounswe/bounswe2022group7/tree/dev/android/alican-unit-test)
- Wrote the test for the input fields [commit](https://github.com/bounswe/bounswe2022group7/commit/47fb7270453c382c05d1664bd7585caca22dcffa)
- Created the [PR](https://github.com/bounswe/bounswe2022group7/pull/483)
Ready for review @canatakan

**Comment by canatakan** [comment]
Hello @AlicanM, 

* Maybe we should merge your tests into `dev/android/event-network-fix` (pending review in #480). 
* The entire implementation then can be merged into `develop` after they are reviewed.

I am changing the base branch in your pull request, #483.

**Comment by canatakan** [comment]
After updating the base, I merged your PR into the related feature branch. You can find the merge commit in c514d9ff8e918e6eadd649be17083edeae4e4cb6.

This task is now completed, I am closing the issue.
