### ISSUE TITLE
[Mobile] Implement Create Art Item Network

### ISSUE THREAD

**Issue by atillaturkmen** [bounswe/bounswe2022group7#484]
During our latest lab session, I was assigned the task of implementing network functionality of create art item page.

These are the tasks to complete this issue:

- [x] Create a branch.
- [x] Fix art item models.
- [x] Create network function for creating art item.
- [x] Create a pull request and add @canatakan as reviewer.

**Deadline: 03/12/2022, 05:00**
**Reviewer: @canatakan **

**Comment by canatakan** [comment]
I merged your updates and added [my review](https://github.com/bounswe/bounswe2022group7/pull/485#pullrequestreview-1203465465) mentioning a future improvement. This task is, on the other hand, completed and the issue can be closed.
