### ISSUE TITLE
[Mobile] Comment Feature

### ISSUE THREAD

**Issue by musasimsekdotdll** [bounswe/bounswe2022group7#486]
I am assigned to implement comment related features. In order to complete this task, there are several points to achieve:

- [x] creating a new branch
- [x] backend integration: enpoint connections, model definitions etc.
- [x] widget creation: a widget that lists comments will be created and all necessary pages(event page, art item page etc.)

Reviewer: @AlicanM

**Comment by AlicanM** [comment]
[branch](https://github.com/bounswe/bounswe2022group7/tree/dev/android/discussion)

**Comment by musasimsekdotdll** [comment]
Comment feature is added to events and art items. Here is how comments look:

### Comments on Events:

- This is how event page looks like when a user wants to type a comment:

![event_comment_progress](https://user-images.githubusercontent.com/74203551/205676620-0deee20f-6baf-447d-b486-ce11554b720d.png)

- This is how the page looks like after the user pushed to the _comment_ button(send icon):
![event_comment_made](https://user-images.githubusercontent.com/74203551/205676829-13d20731-d155-46a5-95df-bf9e9f205bb6.png)



### Comments on Art Items:

- This is how art item page looks like when a user wants to type a comment:
![art_item_comment_progress](https://user-images.githubusercontent.com/74203551/205677018-e4494f43-dd16-4259-a597-ad24e924d733.png)


- This is how the page looks like after the user pushed to the _comment_ button(send icon):
![artitem_comment_done](https://user-images.githubusercontent.com/74203551/205677453-74dcbca4-0899-4526-b692-9ab569f80275.png)


As you can see, a user may upvote/downvote a comment but it is not integrated since the backend is not ready.

**Comment by musasimsekdotdll** [comment]
### Commits
- [comment first version](https://github.com/bounswe/bounswe2022group7/commit/ee9f4a60750bfe4678f261b6be026c1587acb6ec)
- [network fix](https://github.com/bounswe/bounswe2022group7/commit/be95c6ca18c2b0515c69aea5e6406c8ee46a5236)
- [comments are added to art item page](https://github.com/bounswe/bounswe2022group7/commit/6b1d621ba5228942ab060b40b00cc89f3d8ccb92)
- [a padding is added between comment list and adding-a-new-comment-button](https://github.com/bounswe/bounswe2022group7/commit/95e234cd287d6986ace414e1278e857725c24f59)
- [comment feature finished](https://github.com/bounswe/bounswe2022group7/commit/aa664e4086297975513765798b9a28d59fe9e739)

**Comment by canatakan** [comment]
Upon my review, the mentioned pull request (#519) has just been merged. The task is completed, closing the issue.
