### ISSUE TITLE
Web Annotation Service

### ISSUE THREAD

**Issue by guneyizol** [bounswe/bounswe2022group7#488]
Web Annotations feature requires a separate web service that is accessible from both mobile and web platforms.

**Comment by guneyizol** [comment]
MongoDB and Koa.js framework seems like a sufficient tech stack for our requirements.

**Comment by guneyizol** [comment]
I configured a separate docker network for development environment so that we can proxy fetch requests to the annotation service. This was required because we are using two separate docker compose configurations for the main app and the annotation service.

**Comment by erimerkin** [comment]
I have modified the dockerization of the annotation service to prepare it for deployment. Also I have merged the docker-compose files to manage the containers from a single place.  Relevant commit: 066b86d

**Comment by erimerkin** [comment]
The relevant PR #502 for the implementation of this issue is closed, so this issue is now completed.
