### ISSUE TITLE
[Frontend] Styling Content Pages

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#490]
The pages where we display content needs to be updated. Following pages will be updated:
- Discussion page
- Event page
- Art item page
- Create physical event page (will add start&end times)

Deadline: 4.12.2022, 23:59
Reviewer: @erimerkin

**Comment by CahidArda** [comment]
I have updated the pages I listed in the issue description. Additionaly, I defined the color palette.

## Art Item Page

![image](https://user-images.githubusercontent.com/57228345/205455378-576579af-06c8-4c21-b424-9e76d6bfd7b7.png)

## Event Page 

![image](https://user-images.githubusercontent.com/57228345/205455388-2d5a1b19-a459-404e-be02-ae1cf748bdaa.png)

![image](https://user-images.githubusercontent.com/57228345/205455393-95d933b3-950e-4bc8-b1d5-a09a5c5fb9bb.png)

## Discussion Page

![image](https://user-images.githubusercontent.com/57228345/205455405-ec658223-4511-466c-b09e-5bd6bd0839f2.png)

## Comment Section

All of the pages above are followed by a comment section:

![image](https://user-images.githubusercontent.com/57228345/205455441-f3cd9c7c-b58c-4645-ae37-c4203083c0d7.png)

## Create Physical Event Page 

Start and end time selection are added:

![image](https://user-images.githubusercontent.com/57228345/205455499-209feb3e-28d7-4d53-b496-4eba28002b18.png)

**Comment by erimerkin** [comment]
Since the associated pr in #491 is merged succesfully, this issue is now completed.
