### ISSUE TITLE
[Mobile] Show JPG Images

### ISSUE THREAD

**Issue by atillaturkmen** [bounswe/bounswe2022group7#493]
Right now, mobile app gives an error when image type is jpg instead of png. I will fix this issue and have the app show jpg images alongside png images.

Reviewer: @canatakan

**Comment by atillaturkmen** [comment]
I have opened a pull request and added @canatakan as the reviewer.
https://github.com/bounswe/bounswe2022group7/pull/494

**Comment by CahidArda** [comment]
In your code, you remove the beginning of the base64 string (`"data:image/png;base64,"` or `"data:image/jpeg;base64,"`) and pass the remaining part to `Image.memory`. Does it not work if you pass all of the base64 string including the beginning?

**Comment by canatakan** [comment]
> In your code, you remove the beginning of the base64 string (`"data:image/png;base64,"` or `"data:image/jpeg;base64,"`) and pass the remaining part to `Image.memory`. Does it not work if you pass all of the base64 string including the beginning?

I tried that way, it does not work. However, maybe splitting according to "," character might be a better idea, so that it will not depend on the image's file type. I will mention this in my review.

**Comment by canatakan** [comment]
Hello @atillaturkmen, I used a different approach to parse the base64 data. Please check [my review](https://github.com/bounswe/bounswe2022group7/pull/494#pullrequestreview-1203622717) and commit 8d79b5fd26ce676918dc16a84ff8772fea0afad9.

**Comment by CahidArda** [comment]
New version looks cleaner. Can you check if it works with image types other than png and jpeg? If this is a problem in mobile then we can avoid uploading other image types.

**Comment by canatakan** [comment]
As far as I checked, it works for all types.

**Comment by canatakan** [comment]
#494 has been merged after some additional updates. This task is completed, closing the issue.

**Comment by atillaturkmen** [comment]
> Hello @atillaturkmen, I used a different approach to parse the base64 data. Please check [my review](https://github.com/bounswe/bounswe2022group7/pull/494#pullrequestreview-1203622717) and commit [8d79b5f](https://github.com/bounswe/bounswe2022group7/commit/8d79b5fd26ce676918dc16a84ff8772fea0afad9).

I reviewed your addition, it works with no issues. I have also merged the pull request.
