### ISSUE TITLE
Sample Data Formation For Milestone 2

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#496]
We are to create sample data for the demos in Milestone 2 presenations.

**Deadline:** 05/12/2022 12.00

**Comment by demet47** [comment]
The user login credentials for the users I created for demo:

regular user:
```
{
    "email": "deniz.öztürk@mail.com",
    "password":"deniz123"
}
```

artist user:
```
{
    "email": "demet.yayla@mail.com",
    "password":"demet123"
}
```

**Comment by CahidArda** [comment]
We will probably erase the database before adding the data for the presentation by the way. There is a lot of testing data on the app currently which should probably be removed.

I suggest preparing postman requests if you are not doing that already. Don't add data for the presentation to the current database. It will be erased.

**Comment by demet47** [comment]
Really, thanks for letting me know! It is sad that I spent some hours already but you prevented some more.

**Comment by demet47** [comment]
We as the backend team (@askabderon , @sabrimete ) decided to create a postman collection to form samples in case we require an emergency drop of database.

**Comment by sabrimete** [comment]
I think we completed this issue and can close it. @demet47 feel free to close it.

**Comment by demet47** [comment]
We as the backend team held an online meeting to first drop the existing db to reset and then to form the sample datas. We saw that the data are correctly formed in web interface. Thus I am closing the issue.
