### ISSUE TITLE
Document the scenario of semantic search and discussion

### ISSUE THREAD

**Issue by AlicanM** [bounswe/bounswe2022group7#50]
We need to come up with a user scenario where users provide some semantic tags to get relevant content suggestions and discuss about art in forums.

Deadline: 19.03.2022 23:59

**Comment by azizamankenova** [comment]
The documentation of the scenario is completed. It can be viewed in the [Scenario 2](https://github.com/bounswe/bounswe2022group7/wiki/Scenario-2) wiki page. The issue can be closed now.
