### ISSUE TITLE
[Milestone] Complete the Annotations & Standards sections for the M2 Report

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#512]
As discussed in our latest group meeting, we are going to prepare the _Annotations_ and _Standards_ sections for the Milestone 2 Group Report.

Here are some key points that we discussed in the meeting:

- @guneyizol might give details about the front-end library, _[Annotorious](https://recogito.github.io/annotorious/)_ and how it complies with the W3C's [annotation model standards](https://www.w3.org/TR/annotation-model/).
- @erimerkin might include the results of the research that he has been working on at #466.
- @canatakan might summarize the UI implementation that the Mobile Team developed

**Deadline: 06/12/2022, 03:00**
**Reviewer: @CahidArda**

**Comment by canatakan** [comment]
I summarized the work done related to the annotations by the mobile team. I mentioned our implementation in the UI and the lack of connections to back-end, hence following the standards. You can see the updates in commit 56465edb1ad573e60bdbc41638169c206ebc4054.

**Comment by erimerkin** [comment]
I have added the standards part of the report in commit f9da4fe.

**Comment by canatakan** [comment]
The mentioned part was completed with our contributions and the finalized report was merged into `master`. I am now closing the issue.
