### ISSUE TITLE
[Milestone] Project Progress Documentation Related to Requirements

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#515]
For milestone report 2, in the meeting we held to distribute work for individuals, I was assigned to document progression of our project with respect to requirements.

**Deadline:** 05/12/2022 23.59
**Reviewer:** @canatakan @CahidArda

**Comment by demet47** [comment]
I completed the initial draft for it [here](https://omniscient-stock-09e.notion.site/Requirements-status-4db434b275b14fa29d5929f7eff3d6d9).

**Comment by demet47** [comment]
Last version can be seen [here](https://github.com/bounswe/bounswe2022group7/blob/dev/deliverables/deliverables/CMPE451_Customer_Presentation_Milestone_1/milestone_report.md#Individual-Contribution-Reports). It is ready to be filled by also frontend and mobile. It also requires revisions from backend on annotations and some non-functional requirements. 
I am tagging the leaders to this issue to be able to track the progression @atillaturkmen @guneyizol .

**Comment by canatakan** [comment]
Hello @demet47, first of all, I guess the link you shared is broken. I think you wanted to share [this file](https://github.com/bounswe/bounswe2022group7/blob/dev/deliverables/deliverables/CMPE451_Customer_Presentation_Milestone_2/milestone_report.md#13-progress-according-to-requirements). Apart from that, I can mention these points below:

- I think the format can be different than the current one. Maybe switching to tabular format will provide a better view; in the current version, it seems pretty complicated and going down for so long.
- The status of the requirements must be _completed_, _in progress_ or _not yet started_. If we would like to mention the progress in the sub-teams, maybe we can have another status named _partially completed_. However, the first three must exist in the report.
- Also, after updating the status of the requirements as I mentioned above, there will be no need to include the names of all sub-teams.

**Comment by demet47** [comment]
Hello @canatakan.
The final version wiill be different, the boxed info will be deleted and instead status will be written as given in description.
Tabular format I haven't tought of, thanks!

As for the progression of the issue:
I had read and comprehended and shortened the requirements, but with a final discussion among group members, I am to switch to a copy-paste of requirements and sometimes just mention the abstract headers when needed to shorten it all.

**Comment by CahidArda** [comment]
I saw that you have added all of the requirements. I thought it would take me too long to annotate every single requirement in the whole list as "done in frontend".

I instead replaced the requirements section with the requirements we added to the tag. I had already selected the features we were able to present in the milestone (in other words, things that worked in fe/be/mobile).

If you have requirements you are working on or requirements which are completed in your team but not all other teams, than feel free to make additions to the requirements and mark them as "in progress". I have already done this for annotations.

I think this will be faster than trying to mark all of the requirements. For the "not yet started requirements", I think saying something like "rest of the requirements are not yet started" in the beginning should suffice.

**Comment by demet47** [comment]
@canatakan @CahidArda latest version can be found in the same link. Modifications done considering also your feedbacks. Thanks for the suggestions!

**Comment by canatakan** [comment]
After commits cd9908497577034944cb54838be3cf86cbdfc19b and 36f34d3923f68825909c1ef66b3c9b7f5d812f09, the final version looks decent. I also updated some of the requirements before the aforementioned commits and the section, in general, looks good to me now.

**Comment by canatakan** [comment]
The project report was finalized and merged to the `master` branch. Thank you for your contribution, closing this issue.
