### ISSUE TITLE
[Mobile] Navigation From Signup Page

### ISSUE THREAD

**Issue by musasimsekdotdll** [bounswe/bounswe2022group7#518]
As discussed in the meetings, I was assigned to navigate the user that registered successfully to his/her profile page, where s/he can complete the profile.

Reviewer: @canatakan

**Comment by musasimsekdotdll** [comment]
1) After filling the fields in the register page:
![Ekran Görüntüsü (41)](https://user-images.githubusercontent.com/74203551/205682173-635145b8-494c-4115-9c2e-120008a39e99.png)

2) User taps the _Register_ button and is navigated to profile page automatically:
![Ekran Görüntüsü (42)](https://user-images.githubusercontent.com/74203551/205682347-cf6fcb68-2529-4326-8ee9-015ac52db767.png)

3) Optionally, s/he may want to give the remaining personal information by pressing _Go Complete_ button:
![Ekran Görüntüsü (43)](https://user-images.githubusercontent.com/74203551/205682554-aa813e2a-97cb-496c-8a75-24c86be02091.png)

**Comment by musasimsekdotdll** [comment]
## Commits

- [navigation to settings page](https://github.com/bounswe/bounswe2022group7/commit/86073ab94c33e64989ea0a109ba1483c989f8c96)
- [routing to accountInfo edit page is completed](https://github.com/bounswe/bounswe2022group7/commit/f1690d0057c23641d22e34d6a6af2187ef15fa9d)
- [from register page to profile page](https://github.com/bounswe/bounswe2022group7/commit/07902e3c7a882afc1d0716799909c13fbda24f2a)

**Comment by canatakan** [comment]
I checked your updates in the relevant pull request and I think that this kind of a user experience is better. This task is completed, and the issue can be safely closed.
