### ISSUE TITLE
Tag for Milestone 2

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#526]
We need to create a tag for milestone 2. The tag description shall include a brief description of the app and the requirements we cover in this milestone.

Deadline: 6.12.2022, 14:00
Reviewer: @erimerkin

**Comment by CahidArda** [comment]
I have listed the requirements we covered below:

### 1.1.1. Sign Up
* 1.1.1.1: Guest users shall be able to register for an account by providing an email address and a password.
* 1.1.1.2: Duplicate email addresses shall not be accepted.
* 1.1.1.3: Guest users who are trying to sign up shall also pick a unique username to complete the registration process.
* 1.1.1.4: Duplicate usernames shall not be accepted.
* 1.1.1.5: Guest users could provide extra information while signing up, like name, surname, location, age.
* 1.1.1.6: Guest users shall choose their account type, "Artist" or a "Regular User".

### 1.1.2. Sign In
* 1.1.2.1: Users shall be able to sign in using their email and password combination.
* 1.1.2.2: Users shall be able to sign out without a restriction.

### 1.1.3. Guest Users
* 1.1.3.1: Guest Users shall be able to view profile pages, art items, pages of online/physical exhibitions.
* 1.1.3.3: Guest Users shall not be able to make any changes in the state of the system.


### 1.1.4 Comments

* 1.1.4.1: Registered users and artists shall be able to view comments that belong to art items or exhibitions
* 1.1.4.2: Registered users and artists shall be able to create comments on the discussion page.
   * 1.1.4.2.1: Registered users and artists shall be able to edit their comments in the discussion page.


### 1.1.5 Events

* 1.1.5.1: Artists shall be able to arrange physical events
* 1.1.5.5: Artists shall be able to arrange **Physical Exhibitions** using the platform.
   * 1.1.5.5.1: Artists shall be able to mark event location in Physical Exhibitions via using geotagging. 


### 1.1.9 Home Page

* 1.1.9.1: The home page shall highlight the most popular artworks and events of the previous week as well as the events in the coming days that are highly anticipated by the users for the guests.

### 1.1.10 Profile Page

* 1.1.10.1 Followers and the users that a certain user follows shall be visible in his/her profile page.
* 1.1.10.3 The profile page shall include name, surname, location, username and profile picture.
* 1.1.10.6 The users shall be able to edit the information included in their profile pages.
* 1.1.10.7 Art items that an artist have shall be visible in his/her profile page.

### 1.1.13 Annotations
* 1.1.13.1: Registered users shall be able to annotate text segments with corresponding links.
    * 1.1.13.1.2: Registered users shall be able to annotate text segments in replies in comments.
    * 1.1.13.1.3: Artists shall be able to annotate text segments in their own exhibition descriptions and online gallery descriptions.
    * 1.1.13.1.4: Artists shall be able to annotate text segments in their own art item descriptions.
* 1.1.13.2: Registered users shall be able to annotate various content by adding custom labels.
    * 1.1.13.2.1: Registered users shall be able to label discussion comments.
    * 1.1.13.2.2: Artists shall be able to label their own exhibition and online galleries.
    * 1.1.13.2.3: Artists shall be able to label their own art items.

**Comment by erimerkin** [comment]
I have published the release [0.2.0-alpha](https://github.com/bounswe/bounswe2022group7/releases/tag/customer-presentation-2) with tag [customer-presentation-2](https://github.com/bounswe/bounswe2022group7/tree/customer-presentation-2). The tag is currently being deployed: [Frontend](https://github.com/bounswe/bounswe2022group7/actions/runs/3628456212), [Backend](https://github.com/bounswe/bounswe2022group7/actions/runs/3628456216), [Annotation](https://github.com/bounswe/bounswe2022group7/actions/runs/3628456218)

After deployment the application will be available at address http://3.121.123.234/. The API can be accessed from http://3.121.123.234/api/ and Annotation microservice can be accessed from http://3.121.123.234/annotations/ addresses.

**Comment by erimerkin** [comment]
The description and covered requirements are added, only the `.apk` file for mobile is needed.

**Comment by canatakan** [comment]
@erimerkin I have also added the `.apk` file for the release version. The file can be found [here](https://github.com/bounswe/bounswe2022group7/releases/download/customer-presentation-2/ideart.apk).
