### ISSUE TITLE
[Mobile] Add widget tests for Settings Page

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#528]
I shall write widget tests for the Settings Page. Here are the steps to create a correct test:

1) The User Provider should be initialized so that the `token` field that will be used for the authorized http call will not be null.
2) The GET request to `/profile/settings` should be mocked.
3) The GET request to `/image/{id}` to get the profile picture of the user should be mocked. For this purpose, a mock base64 image should be prepared so that the widget should be able to get built with the processing of the mock image.

**Reviewer: @atillaturkmen**
**Deadline: 06/12/2022, 20:30**

**Comment by canatakan** [comment]
The pull request has been opened and pending review from @atillaturkmen. Now adding this issue to the development of the relevant pull request for easier tracking.

**Comment by atillaturkmen** [comment]
I have reviewed and merged the pull request https://github.com/bounswe/bounswe2022group7/pull/529. So I am closing this issue as completed.
