### ISSUE TITLE
Create a template for mobile

### ISSUE THREAD

**Issue by erimerkin** [bounswe/bounswe2022group7#53]
A mobile template for [Scenario 3](https://github.com/bounswe/bounswe2022group7/wiki/Scenario-3:-Copyright-Infringement-Report) with issue #46 should be created.

Deadline: 21-03-2022 23.59

**Comment by erimerkin** [comment]
A template and mockups for [Scenario 3]() is created and added to scenario page as can be seen in [revision](https://github.com/bounswe/bounswe2022group7/wiki/Scenario-3:-Copyright-Infringement-Report/9b4ddd973ec5057ccd1ec393ca0fd66c985b0d56). Now, it needs **review** from scenario group.

### Scenario 3 Group:
@canatakan 
@atillaturkmen

**Comment by canatakan** [comment]
> A template and mockups for Scenario 3 is created and added to scenario page as can be seen in [revision](https://github.com/bounswe/bounswe2022group7/wiki/Scenario-3:-Copyright-Infringement-Report/9b4ddd973ec5057ccd1ec393ca0fd66c985b0d56). Now, it needs **review** from scenario group.
> 
> ### Scenario 3 Group:
> @canatakan @atillaturkmen

Thank you for your great work! These mobile mock-ups are suitable for our scenario and look great. The revision is reviewed, and thus this job is now completed.

**Comment by erimerkin** [comment]
Since the mockups are reviewed and task is completed, I will close this issue as completed.
