### ISSUE TITLE
Implementing Unit Tests on Backend

### ISSUE THREAD

**Issue by askabderon** [bounswe/bounswe2022group7#531]
We should write unit tests for endpoints and the existing several methods. However, I could not totally understand how to implement unit tests for endpoints in Kotlin. 

We should research on this topic and should add unit tests as backend members. This issue created for sharing the research topics and implementing the first unit test example. We can close this issue after the first unit test is done successfully.

Deadline: 14.12.22 23.59

**Comment by sabrimete** [comment]
I already spent at least 6 hours tried to implement it. I hope I finally ran some tests without an error. I will create a PR for that in a minute. Please check it out.

**Comment by askabderon** [comment]
Since the research part is done and first unit tests are introduced to the code, I am closing this issue. If there are necessary unit tests implementation we can create more specific issue regarding that.
Thanks @sabrimete!
