### ISSUE TITLE
[Mobile] Home page image caching

### ISSUE THREAD

**Issue by AlicanM** [bounswe/bounswe2022group7#545]
If a post item is returned to the view in the home page, its images are requested again. I will change the structure so that for each post its image will requested only once.

Due Date: 20.12.2022
Reviewer: @canatakan

**Comment by AlicanM** [comment]
[branch](https://github.com/bounswe/bounswe2022group7/tree/dev/android/homepage_image_cache)

**Comment by AlicanM** [comment]
I implemented a new class PostAnImages 
- This class stores the image and the avatar widget of the post
- So when creating new FeedContainer, those datas are used instead of requesting
- [commit](https://github.com/bounswe/bounswe2022group7/commit/acfa5822f7aa26fd14b232cc8a1f718da085a42c)

Created the [PR](https://github.com/bounswe/bounswe2022group7/pull/546), since this implementation solves the issue.
Ready for review @canatakan

**Comment by canatakan** [comment]
I approved your pull request and merged your commits into `develop`. Closing the issue.
