### ISSUE TITLE
[BE] Recommendation Algorithm Implementation for Homepage

### ISSUE THREAD

**Issue by askabderon** [bounswe/bounswe2022group7#550]
Homepage contains all Art Items and Events. We need a recommendation algorithm to modify this page according to satisfy the user expectations.

#### I am going to implement a sorting algorithm based on the structure below:

- If the user is not registered, we are returning a default list, which is based on the popularity of this items.

- If the user is registered, this user's following artists (if any) have priority on the homepage. We are returning these artists' items first (among them popularity is used as sorting again), and then the other items.

#### Popularity

- For events, number of participants is the indicator of the popularity of an event

- For art items, number of likes is the indicator of the popularity of an art item

Deadline: 19/12/22
Reviewer: @sabrimete

**Comment by sabrimete** [comment]
Since the related PR is merged, I'm closing the issue. Thanks for your efforts.
