### ISSUE TITLE
[BE] Update User Level With Actions

### ISSUE THREAD

**Issue by sabrimete** [bounswe/bounswe2022group7#552]
We have user level field for every user. It has not yet implemented properly. @askabderon is assigned to implement it.

- [x] User level should increase with art item creation.
- [x] User level should increase with event creation.
- [x] User level should be returned with profile informations. 

Deadline: 20/12/2022 23.59
Reviewer: @sabrimete

**Comment by askabderon** [comment]
I think we can update the user level when a user creates a discussion topic. In other case, all the users who are not artists would have the same user level, 0.

**Comment by askabderon** [comment]
Also, we can update this issue's difficulty to easy, there are not much things to change for this field.

**Comment by sabrimete** [comment]
> I think we can update the user level when a user creates a discussion topic. In other case, all the users who are not artists would have the same user level, 0.

Makes sense, thanks for the suggestion and the work.

**Comment by sabrimete** [comment]
Since related PR is merged, I'm closing the issue
