### ISSUE TITLE
[BE] Art Item Like Endpoint

### ISSUE THREAD

**Issue by askabderon** [bounswe/bounswe2022group7#553]
Like functionality for art items is going to be implemented similar to the upvote/downvode mechanism for comments. In this case we do not have downvote functionality. There is going to be a simple like button which is going to use for this endpoint. Tapping to the liked item should be remove the liking.

We can use the same endpoint for this. 

- [x] Like the item if it has not been liked.
- [x] Remove the like if it had already liked.

Due Date: 22.12.2022 23.59
Reviewer: @askabderon

**Comment by sabrimete** [comment]
Since they are very similar features, I also implemented the bookmark option in the related PR. But it is for events and art items, not just for art items.

**Comment by askabderon** [comment]
I am closing this issue since the corresponding PR is merged.
