### ISSUE TITLE
[BE] Event Participation Endpoint

### ISSUE THREAD

**Issue by askabderon** [bounswe/bounswe2022group7#554]
Users shall be able to indicate their participation to the events, and event information should also contain the participants information. We need an endpoint for this functionality. The mechanism is going to be similar to the like button, getting this endpoint twice should be remove the user from the participants list. 

- [x] Add the user (should be extracted from token) to the event's participants.
- [x] Remove the user if it had already indicated its participant.
- [x] Be sure about returning the information of the participants for the events (modify the EventDTO if necessary)

Due Date: 22.12.2022 23.59
Reviewer: @demet47

**Comment by CahidArda** [comment]
PR was merged, can we close the issue?

**Comment by demet47** [comment]
I was the reviewer of the related PR. Everything was fine and the PR is merged thus I am closing the issue.
