### ISSUE TITLE
[BE] Report Functionality Endpoint

### ISSUE THREAD

**Issue by askabderon** [bounswe/bounswe2022group7#555]
Ideart. provides copyright system for all the art items that have been uploaded to the platform. In order to protect artists' rights, we are going to provide a report functionality which is going to be used for art items. All the registered users can report an art item with this functionality. Corresponding report entity is going to be created and saved to the database for the checking of admin and future actions if necessary. 

- [x] Implement the report endpoint. 
- [x] Save the corrresponding report entity to the database.

Due Date: 22.12.2022 23.59
Reviewer: @demet47

**Comment by CahidArda** [comment]
It looks like the PR was merged, can we close this issue?

**Comment by demet47** [comment]
I was the reviewer of the related PR. All seems fine. Thus I am closing the issue.
