### ISSUE TITLE
Create mockup for Scenario 2

### ISSUE THREAD

**Issue by erimerkin** [bounswe/bounswe2022group7#56]
For [Scenario 2](https://github.com/bounswe/bounswe2022group7/wiki/Scenario-2) mockups should be created in accordance with action items.

**Deadline:** 21-03-2022 23.59

**Comment by azizamankenova** [comment]
Thanks for your efforts! The mock-ups look great and include everything mentioned in the scenario.

**Comment by erimerkin** [comment]
Since this issue is now completed, I am closing the issue.
