### ISSUE TITLE
[Mobile] Discussion Post Vote Functionality

### ISSUE THREAD

**Issue by AlicanM** [bounswe/bounswe2022group7#562]
I will implement the discussions posts upvote and downvote feature to the mobile app.

- [x] new branch
- [x] connect up/down vote buttons to end points
- [x] connect remove vote end points
- [x] Update discussions page buttons on load
- [x] Update discussion page button on load
- [x] Create PR

Due Date: 20.12.2022
Reviewer: @musasimsekdotdll

**Comment by AlicanM** [comment]
[branch](https://github.com/bounswe/bounswe2022group7/tree/dev/android/votes)

**Comment by AlicanM** [comment]
- implemented end point connections [commit](https://github.com/bounswe/bounswe2022group7/pull/563/commits/e160a427eca395549ee4936ace549f5ff8ffa1ac)

**Comment by AlicanM** [comment]
- For discussions page, i made the vote buttons connection and the load update by creating a state variable named as discussions. [commit](https://github.com/bounswe/bounswe2022group7/pull/563/commits/26ab9c7a85b8148810d13a5d0818fa858a6a7779) 
-  For single discussion page, made the vote buttons connection and the load update by creating a state variable named as currentDiscussion. [commit](https://github.com/bounswe/bounswe2022group7/pull/563/commits/0d32162c1f2fd09cb01ec2b69e65f0b072d598fc)

**Comment by AlicanM** [comment]
Created the [PR](https://github.com/bounswe/bounswe2022group7/pull/563)
Ready for review @musasimsekdotdll

**Comment by musasimsekdotdll** [comment]
I merged your changes, this issue can be closed.
