### ISSUE TITLE
[Mobile] Comment Vote Functionality

### ISSUE THREAD

**Issue by AlicanM** [bounswe/bounswe2022group7#568]
I will implement the comment up/down vote features to the mobile app.

- [x] new branch
- [x] implement the end points connection
- [x] connect buttons to end point
- [x] update the comment vote buttons on load
- [x] create PR

Due Date: 20.12.2022
Reviewer: @musasimsekdotdll

**Comment by AlicanM** [comment]
[branch](https://github.com/bounswe/bounswe2022group7/tree/dev/android/comment_vote)

**Comment by AlicanM** [comment]
- update model for vote and add update status func [commit](https://github.com/bounswe/bounswe2022group7/commit/9d5a0cacbc463b1204ce37450317270661aa691f)
- comment vote end points [commit](https://github.com/bounswe/bounswe2022group7/commit/0f475f7b1d970c94268fdfc564dc1a8c4d037c54)
- currentUser now stores user id [commit](https://github.com/bounswe/bounswe2022group7/commit/41ae6bc84032fb4acfde984b501fc6aa4174c286)
- button connectios [commit](https://github.com/bounswe/bounswe2022group7/commit/7a8f0934683913d64f8eed28bef4e74e1674e6c0)
- update the comment vote buttons on load [commit](https://github.com/bounswe/bounswe2022group7/commit/54f1742789eac850ddac2adaae6f29acf4c958a9)

**Comment by AlicanM** [comment]
Created the [PR](https://github.com/bounswe/bounswe2022group7/pull/569)
Ready for review @musasimsekdotdll

**Comment by musasimsekdotdll** [comment]
I approved the pull request, this issue can be closed now.
