### ISSUE TITLE
[BE] Collaborator Implementation

### ISSUE THREAD

**Issue by askabderon** [bounswe/bounswe2022group7#573]
We have Event entity that can be created by Artist users of our platform. Current initialization of this Event class extracts the creator from the user token and does not take any additional user inputs. However, our requirements specified the collaborator structure for these classes. 

During the last team meeting, we decided to take a list of usernames as a new field. We also add the corresponding artist of the token to the collaborators. I think we can deprecate the creator class and can only have collaborators but I am leaving the decision to the implementor. 

- [x] Modify the existing event endpoint to take username list
- [x] Take this list and store it as a collaborator field of event class
- [ ] Update the creatorAccountInfo field to a list of account info's of collaborators
- [ ] Add the creator to the collaborator list as well and remove the creator field of event (OPTIONAL)

Deadline: 25.12.22
Reviewer: @askabderon

**Comment by sabrimete** [comment]
After discussion with other team members, we decided not to remove creator field.
As a result creator is not a collaborator but collaborators have equal right on the event.

**Comment by CahidArda** [comment]
PR was merged, can we close the issue?

**Comment by askabderon** [comment]
> After discussion with other team members, we decided not to remove creator field. As a result creator is not a collaborator but collaborators have equal right on the event. That's why I didn't check the third and fourth tasks

Thank you about informing me about the update. It seems fine to me. Tagging the issue as completed and closing it. Thanks for working on this!
