### ISSUE TITLE
[Mobile] Implement Backend Connection for Text Annotation

### ISSUE THREAD

**Issue by atillaturkmen** [bounswe/bounswe2022group7#576]
I was assigned to implement the backend connection for text annotations in our group meeting during this week's lab session.

These are the tasks to complete this issue:
- [x] Create a new branch.
- [x] Implement receiving all text annotations for a page.
- [x] Show text annotations on the page.
- [x] Send new annotations to the backend.

**Deadline: 27/12/2022 11:00**
**Reviewer: @canatakan**

**Comment by atillaturkmen** [comment]
Here is an example text annotation from our app that conforms to [web annotation data model](https://www.w3.org/TR/annotation-model/):
```
{
    "_id": "63aa3a18f6b64fb7e78bb5f4",
    "@context": "http://www.w3.org/ns/anno.jsonld",
    "type": "Annotation",
    "creator": "https://ideart.tk/profile/stevecarell",
    "body": [
        {
            "type": "TextualBody",
            "value": "example annotation body",
            "purpose": "commenting"
        }
    ],
    "target": {
        "source": "https://ideart.tk/artitem/111",
        "selector": {
            "type": "TextPositionSelector",
            "start": 3,
            "end": 16
        }
    },
    "id": "c_#0b08cce4-e368-4a41-b29f-702f4261ca93"
}
```

**Comment by atillaturkmen** [comment]
I have created a pull request and added @canatakan as the reviewer.
https://github.com/bounswe/bounswe2022group7/pull/622

**Comment by canatakan** [comment]
After your updates according to the requested changes, I merged your pull request. This issue can be closed.
