### ISSUE TITLE
[Mobile] Profile Page Revision

### ISSUE THREAD

**Issue by musasimsekdotdll** [bounswe/bounswe2022group7#577]
I was assigned to update profile page according to the second milestone review and backend changes. In order to complete this task,

- [x] In the activity part, profile photos should be replaced by images of the posts.
- [x] User levels should be displayed.
- [x] New activity types should be displayed(like collaborated event)
- [x] Verified users should have a sign showing that they are verified.

Deadline: 25.12.2022 17.00
Reviewer: @canatakan

**Comment by musasimsekdotdll** [comment]
I have created a [branch](https://github.com/bounswe/bounswe2022group7/tree/dev/android/profile-page-revision).

**Comment by musasimsekdotdll** [comment]
From now on, a preview of the image of the post is shown in the profile page instead of profile picture of the user.

Here is how art items of another user looks like:
<img src = "https://user-images.githubusercontent.com/74203551/209424549-abede956-e7b6-4cfd-a3b0-488660937943.jpg" width="350" height="600">

Here is  how events of current user looks like:
<img src="https://user-images.githubusercontent.com/74203551/209424558-5e29920d-ed00-4c8d-a94b-1d5009061372.jpg" width="350" height="600">

**Comment by musasimsekdotdll** [comment]
The level of the user is shown under his/her username.


Here is how the profile page of another user looks like:
<img src="https://user-images.githubusercontent.com/74203551/209425890-df440c9a-6324-4132-b18d-f36cd9f36a5c.jpg" width="350" height="600">


Here is how the profile page of the current user looks like:
<img src="https://user-images.githubusercontent.com/74203551/209425931-aae4240b-4b4c-4092-a940-a7b3347263c1.jpg" width="350" height="600">



[commit of these changes](https://github.com/bounswe/bounswe2022group7/commit/ddd5335e6fe7dd66a294c4fe43a4d9671353627e)

**Comment by musasimsekdotdll** [comment]
An icon showing that the user is verified is added to the profile page.


Here is how the profile page of a verified user looks like:
<img src="https://user-images.githubusercontent.com/74203551/209426558-e518e6f7-cc59-450c-a4b1-50978a07ae3a.jpg" height="600" width="350">


Here is how the profile page of the current user looks like if s/he is verified:
<img src="https://user-images.githubusercontent.com/74203551/209426599-3b05b1ad-9695-40d3-9e12-b64dc8c6dfeb.jpg" width="350" height="600">


[commit for these changes](https://github.com/bounswe/bounswe2022group7/commit/ddd5335e6fe7dd66a294c4fe43a4d9671353627e)

**Comment by musasimsekdotdll** [comment]
After the discussion with the team, we decided that:

- collaborated events will be shown as a created event
- user comments will not be shown in the profile page
- there will not be any other post type that will be included in the dropdown button


Based on the decisions above, profile page is updated.


Here is how profile page of another user looks like:
<img src="https://user-images.githubusercontent.com/74203551/209428250-244de44b-1ca5-40d0-87ff-5d39215e4428.jpg" width="350" height="600">


Here is how profile page of current user looks like:
<img src="https://user-images.githubusercontent.com/74203551/209428291-829828df-5b24-4517-9cf4-47f7aa94eef5.jpg" width="350" height="600">


[commits for these changes](https://github.com/bounswe/bounswe2022group7/commit/71167a2804f3b0e47350980990d1febee92503d9)

**Comment by musasimsekdotdll** [comment]
All features implemented, a [pull request](https://github.com/bounswe/bounswe2022group7/pull/578) is created and the branch is ready to be merged.

**Comment by canatakan** [comment]
Your pull request was merged into `develop` days ago; thus, this issue has been completed. I am closing it.
