### ISSUE TITLE
Update acceptance criteria of the scenarios

### ISSUE THREAD

**Issue by guneyizol** [bounswe/bounswe2022group7#58]
Since the [requirements draft](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)) has been modified, the mentioned requirements in the acceptance criteria section of the [creating event scenario](https://github.com/bounswe/bounswe2022group7/wiki/Scenario-1:-Creating-Events) are no longer valid and therefore need updating.

**Comment by CahidArda** [comment]
After the [meeting #4](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%234), the task of updating the acceptence criteria of the scenarios has been reassigned to @CahidArda and @AlicanM (as the reviewee). Therefore, this issue has been rewritten to include all 3 scenarios and it has been reassigned.

Scenarios to update:
- [ ] [Scenario 1: Creating Events](https://github.com/bounswe/bounswe2022group7/wiki/Scenario-1:-Creating-Events)
- [ ] [Scenario 2: Semantic Search and Discussion](https://github.com/bounswe/bounswe2022group7/wiki/Scenario-2)
- [ ] [Scenario 3: Copyright Infringement Report](https://github.com/bounswe/bounswe2022group7/wiki/Scenario-3:-Copyright-Infringement-Report)

Deadline: 2022-04-01, 19:55
Reviewer: @AlicanM

**Comment by CahidArda** [comment]
Scenario 1 and 3 are updated. While looking at scenario 2, I observed two things:
1) We need to clarify what the home page will include and update the requirements and the scenario 2 accordingly.
2) We may need to add a registered user section to the user requirements to include requirements such as ability to share items.

Before working on the second scenario, I will wait for the first point above to get clarified.

**Comment by CahidArda** [comment]
During the (meeting 6)[https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%236], we handled a lot of the missing requirements. Then this issue was reassigned on the (meeting 8)[https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%238]

Deadline: 12-05-2022, 17.00
Reviewee: @AlicanM

**Comment by CahidArda** [comment]
While looking at the acceptance criteria of the [scenario 2](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)) which is about semantic search, I saw that the last action item is about payment. We concluded in the [customer meeting](https://github.com/bounswe/bounswe2022group7/wiki/Customer-Meeting-Report) that the platform wouldn't include a way of performing payments. This issue will be brought up to my teammates in the next meeting.

**Comment by CahidArda** [comment]
An effort to update the requirements, use cases, class diagrams related to the searching and filtering is underway. Progress can be seen in #79. As part of this effort, requirements were updated. Therefore an item is added to the acceptance criterria of [scenario 2](https://github.com/bounswe/bounswe2022group7/wiki/Scenario-2):
> 1.1.14.1: Guest and registered users shall be able to use the search bar to semantically search for exhibitions, art items, users, posts on the discussion forum.

The updates were reviewed by the team during the [meeting 9](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%239). Closing the issue.
