### ISSUE TITLE
[Frontend] Art Item Auction 

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#583]
We will add art item auction support to our platform. In order for this to happen, we need to include the following functionalities:
- [x] (Owner) Artist shall be able to start an auction. This will be done on the art item page. There will be a button next to the auction status information. Only shown to the owner artist.
- [x] Users shall be able to make bids for the art item. This will again be on the art item page.
- [x] (Owner) Artist shall be able to stop the auction.

Deadline 24.12.2022, 23:59
Reviewer: @erimerkin

**Comment by CahidArda** [comment]
I have finished the auction implementation. Here is how it works:

State space of the display is 2x2, dimensions being `on_auction` and `max_bid` (whether any bid was made). There are 2x2=4 different states.

### State 1: Initial State (not on auction, no bid)

User creates and art item and views the page:

![image](https://user-images.githubusercontent.com/57228345/209447723-f884a580-3ca7-4d66-8dc4-7a3d1d8fa061.png)

Users other than the owner doesn't see the new auction display at all.

### State 2: Auction Starts

Owner clicks the start auction button and auction starts:

![image](https://user-images.githubusercontent.com/57228345/209447754-6e3f6992-e316-4c1a-bfb4-a6c52c463bcc.png)

Other users:

![image](https://user-images.githubusercontent.com/57228345/209447770-e38c65f5-b788-4d93-8d04-9b281dec2887.png)

Visitor users:

![image](https://user-images.githubusercontent.com/57228345/209447783-182bf3d5-ccbe-44a0-9029-978a90b037b4.png)

### State 3: First Bid Made

Steve enters a bid amount and makes the bid. Owner:

![image](https://user-images.githubusercontent.com/57228345/209447832-94a49bb8-a2b4-4d53-abf1-1f8dba9027f1.png)

Steve:

![image](https://user-images.githubusercontent.com/57228345/209447837-ed433d9a-79cf-4275-bef8-0763b73abb91.png)

Visitor users:

![image](https://user-images.githubusercontent.com/57228345/209447844-a85e7477-d985-4dff-81ac-38a32c01c806.png)

### State 4: Auction ends

Owner clicks end auction button to end the auction. He can restart the auction if he wants.

![image](https://user-images.githubusercontent.com/57228345/209447860-85792e62-d3eb-4790-89a3-02fd1863cd82.png)

Steve and visitor users:

![image](https://user-images.githubusercontent.com/57228345/209447875-3a379423-d615-41a0-8c53-62e79a1a6a59.png)

**Comment by erimerkin** [comment]
The related PR #585 is now merged to `develop` so this issue is now completed.
