### ISSUE TITLE
Prepare and add customer interview notes

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#59]
This week, we had our customer interview with our TA. I was the note taker during the meeting and noted down the key points in our TA's answers.

I will add the answers to the customer interview questions document and upload it in our repository so that we can check them and keep working on our requirements accordingly.

**Comment by canatakan** [comment]
I firstly added the project description analysis and possible customer questions document that is shared by @CahidArda via Slack, with minor alterations. Our additional questions are also added to this document. 

The customer meeting notes will be explanatory for these questions as we have covered most of these points in the meeting.

The relevant page can be found [here](https://github.com/bounswe/bounswe2022group7/wiki/Project-Analysis-and-Possible-Customer-Questions).

**Comment by canatakan** [comment]
Customer Meeting Report is now completed and it is pending review. All the other attending members are encouraged to add any points that are missed by me to the report.

The report can be found [here](https://github.com/bounswe/bounswe2022group7/wiki/Customer-Meeting-Report).

**Comment by azizamankenova** [comment]
I have read the report, it looks great! Thanks for the effort!

**Comment by CahidArda** [comment]
I think the [customer meeting](https://github.com/bounswe/bounswe2022group7/wiki/Customer-Meeting-Report) report looks good. It lists all the questions we asked brief summaries of the answers we received.
