### ISSUE TITLE
[Mobile] Search Functionality

### ISSUE THREAD

**Issue by musasimsekdotdll** [bounswe/bounswe2022group7#593]
As discussed in the mobile meeting, I was assigned to implement search functionaliy. In order to do that, I have to

- [x] implement backend integration
- [x] implement UI part of the search

Deadline: 25.12.2022 00.00
Reviewer: @atillaturkmen

**Comment by musasimsekdotdll** [comment]
[branch](https://github.com/bounswe/bounswe2022group7/tree/dev/backend/search) created.

**Comment by musasimsekdotdll** [comment]
backend integration completed. you can view changes on [this commit](https://github.com/bounswe/bounswe2022group7/commit/6b92b1ada3289009ee043cf43b5d8749cf8d6b04).

**Comment by musasimsekdotdll** [comment]
search feature is completed with [the latest commit](https://github.com/bounswe/bounswe2022group7/commit/f3695f8f4d46dd5277cc7f214d13c72ed76a57bf). I will share some screenshots  from the app below. The basics of the search page are:

- users can search 5 types of data: physical exhibition, online gallery, art item, discussion post, another user.
- users will type keywords into the search bar located at the top of the screen and select the data type s/he wants to see.
- depending on the selected data type, the layout will change: events and art items will be displayed in a grid view while users and discussion posts are shown row by row.
- all data listed in search page have actual links of that data, which means if you are interested one of the art items in the search page, you can see its page by tapping on the image.


### screenshots from app

- This is the home page of the application:
    <img src="https://user-images.githubusercontent.com/74203551/209584209-8f27301e-99f5-4572-a69f-882ac877e286.jpg" width="350" height="400">
- If user taps the search icon, search page will be brought:
    <img src="https://user-images.githubusercontent.com/74203551/209584410-da499bd5-44bc-4399-ac30-942a76750fd7.jpg" width="350" height="600">
- user can select the data type from dropdown menu:
    <img src="https://user-images.githubusercontent.com/74203551/209584497-eb0bfa9f-5493-4c82-beb2-6285a45470fa.jpg" width="350" height="600">
- after selecting data type, user can type keywords and see the results of the search:
    - physical exhibition:
        <img src="https://user-images.githubusercontent.com/74203551/209584616-4889f253-6c77-4fc5-a876-fae1416aec77.jpg" width="350" height="600">
        <img src="https://user-images.githubusercontent.com/74203551/209584628-3bd9ac5c-a0a8-414b-a406-d9e63e8d726d.jpg" width="350" height="600">

    - user:
        <img src="https://user-images.githubusercontent.com/74203551/209584685-42ba32d3-8eb9-4a4c-99dc-f61c823ff4cd.jpg" width="350" height="600">
        <img src="https://user-images.githubusercontent.com/74203551/209584687-3d46eb47-f8a4-404e-98e3-30bfeb29eab4.jpg" width="350" height="600">

    - discussion post:
        <img src="https://user-images.githubusercontent.com/74203551/209584745-019441ac-0aa2-4f98-9595-6832bb059e03.jpg" width="350" height="600">
        <img src="https://user-images.githubusercontent.com/74203551/209584751-ef2f69a4-fd5b-423b-abb5-25d49641d40e.jpg" width="350" height="600">

    - art item:
        <img src="https://user-images.githubusercontent.com/74203551/209584775-ca29e43a-a59f-45da-9232-654e4b106c81.jpg" width="350" height="600">
        <img src="https://user-images.githubusercontent.com/74203551/209584779-5a38e1f8-1926-409c-87ae-d30b235f0279.jpg" width="350" height="600">

    - online gallery:
        <img src="https://user-images.githubusercontent.com/74203551/209584828-7b269fd8-cc69-43b9-b2d7-cc46eefc3b2e.jpg" width="350" height="600">
        <img src="https://user-images.githubusercontent.com/74203551/209584832-c486785f-d162-4bfc-be1c-7c006f6da7f4.jpg" width="350" height="600">

**Comment by canatakan** [comment]
I approved your pull request and merged it. This issue has been completed, closing it.
