### ISSUE TITLE
[Mobile] Art Item Auction

### ISSUE THREAD

**Issue by atillaturkmen** [bounswe/bounswe2022group7#599]
I was assigned to implement the art item auction support to our app in our group meeting during this week's lab session.

These are the tasks to complete this issue:
- [x] Create a new branch.
- [x] Add a button for starting an auction that is only visible to the owner of the art item.
- [x] Other users will be able to make bids for the art item.
- [x] Artist will be able to stop the auction.

**Deadline: 27/12/2022 11:00**
**Reviewer: @canatakan**

**Comment by atillaturkmen** [comment]
All of the tasks are complete. Here are example screenshots:

![Screenshot (203)](https://user-images.githubusercontent.com/59166549/209587332-72936e56-14e7-49fd-bb09-31bc649bc772.png)
![Screenshot (204)](https://user-images.githubusercontent.com/59166549/209587334-35eeea89-ca20-452e-8e06-f2912b5c048f.png)
![Screenshot (201)](https://user-images.githubusercontent.com/59166549/209587335-d9233734-913d-42a2-afa1-beb66e7c2b51.png)

Now I will open a pull request and add @canatakan as the reviewer.

**Comment by canatakan** [comment]
* I approved and merged your pull request #620.
* Please check [my review](https://github.com/bounswe/bounswe2022group7/pull/620#pullrequestreview-1230252954) for a feature request

Currently, the task is completed and the issue can be closed.
