### ISSUE TITLE
[Frontend] Implement a distiction between recommended and general homepage feed

### ISSUE THREAD

**Issue by erimerkin** [bounswe/bounswe2022group7#613]
As we have a recommended selection and generic homepage feed, we need to create a distinction between these for user. So that user can see both of these selections by selecting one of them. Recommended will be default for a signed up user while if user is not signed in the generic feed will be shown.

**Deadline: 2022-12-27, 10:00**
**Reviewer: @CahidArda**

**Comment by CahidArda** [comment]
Changes were approved in the PR. Thanks for the work!

Closing the issue.
