### ISSUE TITLE
[FE] Display following users on profile page

### ISSUE THREAD

**Issue by ENESAYDOGDUOGLU** [bounswe/bounswe2022group7#625]
When the following button on the profile page is clicked, the list of followed users should be displayed.

**Comment by ENESAYDOGDUOGLU** [comment]
I created [this PR](https://github.com/bounswe/bounswe2022group7/pull/624) .

When you click the following button on the profile page, the users that the person follows are listed.

<img width="427" alt="Screen Shot 2022-05-20 at 10 45 15" src="https://user-images.githubusercontent.com/56451956/209624746-24143425-f50c-41b2-8ad3-b19af02f74ef.PNG">

**Comment by erimerkin** [comment]
As the PR #624 is merged, this issue is now completed.
