### ISSUE TITLE
[Mobile] Update and Fix some minor issues

### ISSUE THREAD

**Issue by AlicanM** [bounswe/bounswe2022group7#630]
I will update the event information table and remove the unused buttons.

- [x] update event page
- [x] remove unused buttons

Due Date: 27.12.2022
Reviewer: @canatakan

**Comment by AlicanM** [comment]
Created the [PR](https://github.com/bounswe/bounswe2022group7/pull/629)

**Comment by canatakan** [comment]
I have just merged your pull request after contribution a couple of changes. This issue can be closed now.
