### ISSUE TITLE
[Mobile] Bidding Network

### ISSUE THREAD

**Issue by musasimsekdotdll** [bounswe/bounswe2022group7#633]
I was assigned to integrate backend side of the bidding mechanism.

Reviewer: @canatakan

**Comment by musasimsekdotdll** [comment]
[changes regarding this issue](https://github.com/bounswe/bounswe2022group7/commit/d82dee03995ae77d797f05dbe29cdc06c2db6865)

**Comment by canatakan** [comment]
* I have just merged your pull request #632 
* The task has been completed, I am closing the issue.
