### ISSUE TITLE
Update the requirement elements related to the customer's answer for Q5

### ISSUE THREAD

**Issue by guneyizol** [bounswe/bounswe2022group7#64]
Update the [requirements](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)) according to the answer of the [customer question 5](https://github.com/bounswe/bounswe2022group7/wiki/Customer-Meeting-Report). 

Deadline: 01.04.2022 19:59

The updated requirements will be reviewed by @AlicanM

**Comment by guneyizol** [comment]
The definitions of artistic value, offline exhibitions,  online galleries, and verified account are added to the glossary.
User requirement for account verification is updated. (1.1.7)
System requirement for account verification is updated (1.2.5)

**Comment by AlicanM** [comment]
I think factors that affect the artistic value calculations, should be added as a new system requirement or under existing requirements. Other than that it looks good.

**Comment by guneyizol** [comment]
I will add it as a system requirement because according to the answer given to Q5 artistic values are not used for a single functionality.

**Comment by AlicanM** [comment]
Looks good, thank you!
