### ISSUE TITLE
Update the requirement elements related to the customer's answer for Q3

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#65]
Update the [requirements](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)) according to the answer of the [customer question 3](https://github.com/bounswe/bounswe2022group7/wiki/Customer-Meeting-Report). 

Deadline: 01.04.2022 19:59

The updated requirements will be reviewed by @HasanBingolbali

**Comment by demet47** [comment]
* I modified 1.2.1.4 such that a user's level info is invisible to other users. **This feature can be changed as *visible to everyone* depending on our choice**.
* I added 1.2.1.6 which is about enabling or disabling user activities according to level infos.

**Comment by HasanBingolbali** [comment]
Everything seems fine
