### ISSUE TITLE
Complete the glossary in requirements page

### ISSUE THREAD

**Issue by atillaturkmen** [bounswe/bounswe2022group7#66]
Add more items to glossary in [requirements page](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)).

**Comment by atillaturkmen** [comment]
Added interaction level, popularity level and user level to glossary. Awaiting review from Rafet Oğuz Pançuk.

**Comment by oguzpancuk** [comment]
Reviewed, found nothing to change.
