### ISSUE TITLE
Update elements in requirements draft related to customer's answer to Question 4

### ISSUE THREAD

**Issue by erimerkin** [bounswe/bounswe2022group7#67]
[Requirements Draft](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)) needs review and modifications according to answers given in [Customer Meeting](https://github.com/bounswe/bounswe2022group7/wiki/Customer-Meeting-Report). I am tasked with checking the compatibility of requirements and making the necessary modifications related to Q4 in [Meeting #4](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%234).

Question 4 and its answers can be found in [Customer Meeting Report](https://github.com/bounswe/bounswe2022group7/wiki/Customer-Meeting-Report).

**Deadline: 2022-04-01, 19:55**
**Reviewer: @guneyizol**

**Comment by guneyizol** [comment]
Seems ok to me. But the phrase "discussion forum" is still used under 1.1.4 and 1.2.2. Was this intentional?

**Comment by CahidArda** [comment]
I think we still need a discussion forum.

Each exhibition and art item will have it's own comment section where users can comment about that particular exhibition or art item.

In addition to these comment sections, I believe the platform will include a discussion forum. [The project description](https://github.com/bounswe/bounswe2022group7/wiki/Project-Analysis-and-Possible-Customer-Questions) includes the following sentence:
> In discussion forums, people discuss about art.

As far as I understand, this forum can include discussions about exhibitions, art items or anything related to art. I believe the platform still needs to include a discussion forum.

**Comment by erimerkin** [comment]
> Seems ok to me. But the phrase "discussion forum" is still used under 1.1.4 and 1.2.2. Was this intentional?

I wasn't sure about discussion part so I half baked these changes. 

> I think we still need a discussion forum.
> 
> Each exhibition and art item will have it's own comment section where users can comment about that particular exhibition or art item.
> 
> In addition to these comment sections, I believe the platform will include a discussion forum. [The project description](https://github.com/bounswe/bounswe2022group7/wiki/Project-Analysis-and-Possible-Customer-Questions) includes the following sentence:
> 
> > In discussion forums, people discuss about art.
> 
> As far as I understand, this forum can include discussions about exhibitions, art items or anything related to art. I believe the platform still needs to include a discussion forum.

If that is the case, should we create another requirement topic for Comments or should we merge it with Discussion Forum under Discussions?

**Comment by erimerkin** [comment]
I have made some small changes to requirements.

- Requirement 1.1.4.3 is removed since it may overlap with other requirements. All other requirements' indexes for 1.1.4.x, x > 3 are decreased by 1 
-  Requirement 1.1.4.4(new index of 1.1.4.3): Removed the note inside the brackets(optionality)

Sorry to bother again @guneyizol, can you review these [changes](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)/2008bab959e2d52f6dff272c82f27756ab0d81ef) when you are available.

**Comment by guneyizol** [comment]
> (Needs clarification: how will the semantic search work)
This part under 1.2.2 is unnecessary in my opinion because how some feature works is not really relevant for the requirements.
Other than this everything seems fine 👍

**Comment by erimerkin** [comment]
> > (Needs clarification: how will the semantic search work)
> 
> This part under 1.2.2 is unnecessary in my opinion because how some feature works is not really relevant for the requirements. Other than this everything seems fine 👍

I wasn't responsible for that part but I think you are right. We can delete that part.
