### ISSUE TITLE
Updating the table of contents of the requirements 

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#68]
It was decided on the [meeting #4](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%234) that we will update the index of the requirements. The way they will be updated is explained below.

Each item in the index shall be a hyperlink. When clicked, it should show the relevant section from the requirements list.

An example of the desired behaviour can be seen in the [requirements of group 1 from 2020](https://github.com/bounswe/bounswe2020group1/wiki/Requirements#117-List-of-Favorite-Products).

Deadline: 2022-04-01, 19:55
Reviewer: @CahidArda

**Comment by AlicanM** [comment]
An anchorlink is added to each element of the table of content in [the requirements page](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft))

**Comment by CahidArda** [comment]
Looks great, thanks!
