### ISSUE TITLE
Updating the README file

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#7]
The main [README file](https://github.com/bounswe/bounswe2022group7/blob/master/README.md) needs to be updated. It should include the following:
- A description of what wer are doing.
- Link to the wiki
- Links to the personal pages of team members

**Comment by erimerkin** [comment]
Created a [pull request](#13) for updated README.md, assigned @oguzpancuk as reviewer before merging codebases.

**Comment by canatakan** [comment]
> Created a pull request (#13) for updated README.md, assigned @oguzpancuk as reviewer before merging codebases.

I have also reviewed the relevant pull request, the changes look great for now. My review can be found [here](https://github.com/bounswe/bounswe2022group7/pull/13#pullrequestreview-901046014) as well.
