### ISSUE TITLE
[Mockup] Update the mockups according to TA's feedback and updated requirements

### ISSUE THREAD

**Issue by erimerkin** [bounswe/bounswe2022group7#72]
In [Meeting #4](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%234), updating the mockups according to TA's feedback, revised requirements and scenarios were assigned to previous mockup team. Since progress in this issue is dependent on #58 and updated requirements, deadline was pushed to a new date.

We need to update the mockups according to TA's feedback, which are:

- Clearly matching actions and mockups (maybe we can use action numbers for each)
- Clearly indicating the action being done in corresponding steps(marking when a user presses to a button)
- Reviewing and updating the mockups for updated requirements and scenarios as a result of [Customer Meeting]()

Progress of scenarios:

- [x] Reviewing and updating mockups for [Scenario 1](https://github.com/bounswe/bounswe2022group7/wiki/Scenario-1:-Creating-Events)
- [x] Reviewing and updating mockups for [Scenario 2](https://github.com/bounswe/bounswe2022group7/wiki/Scenario-2)
- [x] #125

**Updated mock-ups will be reviewed by groups responsible for creating the scenarios.**

**Deadline: 2022-04-12, 17.00**

**Comment by CahidArda** [comment]
Mockups of scenario 2 are updated to highlight the cursor. Revision is available [here](https://github.com/bounswe/bounswe2022group7/wiki/Scenario-2/63b137327bc6c07ff6dc23ec583dfbce5454d132).

**Comment by erimerkin** [comment]
We have changed responsibilities between previous Mock-up creators and scenario creators, in which @erimerkin @musasimsekdotdll  and @mehmeteminipekdal will work on scenarios and @CahidArda @canatakan @azizamankenova will work on to update mockups.

**Comment by azizamankenova** [comment]
Mockups of scenario 1 are also updated with the highlighted cursor. The changes can be seen in [Scenario 1](https://github.com/bounswe/bounswe2022group7/wiki/Scenario-1:-Creating-Events).

**Comment by canatakan** [comment]
With the completion of #125, all subtasks are now completed and all of the mock-ups are at their final version right now. Thus, the main task is completed and the issue can be safely closed.
