### ISSUE TITLE
[Use Case Diagram] Adding Search and Filtering

### ISSUE THREAD

**Issue by musasimsekdotdll** [bounswe/bounswe2022group7#79]
I could not have found so much information about the searching and filtering. I made some edits in the diagram, however. 

What you say, @CahidArda?

**Comment by canatakan** [comment]
Could you please clarify what this issue is about? Is this about the user scenarios or the use case diagram?

**Comment by musasimsekdotdll** [comment]
I have updated the header, sorry for inconvenience.

**Comment by musasimsekdotdll** [comment]
We have finished the Use Case Diagram, I am closing this issue.

**Comment by CahidArda** [comment]
During the PS meeting on 5.4.2022, we also talked about how searching and filtering can be represented in the Use Case Diagram. TA made the following suggestions:
- Consider two types of searching: basic search and semantic search. With basic search, system will not rely on any semantics and it will basically show any content that includes the words in the query. TA suggested that we can view basic search as filtering and view the semantic search as an extension of basic search. I believe this approach doesn't fit with the way we had imagined the filtering would work. We can discuss this in the next meeting.
- We currently don't cover every search use case. We only allow searching exhibitions and discussion threads. No users, artitems. We should cover all.

**Comment by CahidArda** [comment]
Fixing the search and filtering was reassigned in the [meeting 9](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%239).

Following tasks need to be carried out:
- [ ] Add a search section (1.1.14) to the [requirements](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)). Transfer all the search related requirements scattered across the document to this single requirement.
- [ ] Update the use case diagram according to the new requirements
- [ ] Class diagram shall be updated to cover the new format of the search & filter.

**Comment by CahidArda** [comment]
Requirements about search and filtering are transfered to their own sections. Revision can be seen [here](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)/_compare/2b02b47bad2f5269ed42dafd956e19d44ecadb0e...c1fb398436bf813393feb57dfc9272d66fdf8c3e).

Next, we need to update the use case diagram.

**Comment by CahidArda** [comment]
Use Case Diagram satisfies the requirements. Pending review.

**Comment by CahidArda** [comment]
Changes were reviewed during meeting 10. Closing the issue.
