### ISSUE TITLE
Update the requirement elements related to the customer's answer for Q7

### ISSUE THREAD

**Issue by mehmeteminipekdal** [bounswe/bounswe2022group7#80]
[Requirements Draft](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)) should be modified according to the answers given in [Customer Meeting Report](https://github.com/bounswe/bounswe2022group7/wiki/Customer-Meeting-Report) and I am responsible for question 7 in that report as decided in [Meeting #4](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%234):

> Q7: Can the artist end the bidding by withdrawing the item and not selling it at all?

Deadline: 2022-04-01, 19:59
Reviewer: @azizamankenova

**Comment by mehmeteminipekdal** [comment]
I have updated 1.1.8.4 in [Requirements Page](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)):

> * 1.1.8.4: Artists shall not end the bidding by withdrawing the item and not selling it at all.

**Comment by azizamankenova** [comment]
The new requirement seems okay, thanks! 👍🏻
