### ISSUE TITLE
Review the final version of the Use Case Diagram

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#85]
After completion of individual tasks on the Use Case Diagram and discussions at [Meeting 6](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%236), it was decided that we divide into two groups for completing the diagram. 

The first group, 
* combined a couple of use cases that are drawn by different members previously 
* drew all the other necessary use cases 
*  finalized the format of the diagram.

The second group's task is to:
1. Review the final version of the diagram
2. Add missing use cases
3. Correct possible mistakes in the available uses cases

The assignment of the groups can be found in [Meeting Notes #6](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%236).

**Comment by canatakan** [comment]
The use case for changing password is added. 

This use case includes:
* Getting an email verification code
* Setting the new password

Necessary conditions are also included in the diagram.

**Comment by erimerkin** [comment]
I have found some missing features added them to the diagram:

1. Added usecase of editing and removing forum threads by author
2. Added usecase of editing and removing thread replies by author 
3. Added editing of profile page for owner of the page.
   - Edit profile photo
   - Edit Name, Surname
   - Edit Location
   - I also thought about adding "Edit username" but not so sure about that. Should usernames be modifiable by the user?  

We can also include viewing bids by user, viewing verification status and followers to interacting with profile use case.

**Comment by canatakan** [comment]
Changed `<<includes>>` and `<<extends>>` to `<<include>>` and `<<extend>>`, respectively.

**Comment by erimerkin** [comment]
I have also now added **editing and removing use cases for comments made by user**(user should be the author) to diagram. 


> I have found some missing features added them to the diagram:
> 
>     1. Added usecase of editing and removing forum threads by author
> 
>     2. Added usecase of editing and removing thread replies by author
> 
>     3. Added editing of profile page for owner of the page.
>        
>        * Edit profile photo
>        * Edit Name, Surname
>        * Edit Location
>        * I also thought about adding "Edit username" but not so sure about that. Should usernames be modifiable by the user?
> 
> 
> We can also include viewing bids by user, viewing verification status and followers to interacting with profile use case.

Can anyone review the changes, I am not so sure whether should i use `<<include>>` or `<<extend>>` in 3rd change.

**Comment by azizamankenova** [comment]
Hi @erimerkin, about the 3rd item, I think it should be `<<include>>`. Also, I guess we decided that usernames should also be modifiable by the user.

Also, added the "log out" use case to the diagram.

**Comment by erimerkin** [comment]
> Hi @erimerkin, about the 3rd item, I think it should be `<<include>>`. Also, I guess we decided that usernames should also be modifiable by the user.
> 
> Also, added the "log out" use case to the diagram.

Thanks, @azizamankenova. I have modified 3rd item, `<<extend>>` is now changed to `<<include>>` in necessary places.

**Comment by demet47** [comment]
Moved "Login" node to Guest user and "Change Password" was added to visitor user. Latter also was added to Guest with differing prerequisites.
