### ISSUE TITLE
[UML Class Diagram] Complete "Artist" and "ArtItem" classes 

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#87]
As mentioned in this [comment](https://github.com/bounswe/bounswe2022group7/issues/86#issuecomment-1087586808), we shall complete the "Artist" and "ArtItem" classes.

The "Artist" class needs to have additional features over the "RegisteredUser" class. Some of these privileged actions are:
- Starting an auction
- Hosting an online gallery
- Creating an offline exhibition

Also, note that the "Artist" class shall inherit the "RegisteredUser" as can be seen in the template. These are the very first points to consider while designing these classes.

**Deadline: 05/04/2022, 13.00**

**Comment by guneyizol** [comment]
Added accessor methods to the ArtItem, Artist, and other related smaller classes.
Added composition relationships between ArtItem and other relevant classes.

You might want to review ArtItem, Artist, ArtItemInfo and Comment classes and try to find missing features and relationships between them and other classes.

**Comment by canatakan** [comment]
Thank you for your work. I think the CommentSection class is excellent since it will be also connected to Exhibition and OnlineGallery classes.

I am not sure about all the composition relationships though, but we are going to check the big picture at the end anyway. I will add the things that I come up with.

**Comment by guneyizol** [comment]
> Thank you for your work. I think the CommentSection class is excellent since it will be also connected to Exhibition and OnlineGallery classes.

I wasn't the one added that CommentSection class but anyways 😄 👍. Thank you for your work, too.

**Comment by canatakan** [comment]
We have reviewed the relevant classes during [Meeting 7](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%237), and there were no additional tasks to be done. 

We can monitor the final version of the Class Diagram so that we can see whether these 2 classes need any change or not. Apart from that, the task here is done and the issue can be safely closed.
