### ISSUE TITLE
[Software Design] Complete "Admin" Sections

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#89]
The class for Admin needs to be completed on the UML Class Diagram. The admin class shall cover the use cases shown in the [use case diagram](https://github.com/bounswe/bounswe2022group7/wiki/Use-Case-Diagram). It shall include:
- [x] Banning a user
- [x] Removing a comment
- [ ] ~Removing a thread from the discussion forum~
- [ ] ~Removing a reply from a thread on the discussion forum~
- [x] Handling copyright infringement reports

Update: Discussion forum related tasks are removed after the discussion forum and comments were merged under a single class.

**Comment by CahidArda** [comment]
To handle these cases, I added a new class for handling copyright infringements:
![image](https://user-images.githubusercontent.com/57228345/161625046-0aba6dea-c423-4a94-9d15-c3935ed97c6c.png)

Then I worked on finalizing the admin user class:
![image](https://user-images.githubusercontent.com/57228345/161625531-41a016e5-08f5-46d6-aa7e-4e055f4a0d1e.png)

We currently don't have classes related to a discussion forum. This issue will be brought up in the next team meeting.

**Comment by canatakan** [comment]
I added boolean return values for some of the methods with no return value since for every method, we can have a return value demonstrating whether the process was successful or not.

Also, yes, we currently do not have classes related to the forum; however, creating and completing the ForumPage and all the other related classes were already assigned to @AlicanM and @oguzpancuk. You can see the assignments [here](https://github.com/bounswe/bounswe2022group7/issues/86#issuecomment-1087586808).

**Comment by CahidArda** [comment]
Thanks for the information.

Then I will wait for ForumPage class to be created and then I will add the methods related to the admin.

**Comment by CahidArda** [comment]
An issue was created #91 about adding classes related to forum page. The changes are currently awaiting review.

**Comment by CahidArda** [comment]
In an effort to imrpove the cohesiveness of our software design documents, I will be reviewing the admin related sections. First, I have added an Admin section to the requirements:
> ### 1.1.15 Admin User
> * 1.1.15.1: Admin user shall be able to view the copyright infringement reports.
> * 1.1.15.2: Admin user shall be able to accept or reject a copyright infringement report. When the report is accepted, the art item will be removed.

It may not be complete yet. Next I will:
- [ ] Review the use case diagram and update the use cases
- [ ] Review the class diagram and make sure that the use cases are being covered
- [ ] Update the related sequence diagrams

**Comment by CahidArda** [comment]
All subtasks related to handling the Admin class are completed. Pending group review during the meeting.

**Comment by CahidArda** [comment]
Changes were reviewed during meeting 10. Closing the issue.
