### ISSUE TITLE
Customizing Issue Tags

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#9]
Issue tags of our repository should be reviewed and new tags should be added to make them more useful. Possible additions are:
- Tags showing different priority levels
- Type of the task

**Comment by canatakan** [comment]
I made some research on issue tags, and the details about that can be found [here](https://github.com/bounswe/bounswe2022group7/issues/14).

Also, I made some changes accordingly. Tags showing different priority levels, and types of the tasks are added.

Another label type for stating the difficulty of a task can also be added if wanted.

**Comment by azizamankenova** [comment]
I have changed the colors of different labels according to their type. The labels with the same type have the same color, but different tones. This way it is easier to navigate through the labels. 

Also, difficulty labels and type: discussion labels are added.

**Comment by canatakan** [comment]
We talked about our labels in our first meeting and we concluded that our issue labels are great. Since this topic is discussed in the meeting, it can be said that these changes are reviewed by all our team members.

Hence, marking it as "Completed".

**Comment by azizamankenova** [comment]
I am closing this issue, as the task is completed.
