### ISSUE TITLE
[UML Class Diagram] Complete "ForumPage" class

### ISSUE THREAD

**Issue by AlicanM** [bounswe/bounswe2022group7#91]
As mentioned in this [comment](https://github.com/bounswe/bounswe2022group7/issues/86#issuecomment-1087586808), we shall complete the "ForumPage " class.

Deadline: 05/04/2022, 13.00

**Comment by AlicanM** [comment]
I added the DiscussionForum and ForumThread classes attributes and operations.
I cant add the lines required, because lucidchat says i need premium features.

@oguzpancuk, can you review the classes to see if i miss anything and also if the site gives you permission, can you add the required lines.

**Comment by AlicanM** [comment]
I added DiscussionForumPage and ThreadReport classes attributes and operations, also the necessary lines.

**Comment by CahidArda** [comment]
Hi @AlicanM,

I was looking at the classes related to the forum and there is something I couldn't understand. Both the ForumPost and ForumThread have a `List<ForumThread>` field. Was it intentional?

**Comment by CahidArda** [comment]
I think I understand how the Forum is designed now. I will look like the forum in Moodle or Reddit where there are threads branching out from every post. I feel like we don't need to complicate things by trying to implement such a functionality.

Instead I was thinking maybe we can merge the classes related to the discussion forum and the ones related to the comments. There can be a single `Thread` class to represent both. Then we can add a `thread: Thread` field to the `ArtItem` and `Event` classes. Also we would add a `List<Thread>` to the `DiscussionPage` class.

This way, I think it would be easier to implement all the details of the comment section or the forum.

**Comment by CahidArda** [comment]
The `ForumPage` class was redesigned as suggested in the comment above. A new issue (#115) was created about merging the forum and the comment section classes.

Another issue (#117) was created about handling the changes in the requirements.
