### ISSUE TITLE
[UML Class Diagram] Complete "Notifications" and "Comment" classes

### ISSUE THREAD

**Issue by mehmeteminipekdal** [bounswe/bounswe2022group7#94]
As mentioned in the [comment](https://github.com/bounswe/bounswe2022group7/issues/86#issuecomment-1087586808), we shall complete the "Notifications" and "Comment" classes.

Deadline: 05/04/2022, 13.00

**Comment by atillaturkmen** [comment]
- Added isRead() and setIsRead() functions to Notification class.
- Connected Notification class to RegisteredUser class with composition arrow.
- Added upvote and downvote fields with getter and setters to Comment class.
- Added function to remove comments in CommentSection class.
- Added CommentReport class and reports list to Comment class which contains CommentReports.
