### ISSUE TITLE
[Sequence Diagram]Create Sequence Diagram for bidding

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#99]
Create a sequence diagram for the above events in accordance with the Use Case Diagram and Class Diagram.
To be reviewed by @canatakan 

Deadline: 15.04.2022 @19.00

**Comment by demet47** [comment]
I edited class diagram:
- added getArtItems() for Artist class
- moved bid() to Auction
- removed setMinimumPrice(minimumPrice:double), getRemainingTime():Time, getMinimumPrice():double and setDeadline(endingDate:Date) methods from Auction class since AuctionInfo has the same setters and getters

**Comment by demet47** [comment]
I finished drawing the sequence diagram. The current version requires that user do the bidding operation again if we have an internal error while adding the bid to DB.

The diagram can be found [here](https://lucid.app/lucidchart/507965f6-766a-4a4d-83a6-1b72cc8cb821/edit?page=g_.9hlKSB4Hx#)

**Comment by canatakan** [comment]
As we talked in the meeting, there were some minor issues with these points below:

* Sequential flow of the process was not clear
* Creation of the Bid object did not return the instance to the relevant class/actor
* The alternative cases were somehow confusing

The diagram is apparently finalized and these problems are solved. The job is, therefore, completed.

**Comment by demet47** [comment]
Changed the whole structure of bidding sequence diagram, doing some changes in UML Class Diagram in parallel accordingly.
- Removed duplicate methods for Auction and AuctionInfo
- Moved bid(price:double, bidder:RegisteredUser) from bid to Auction

Latest version can be found from [here](https://lucid.app/lucidchart/507965f6-766a-4a4d-83a6-1b72cc8cb821/edit?page=g_.9hlKSB4Hx#)
